% enable_recursion.
% enable_pi.

% max_vars(3).
% max_body(4).
% max_clauses(3).

head_pred(dangerous,1).
% head_pred(supports,2).

% Only for stable
% body_pred(recursive_supports,2).
body_pred(belongsTo,2).
body_pred(bird,1).
body_pred(canCollapse,2).
body_pred(isBelow,2).
body_pred(isCollapsable,1).
body_pred(isLeft,2).
body_pred(isOn,2).
body_pred(isOver,2).
body_pred(isRight,2).
body_pred(protects,2).
body_pred(structure,1).
body_pred(birdInSling,1).
body_pred(blackBird,1).
body_pred(blueBird,1).
body_pred(redBird,1).
body_pred(yellowBird,1).
body_pred(whiteBird,1).
body_pred(wood,1).
body_pred(stone,1).
body_pred(ice,1).
body_pred(pig,1).
body_pred(collapsesAway,2).
body_pred(collapsesTowards,2).
body_pred(smallSize,1).
body_pred(mediumSize,1).
body_pred(largeSize,1).
body_pred(formBar,1).
body_pred(formBlock,1).
body_pred(formCircle,1).
body_pred(formPoly,1).
body_pred(orientedVertically,1).
body_pred(orientedHorizontally,1).
body_pred(hill,1).

body_pred(before,2).
body_pred(after,2).
body_pred(meets,2).
body_pred(meetsI,2).
body_pred(mostOverlapsMost,2).
body_pred(mostOverlapsMostI,2).
body_pred(lessOverlapsMost,2).
body_pred(lessOverlapsMostI,2).
body_pred(mostOverlapsLess,2).
body_pred(mostOverlapsLessI,2).
body_pred(lessOverlapsLess,2).
body_pred(lessOverlapsLessI,2).
body_pred(lessStarts,2).
body_pred(lessStartsI,2).
body_pred(leftDuring,2).
body_pred(leftDuringI,2).
body_pred(centerDuring,2).
body_pred(centerDuringI,2).
body_pred(rightDuring,2).
body_pred(rightDuringI,2).
body_pred(lessFinishes,2).
body_pred(lessFinishesI,2).
body_pred(mostFinishes,2).
body_pred(mostFinishesI,2).
body_pred(equal,2).
body_pred(noContact,2).
body_pred(surfaceContact,2).
body_pred(pointContact,2).
body_pred(pointSurfaceContact,2).
body_pred(horizontalContact,2).
body_pred(verticalContact,2).
body_pred(below,2).
body_pred(above,2).
body_pred(on,2).
body_pred(onI,2).
body_pred(overlapsY,2).
body_pred(overlapsYI,2).
body_pred(startsY,2).
body_pred(startsYI,2).
body_pred(duringY,2).
body_pred(duringYI,2).
body_pred(finishesY,2).
body_pred(finishesYI,2).
body_pred(equalY,2).
body_pred(object,1).
body_pred(fixed,1).
body_pred(mobile,1).

direction(before,(in,out)).
direction(after,(in,out)).
direction(meets,(in,out)).
direction(meetsI,(in,out)).
direction(mostOverlapsMost,(in,out)).
direction(mostOverlapsMostI,(in,out)).
direction(lessOverlapsMost,(in,out)).
direction(lessOverlapsMostI,(in,out)).
direction(mostOverlapsLess,(in,out)).
direction(mostOverlapsLessI,(in,out)).
direction(lessOverlapsLess,(in,out)).
direction(lessOverlapsLessI,(in,out)).
direction(lessStarts,(in,out)).
direction(lessStartsI,(in,out)).
direction(leftDuring,(in,out)).
direction(leftDuringI,(in,out)).
direction(centerDuring,(in,out)).
direction(centerDuringI,(in,out)).
direction(rightDuring,(in,out)).
direction(rightDuringI,(in,out)).
direction(lessFinishes,(in,out)).
direction(lessFinishesI,(in,out)).
direction(mostFinishes,(in,out)).
direction(mostFinishesI,(in,out)).
direction(equal,(in,in)).
direction(equalI,(in,in)).
direction(below,(in,out)).
direction(belowI,(in,out)).
direction(on,(in,out)).
direction(onI,(in,out)).
direction(overlapsY,(in,out)).
direction(overlapsYI,(in,out)).
direction(startsY,(in,out)).
direction(startsYI,(in,out)).
direction(duringY,(in,out)).
direction(duringYI,(in,out)).
direction(finishesY,(in,out)).
direction(finishesYI,(in,out)).
direction(equalY,(in,out)).
direction(object,(out,)).
direction(fixed,(out,)).
direction(mobile,(out,)).

direction(noContact,(in,in)).
direction(surfaceContact,(in,in)).
direction(pointContact,(in,in)).
direction(pointSurfaceContact,(in,in)).
direction(horizontalContact,(in,in)).
direction(verticalContact,(in,in)).

type(dangerous,(object,)).
type(belongsTo,(object,structure)).
type(bird,(bird,)).
type(canCollapse,(structure,structure)).
type(isBelow,(object,object)).
type(isCollapsable,(structure,)).
type(isLeft,(object,object)).
type(isOn,(object,object)).
type(isOver,(object,object)).
type(isRight,(object,object)).
type(protects,(structure,object)).
type(structure,(structure,)).
type(birdInSling,(bird,)).
type(blackBird,(bird,)).
type(blueBird,(bird,)).
type(redBird,(bird,)).
type(yellowBird,(bird,)).
type(whiteBird,(bird,)).
type(wood,(object,)).
type(stone,(object,)).
type(ice,(object,)).
type(pig,(object,)).
type(collapsesAway,(structure,structure)).
type(collapsesTowards,(structure,structure)).
type(smallSize,(object,)).
type(mediumSize,(object,)).
type(largeSize,(object,)).
type(formBar,(object,)).
type(formBlock,(object,)).
type(formCircle,(object,)).
type(formPoly,(object,)).
type(orientedVertically,(object,)).
type(orientedHorizontally,(object,)).
type(hill,(object,)).

type(before,(object,object)).
type(after,(object,object)).
type(meets,(object,object)).
type(meetsI,(object,object)).
type(mostOverlapsMost,(object,object)).
type(mostOverlapsMostI,(object,object)).
type(lessOverlapsMost,(object,object)).
type(lessOverlapsMostI,(object,object)).
type(mostOverlapsLess,(object,object)).
type(mostOverlapsLessI,(object,object)).
type(lessOverlapsLess,(object,object)).
type(lessOverlapsLessI,(object,object)).
type(lessStarts,(object,object)).
type(lessStartsI,(object,object)).
type(leftDuring,(object,object)).
type(leftDuringI,(object,object)).
type(centerDuring,(object,object)).
type(centerDuringI,(object,object)).
type(rightDuring,(object,object)).
type(rightDuringI,(object,object)).
type(lessFinishes,(object,object)).
type(lessFinishesI,(object,object)).
type(mostFinishes,(object,object)).
type(mostFinishesI,(object,object)).
type(equal,(object,object)).
type(equalI,(object,object)).
type(below,(object,object)).
type(belowI,(object,object)).
type(on,(object,object)).
type(onI,(object,object)).
type(overlapsY,(object,object)).
type(overlapsYI,(object,object)).
type(startsY,(object,object)).
type(startsYI,(object,object)).
type(duringY,(object,object)).
type(duringYI,(object,object)).
type(finishesY,(object,object)).
type(finishesYI,(object,object)).
type(equalY,(object,object)).
type(object,(object,)).
type(fixed,(object,)).
type(mobile,(object,)).

type(noContact,(object,object)).
type(surfaceContact,(object,object)).
type(pointContact,(object,object)).
type(pointSurfaceContact,(object,object)).
type(horizontalContact,(object,object)).
type(verticalContact,(object,object)).