supports(A,B):- mobile(B),leftDuringI(B,A).
supports(A,B):- object(A),lessFinishes(A,B).
supports(A,B):- object(A),lessStartsI(A,B).
supports(A,B):- fixed(A),mostOverlapsLessI(A,B).
supports(A,B):- fixed(A),overlapsY(A,B).
supports(A,B):- fixed(A),mostFinishesI(A,B).
supports(A,B):- fixed(A),lessOverlapsMost(A,B).
supports(A,B):- object(A),mostOverlapsMostI(A,C),finishesYI(C,B).
supports(A,B):- object(A),meetsI(A,C),lessOverlapsLess(C,B).
supports(A,B):- object(A),mostFinishes(A,C),mostFinishesI(C,B).
supports(A,B):- object(A),lessOverlapsLessI(A,C),lessFinishesI(C,B).
supports(A,B):- object(A),lessOverlapsMost(A,C),mostFinishes(C,B).
supports(A,B):- object(A),overlapsY(A,C),duringY(C,B).
supports(A,B):- object(B),on(B,A),surfaceContact(A,B).
supports(A,B):- object(A),lessStartsI(A,C),startsYI(C,B).
supports(A,B):- object(A),finishesY(A,C),lessOverlapsMostI(C,B).
supports(A,B):- object(B),lessOverlapsLess(B,A),surfaceContact(A,B).
supports(A,B):- object(A),centerDuringI(A,C),lessOverlapsLess(C,B).
supports(A,B):- object(A),lessOverlapsLess(A,C),lessOverlapsMostI(C,B).
supports(A,B):- object(A),finishesY(A,C),mostFinishesI(C,B).
supports(A,B):- object(A),lessStartsI(A,C),meets(C,B).
supports(A,B):- object(A),centerDuringI(A,C),finishesY(C,B).
supports(A,B):- object(A),finishesYI(A,C),finishesYI(C,B).
supports(A,B):- object(A),lessOverlapsMostI(A,C),lessOverlapsLess(C,B).
supports(A,B):- object(A),finishesY(A,C),lessStarts(C,B).
supports(A,B):- object(A),lessStarts(A,C),lessOverlapsLessI(C,B).
supports(A,B):- object(A),rightDuringI(A,C),rightDuring(C,B).
supports(A,B):- object(B),lessOverlapsMost(B,A),surfaceContact(A,B).
supports(A,B):- object(A),lessOverlapsLessI(A,C),lessOverlapsLess(C,B).
supports(A,B):- mobile(B),lessOverlapsLessI(B,A),surfaceContact(A,B).
supports(A,B):- object(A),lessOverlapsMost(A,C),finishesY(C,B).
supports(A,B):- object(A),startsY(A,C),lessOverlapsMost(C,B).
supports(A,B):- object(A),leftDuringI(A,C),lessOverlapsMostI(C,B).
supports(A,B):- object(A),meetsI(A,C),mostOverlapsLess(C,B).
supports(A,B):- object(A),leftDuringI(A,C),startsYI(C,B).
supports(A,B):- object(A),rightDuring(A,C),mostOverlapsMost(C,B).
supports(A,B):- object(B),duringYI(B,A),surfaceContact(A,B).
supports(A,B):- object(A),centerDuringI(A,C),mostOverlapsMostI(C,B).
supports(A,B):- object(A),finishesY(A,C),lessStartsI(C,B).
supports(A,B):- object(A),meetsI(A,C),lessOverlapsMost(C,B).
supports(A,B):- object(A),lessOverlapsLess(A,C),mostOverlapsMostI(C,B).
supports(A,B):- object(A),lessFinishesI(A,C),onI(C,B).
supports(A,B):- mobile(B),rightDuringI(B,A),surfaceContact(A,B).
supports(A,B):- object(A),on(A,C),lessFinishes(C,B).
supports(A,B):- object(A),rightDuringI(A,C),startsYI(C,B).
supports(A,B):- object(A),centerDuringI(A,C),lessOverlapsLessI(C,B).
supports(A,B):- object(A),rightDuringI(A,C),meetsI(C,B).
supports(A,B):- object(A),finishesYI(A,C),lessFinishes(C,B).
supports(A,B):- object(A),centerDuring(A,C),lessOverlapsLessI(C,B).
supports(A,B):- object(A),leftDuringI(A,C),finishesY(C,B).
supports(A,B):- object(A),centerDuring(A,C),lessOverlapsMostI(C,B).
supports(A,B):- object(A),lessStartsI(A,C),finishesY(C,B).
supports(A,B):- object(A),centerDuringI(A,C),lessFinishesI(C,B).
supports(A,B):- object(A),leftDuringI(A,C),startsY(C,B).
supports(A,B):- object(A),meets(A,C),lessOverlapsLessI(C,B).
supports(A,B):- object(A),lessOverlapsMost(A,C),overlapsYI(C,B).
supports(A,B):- object(A),mostFinishesI(A,C),lessOverlapsLess(C,B).
supports(A,B):- object(A),lessOverlapsMost(A,C),mostOverlapsMostI(C,B).
supports(A,B):- object(A),lessOverlapsLessI(A,C),mostOverlapsLess(C,B).
