supports(A,B):- mobile(A),centerDuring(A,B).
supports(A,B):- object(B),lessOverlapsLess(B,A).
supports(A,B):- fixed(A),startsY(A,B).
supports(A,B):- mobile(A),centerDuringI(A,B).
supports(A,B):- object(A),onI(A,B),lessStartsI(A,B).
supports(A,B):- object(A),rightDuringI(A,C),mostFinishesI(C,B).
supports(A,B):- object(A),onI(A,B),lessOverlapsLess(A,B).
supports(A,B):- object(A),onI(A,B),mostOverlapsLess(A,B).
supports(A,B):- object(A),leftDuringI(A,B),onI(A,B).
supports(A,B):- object(A),mostFinishesI(A,B),onI(A,B).
supports(A,B):- object(B),startsYI(B,C),mostOverlapsMostI(C,A).
supports(A,B):- fixed(C),finishesYI(C,B),object(A).
supports(A,B):- object(A),mostFinishes(A,C),mostOverlapsLess(C,B).
supports(A,B):- object(A),startsY(A,B),lessOverlapsMostI(A,B).
supports(A,B):- object(A),onI(A,B),mostOverlapsLessI(A,B).
supports(A,B):- object(A),mostOverlapsMostI(A,C),overlapsY(C,B).
supports(A,B):- object(A),rightDuringI(A,B),onI(A,B).
supports(A,B):- object(A),mostOverlapsLess(A,C),meetsI(C,B).
supports(A,B):- object(A),onI(A,B),lessOverlapsMost(A,B).
supports(A,B):- object(A),onI(A,B),equal(A,B).
supports(A,B):- object(A),lessOverlapsMostI(A,B),surfaceContact(A,B).
supports(A,B):- object(A),mostOverlapsLessI(A,C),mostOverlapsMostI(C,B).
supports(A,B):- object(B),rightDuringI(B,C),rightDuring(C,A).
supports(A,B):- object(A),lessFinishesI(A,C),meetsI(C,B).
supports(A,B):- object(A),mostOverlapsMost(A,C),mostOverlapsLessI(C,B).
supports(A,B):- object(A),mostOverlapsMostI(A,C),rightDuringI(C,B).
supports(A,B):- object(A),mostOverlapsMostI(A,C),mostFinishesI(C,B).
supports(A,B):- object(A),onI(A,B),lessStarts(A,B).
supports(A,B):- object(C),finishesY(C,A),lessStartsI(A,B).
supports(A,B):- object(B),rightDuring(B,C),mostFinishesI(C,A).
supports(A,B):- object(A),startsY(A,B),lessOverlapsLess(A,B).
supports(A,B):- object(A),meets(A,C),lessOverlapsLessI(C,B).
supports(A,B):- object(C),finishesY(C,A),mostFinishes(A,B).
supports(A,B):- object(A),lessFinishesI(A,B),on(B,A).
supports(A,B):- object(B),mostOverlapsMost(B,C),overlapsYI(C,A).
supports(A,B):- object(C),lessStarts(C,B),startsYI(B,A).
supports(A,B):- object(A),lessFinishesI(A,C),overlapsYI(C,B).
supports(A,B):- object(A),meetsI(A,C),lessOverlapsLess(C,B).
supports(A,B):- object(A),centerDuringI(A,C),centerDuring(C,B).
supports(A,B):- object(A),rightDuringI(A,C),meetsI(C,B).
supports(A,B):- object(A),overlapsY(A,B),verticalContact(A,B).
supports(A,B):- object(A),mostOverlapsMost(A,B),pointSurfaceContact(A,B).
supports(A,B):- object(C),after(C,A),mostOverlapsMostI(A,B).
supports(A,B):- object(A),startsY(A,B),mostOverlapsLess(A,B).
supports(A,B):- object(A),lessOverlapsMost(A,C),mostOverlapsMost(C,B).
supports(A,B):- object(C),lessStarts(C,A),mostOverlapsMost(A,B).
supports(A,B):- object(A),lessFinishesI(A,C),mostFinishes(C,B).
