supports(A,B):- object(A),lessOverlapsLessI(A,B).
supports(A,B):- object(A),rightDuringI(A,B).
supports(A,B):- object(A),lessFinishes(A,B).
supports(A,B):- object(B),rightDuringI(B,A).
supports(A,B):- object(A),lessOverlapsMostI(A,B).
supports(A,B):- object(A),lessOverlapsMost(A,B).
supports(A,B):- object(A),mostFinishes(A,B),on(B,A).
supports(A,B):- object(A),centerDuring(A,C),mostOverlapsMost(C,B).
supports(A,B):- object(A),overlapsY(A,B),mostOverlapsLessI(B,A).
supports(A,B):- object(A),lessStarts(A,B),on(B,A).
supports(A,B):- object(A),onI(A,B),mostOverlapsLess(B,A).
supports(A,B):- object(A),finishesYI(A,B),mostFinishes(B,A).
supports(A,B):- object(A),mostOverlapsMost(A,B),on(B,A).
supports(A,B):- object(A),lessStartsI(A,C),mostOverlapsLess(C,B).
supports(A,B):- object(A),mostFinishesI(A,C),lessStarts(C,B).
supports(A,B):- object(A),duringYI(A,C),lessOverlapsMost(C,B).
supports(A,B):- object(A),onI(A,B),mostFinishes(B,A).
supports(A,B):- object(A),mostOverlapsMost(A,C),mostOverlapsLessI(C,B).
supports(A,B):- object(A),centerDuring(A,B),on(B,A).
supports(A,B):- object(A),onI(A,B),lessOverlapsMostI(B,A).
supports(A,B):- object(A),mostOverlapsLess(A,B),startsYI(B,A).
supports(A,B):- object(A),lessFinishesI(A,B),on(B,A).
supports(A,B):- object(A),mostOverlapsLess(A,C),overlapsY(C,B).
supports(A,B):- object(A),onI(A,B),startsYI(B,A).
supports(A,B):- object(A),lessStartsI(A,B),duringY(B,A).
supports(A,B):- object(A),mostOverlapsMost(A,C),duringYI(C,B).
supports(A,B):- object(A),finishesYI(A,B),verticalContact(B,A).
supports(A,B):- object(A),onI(A,B),meetsI(B,A).
supports(A,B):- object(A),mostOverlapsMostI(A,C),centerDuringI(C,B).
supports(A,B):- object(A),rightDuringI(A,C),meetsI(C,B).
supports(A,B):- object(A),onI(A,B),lessStarts(B,A).
supports(A,B):- object(A),mostOverlapsMostI(A,C),rightDuringI(C,B).
supports(A,B):- object(A),meetsI(A,B),duringYI(B,A).
supports(A,B):- object(A),centerDuringI(A,B),on(B,A).
supports(A,B):- object(A),overlapsY(A,B),surfaceContact(A,B).
supports(A,B):- object(A),mostFinishes(A,C),centerDuringI(C,B).
supports(A,B):- object(A),lessFinishesI(A,C),meetsI(C,B).
supports(A,B):- object(A),lessOverlapsLess(A,B),on(B,A).
supports(A,B):- object(A),finishesY(A,C),overlapsY(C,B).
supports(A,B):- object(A),onI(A,B),equal(B,A).
supports(A,B):- object(A),mostOverlapsMostI(A,B),startsYI(B,A).
supports(A,B):- object(A),mostOverlapsMost(A,B),overlapsYI(B,A).
