supports(A,B):- fixed(A),startsY(A,B).
supports(A,B):- fixed(C),rightDuring(C,A),onI(A,B).
supports(A,B):- fixed(C),lessOverlapsMostI(C,A),onI(A,B).
supports(A,B):- object(A),onI(A,B),rightDuring(B,A).
supports(A,B):- fixed(A),mobile(B),pointContact(B,A).
supports(A,B):- fixed(C),below(C,B),centerDuring(B,A).
supports(A,B):- mobile(B),leftDuringI(B,A).
supports(A,B):- fixed(C),leftDuringI(C,A),mostOverlapsMostI(A,B).
supports(A,B):- object(A),finishesYI(A,C),rightDuring(C,B).
supports(A,B):- object(A),mostFinishesI(A,C),startsYI(C,B).
supports(A,B):- object(A),mostOverlapsMost(A,C),leftDuringI(C,B).
supports(A,B):- object(A),mostFinishesI(A,C),mostFinishesI(C,B).
supports(A,B):- fixed(C),after(C,A),mostFinishes(A,B).
supports(A,B):- fixed(C),equalY(C,A),lessOverlapsMost(C,B).
supports(A,B):- fixed(C),onI(C,A),lessFinishes(A,B).
supports(A,B):- fixed(C),centerDuringI(C,B),startsYI(B,A).
supports(A,B):- fixed(C),mostFinishesI(C,A),mostOverlapsLessI(A,B).
supports(A,B):- fixed(C),lessFinishesI(C,B),on(B,A).
supports(A,B):- object(A),mostFinishes(A,C),lessFinishesI(C,B).
supports(A,B):- object(A),lessOverlapsLessI(A,C),lessFinishesI(C,B).
supports(A,B):- fixed(C),startsY(C,A),mostOverlapsLess(A,B).
supports(A,B):- object(A),onI(A,B),rightDuring(A,B).
supports(A,B):- object(A),rightDuring(A,C),mostFinishesI(C,B).
supports(A,B):- fixed(C),leftDuringI(C,A),lessOverlapsMostI(A,B).
supports(A,B):- object(A),meets(A,C),mostFinishes(C,B).
supports(A,B):- fixed(C),rightDuringI(C,A),lessFinishes(A,B).
supports(A,B):- fixed(C),onI(C,A),lessOverlapsMostI(A,B).
supports(A,B):- fixed(C),mobile(A),overlapsY(C,B).
supports(A,B):- fixed(C),onI(C,A),mostOverlapsMost(A,B).
supports(A,B):- fixed(C),lessStartsI(C,B),mostOverlapsLess(B,A).
supports(A,B):- object(A),lessOverlapsMost(A,C),mostOverlapsMost(C,B).
supports(A,B):- object(A),startsYI(A,C),lessOverlapsLessI(C,B).
supports(A,B):- object(A),lessOverlapsMostI(A,C),mostFinishesI(C,B).
supports(A,B):- fixed(C),rightDuringI(C,B),leftDuring(B,A).
supports(A,B):- object(A),lessOverlapsLess(A,C),leftDuringI(C,B).
supports(A,B):- object(A),finishesY(A,C),overlapsY(C,B).
supports(A,B):- object(A),lessFinishesI(A,C),meets(C,B).
supports(A,B):- fixed(C),startsY(C,A),lessOverlapsLessI(A,B).
supports(A,B):- object(A),mostFinishes(A,C),mostOverlapsMost(C,B).
supports(A,B):- object(A),meets(A,C),lessFinishes(C,B).
supports(A,B):- fixed(C),leftDuringI(C,B),mostOverlapsMostI(B,A).
supports(A,B):- fixed(C),leftDuringI(C,A),lessStarts(A,B).
supports(A,B):- fixed(C),lessStartsI(C,A),lessOverlapsMost(A,B).
supports(A,B):- object(A),centerDuring(A,C),mostFinishesI(C,B).
supports(A,B):- fixed(C),mostFinishesI(C,A),on(C,B).
supports(A,B):- object(A),mostOverlapsMostI(A,C),lessFinishes(C,B).
supports(A,B):- mobile(B),fixed(A),mostOverlapsLess(A,B).
supports(A,B):- fixed(C),below(C,A),finishesYI(A,B).
supports(A,B):- fixed(C),onI(C,A),lessStartsI(C,B).
supports(A,B):- object(A),mostOverlapsLessI(A,C),lessOverlapsMost(C,B).
supports(A,B):- fixed(C),centerDuringI(C,B),mostFinishes(B,A).
supports(A,B):- object(A),overlapsYI(A,C),lessStarts(C,B).
supports(A,B):- fixed(C),rightDuringI(C,B),overlapsYI(B,A).
supports(A,B):- fixed(C),duringY(C,A),mobile(B).
supports(A,B):- fixed(A),leftDuringI(A,C),on(C,B).
supports(A,B):- fixed(C),centerDuringI(C,B),mostFinishesI(B,A).
supports(A,B):- fixed(C),startsY(C,A),lessOverlapsLess(A,B).
supports(A,B):- fixed(C),lessOverlapsMost(C,A),onI(A,B).
supports(A,B):- fixed(C),leftDuringI(C,B),mostFinishes(B,A).
supports(A,B):- fixed(C),centerDuringI(C,A),startsY(A,B).
supports(A,B):- object(A),lessOverlapsLess(A,C),finishesY(C,B).
supports(A,B):- object(A),mostFinishesI(A,C),mostOverlapsMostI(C,B).
supports(A,B):- fixed(C),before(C,A),lessFinishesI(A,B).
supports(A,B):- fixed(C),lessStartsI(C,A),onI(A,B).
supports(A,B):- object(A),mostOverlapsLessI(A,C),mostFinishesI(C,B).
supports(A,B):- object(A),lessStarts(A,C),mostFinishes(C,B).
supports(A,B):- object(A),lessFinishesI(A,C),leftDuring(C,B).
supports(A,B):- fixed(C),centerDuringI(C,A),overlapsY(A,B).
supports(A,B):- object(A),centerDuring(A,C),lessFinishesI(C,B).
supports(A,B):- object(A),leftDuring(A,C),mostOverlapsLessI(C,B).
