supports(A,B):- mobile(A),centerDuring(A,B).
supports(A,B):- object(B),lessOverlapsLess(B,A).
supports(A,B):- mobile(A),lessOverlapsLessI(A,B).
supports(A,B):- fixed(A),startsY(A,B).
supports(A,B):- mobile(A),centerDuringI(A,B).
supports(A,B):- fixed(A),mostOverlapsLess(A,B).
supports(A,B):- fixed(A),rightDuringI(A,B).
supports(A,B):- mobile(C),mostOverlapsLessI(C,A),startsY(A,B).
supports(A,B):- mobile(C),lessOverlapsLessI(C,B),meetsI(C,A).
supports(A,B):- mobile(C),centerDuringI(C,A),mostOverlapsLess(A,B).
supports(A,B):- mobile(C),lessStarts(C,A),lessStarts(C,B).
supports(A,B):- mobile(C),lessStarts(C,B),startsYI(B,A).
supports(A,B):- mobile(C),mostOverlapsMost(C,A),mostFinishesI(A,B).
supports(A,B):- mobile(C),after(C,A),mostOverlapsMostI(A,B).
supports(A,B):- mobile(C),lessFinishes(C,A),lessOverlapsLess(A,B).
supports(A,B):- mobile(C),overlapsY(C,B),lessFinishes(B,A).
supports(A,B):- mobile(C),rightDuring(C,A),meets(A,B).
supports(A,B):- mobile(C),before(C,A),lessOverlapsMost(A,B).
supports(A,B):- mobile(C),lessFinishesI(C,A),startsY(A,B).
supports(A,B):- mobile(C),lessOverlapsMost(C,B),lessOverlapsLess(C,A).
supports(A,B):- mobile(C),mostFinishes(C,A),rightDuringI(C,B).
supports(A,B):- mobile(C),lessOverlapsMostI(C,A),lessOverlapsMostI(A,B).
supports(A,B):- mobile(C),lessOverlapsLessI(C,A),lessStartsI(A,B).
supports(A,B):- mobile(C),mostOverlapsMostI(C,A),lessStartsI(A,B).
supports(A,B):- mobile(C),mostFinishesI(C,B),mostOverlapsMost(C,A).
supports(A,B):- mobile(C),lessOverlapsLessI(C,B),lessOverlapsLessI(B,A).
supports(A,B):- mobile(C),finishesY(C,B),lessOverlapsLessI(B,A).
supports(A,B):- mobile(C),lessOverlapsLessI(C,B),lessStarts(C,A).
supports(A,B):- mobile(C),lessFinishes(C,A),mostFinishesI(A,B).
supports(A,B):- mobile(C),duringY(C,A),below(C,B).
supports(A,B):- mobile(C),mostOverlapsLess(C,B),mostFinishesI(C,A).
supports(A,B):- mobile(C),mostOverlapsMost(C,B),lessStarts(C,A).
supports(A,B):- mobile(C),mostOverlapsLess(C,B),lessStartsI(B,A).
supports(A,B):- mobile(C),startsYI(C,A),mostFinishes(A,B).
supports(A,B):- mobile(C),mostOverlapsLess(C,B),lessStarts(C,A).
supports(A,B):- mobile(C),lessFinishes(C,A),meetsI(C,B).
supports(A,B):- mobile(C),rightDuring(C,B),on(B,A).
supports(A,B):- mobile(C),startsY(C,A),mostFinishesI(A,B).
supports(A,B):- mobile(C),centerDuringI(C,B),mostFinishes(B,A).
supports(A,B):- mobile(C),centerDuring(C,A),centerDuring(C,B).
supports(A,B):- mobile(C),leftDuringI(C,B),on(B,A).
supports(A,B):- mobile(C),lessOverlapsLess(C,A),mostFinishesI(A,B).
supports(A,B):- mobile(C),mostFinishesI(C,A),mostFinishesI(A,B).
supports(A,B):- mobile(C),meetsI(C,B),mostOverlapsLessI(C,A).
supports(A,B):- mobile(C),startsY(C,B),lessOverlapsMost(B,A).
supports(A,B):- mobile(C),mostOverlapsMostI(C,B),mostOverlapsLess(C,A).
supports(A,B):- mobile(C),lessOverlapsLess(C,B),meets(C,A).
supports(A,B):- mobile(C),centerDuringI(C,A),centerDuringI(C,B).
supports(A,B):- mobile(C),mostOverlapsMost(C,B),lessFinishes(B,A).
supports(A,B):- mobile(C),lessFinishes(C,A),overlapsYI(C,B).
supports(A,B):- mobile(C),startsYI(C,A),mostOverlapsMost(A,B).
