supports(A,B):- lessFinishes(B,A).
supports(A,B):- lessFinishes(A,B).
supports(A,B):- lessStarts(A,B).
supports(A,B):- centerDuring(A,B).
supports(A,B):- lessStarts(B,A).
supports(A,B):- mostFinishes(B,A).
supports(A,B):- leftDuring(A,B).
supports(A,B):- on(B,A),mostOverlapsLess(B,A).
supports(A,B):- lessOverlapsMost(A,C),leftDuring(C,B).
supports(A,B):- finishesY(B,A),lessOverlapsLess(A,B).
supports(A,B):- on(B,A),mostOverlapsMost(B,A).
supports(A,B):- verticalContact(B,A),on(B,A).
supports(A,B):- on(B,A),lessOverlapsLess(B,A).
supports(A,B):- surfaceContact(A,B),overlapsY(A,B).
supports(A,B):- startsY(A,B),lessOverlapsLess(A,B).
supports(A,B):- verticalContact(B,A),finishesY(B,A).
supports(A,B):- centerDuring(B,A),on(B,A).
supports(A,B):- mostOverlapsMost(A,C),centerDuring(C,B).
supports(A,B):- mostOverlapsLess(A,B),startsY(A,B).
supports(A,B):- startsY(A,B),surfaceContact(A,B).
supports(A,B):- on(A,C),leftDuring(C,B).
supports(A,B):- overlapsY(A,B),centerDuring(B,A).
supports(A,B):- fixed(A),startsY(A,B).
supports(A,B):- lessOverlapsLess(B,A),startsY(A,B).
supports(A,B):- on(B,A),lessOverlapsLess(A,B).
supports(A,B):- overlapsY(A,B),mostOverlapsMost(B,A).
supports(A,B):- meets(B,A),on(B,A).
supports(A,B):- meets(B,A),startsY(B,A).
supports(A,B):- mostOverlapsLess(B,A),startsY(A,B).
supports(A,B):- lessOverlapsMost(A,B),on(B,A).
supports(A,B):- overlapsY(B,C),mostOverlapsLess(C,A).
supports(A,B):- equal(A,B),on(B,A).
supports(A,B):- meets(A,C),lessOverlapsLess(B,C).