supports(A,B):- fixed(A),mostOverlapsMost(A,B).
supports(A,B):- fixed(A),mostOverlapsMostI(A,B).
supports(A,B):- object(A),lessStartsI(A,B).
supports(A,B):- fixed(A),mostOverlapsLessI(A,B).
supports(A,B):- object(A),lessFinishes(A,B).
supports(A,B):- fixed(A),mostFinishesI(A,B).
supports(A,B):- fixed(A),rightDuringI(A,B).
supports(A,B):- fixed(A),lessFinishesI(A,B).
supports(A,B):- fixed(A),leftDuringI(A,B).
supports(A,B):- fixed(A),overlapsY(A,B).
supports(A,B):- mobile(B),rightDuringI(B,A).
supports(A,B):- object(A),lessOverlapsMostI(A,B).
supports(A,B):- object(A),centerDuringI(A,C),lessOverlapsMost(C,B).
supports(A,B):- mobile(A),lessStarts(A,C),lessOverlapsLessI(C,B).
supports(A,B):- mobile(A),mostFinishes(A,B),onI(A,B).
supports(A,B):- mobile(A),lessOverlapsLess(A,B),onI(A,B).
supports(A,B):- mobile(A),onI(A,B),mostOverlapsMostI(A,B).
supports(A,B):- mobile(A),rightDuringI(A,B),onI(A,B).
supports(A,B):- mobile(A),lessStarts(A,C),centerDuring(C,B).
supports(A,B):- mobile(A),meetsI(A,C),lessOverlapsMost(C,B).
supports(A,B):- mobile(A),mostOverlapsLessI(A,C),lessOverlapsMostI(C,B).
supports(A,B):- mobile(A),on(A,C),lessFinishes(C,B).
supports(A,B):- mobile(A),lessStartsI(A,C),centerDuring(C,B).
supports(A,B):- mobile(A),mostFinishesI(A,B),onI(A,B).
supports(A,B):- mobile(A),meets(A,C),lessOverlapsMostI(C,B).
supports(A,B):- mobile(A),meets(A,B),onI(A,B).
supports(A,B):- mobile(A),lessFinishesI(A,C),mostOverlapsLess(C,B).
supports(A,B):- mobile(A),finishesYI(A,B),lessOverlapsLess(B,A).
supports(A,B):- mobile(A),onI(A,B),equal(A,B).
supports(A,B):- mobile(A),mostOverlapsLess(A,B),overlapsY(A,B).
supports(A,B):- fixed(C),lessStartsI(C,B),object(A).
supports(A,B):- mobile(A),rightDuringI(A,C),lessOverlapsMostI(C,B).
supports(A,B):- mobile(A),overlapsY(A,B),equal(A,B).
supports(A,B):- mobile(A),rightDuringI(A,C),mostOverlapsMost(C,B).
supports(A,B):- mobile(A),mostOverlapsMostI(A,C),mostOverlapsLess(C,B).
supports(A,B):- mobile(A),onI(A,B),surfaceContact(A,B).
supports(A,B):- mobile(A),mostOverlapsMostI(A,C),centerDuringI(C,B).
supports(A,B):- mobile(A),onI(A,B),mostOverlapsMost(A,B).
supports(A,B):- mobile(A),duringY(A,B),surfaceContact(A,B).
supports(A,B):- mobile(A),overlapsY(A,B),verticalContact(A,B).
supports(A,B):- object(A),startsY(A,C),lessOverlapsMost(C,B).
supports(A,B):- mobile(A),overlapsY(A,B),lessOverlapsLessI(B,A).
supports(A,B):- mobile(A),lessStarts(A,B),startsY(A,B).
supports(A,B):- mobile(A),onI(A,B),lessOverlapsMostI(B,A).
supports(A,B):- mobile(A),onI(A,B),lessOverlapsLess(B,A).
supports(A,B):- mobile(A),lessOverlapsMost(A,C),overlapsYI(C,B).
supports(A,B):- mobile(A),lessOverlapsLess(A,B),equalY(A,B).
supports(A,B):- mobile(A),onI(A,B),lessFinishesI(A,B).
supports(A,B):- mobile(A),overlapsY(A,C),lessStarts(C,B).
supports(A,B):- mobile(A),lessFinishesI(A,C),overlapsYI(C,B).
supports(A,B):- mobile(A),onI(A,B),leftDuringI(A,B).
supports(A,B):- mobile(A),lessStarts(A,B),onI(A,B).
supports(A,B):- mobile(A),mostOverlapsLess(A,B),startsY(A,B).
supports(A,B):- fixed(C),lessOverlapsLess(C,B),object(A).
supports(A,B):- mobile(A),lessOverlapsLess(A,C),mostOverlapsMostI(C,B).
supports(A,B):- mobile(A),meetsI(A,C),lessOverlapsLess(C,B).
supports(A,B):- mobile(A),overlapsY(A,B),mostOverlapsMostI(B,A).
supports(A,B):- mobile(A),overlapsY(A,B),mostFinishesI(A,B).
supports(A,B):- mobile(A),onI(A,B),centerDuringI(A,B).
supports(A,B):- mobile(A),finishesY(A,C),mostFinishesI(C,B).
supports(A,B):- mobile(A),lessOverlapsLessI(A,B),surfaceContact(A,B).
supports(A,B):- mobile(A),finishesYI(A,C),lessFinishes(C,B).
supports(A,B):- mobile(A),startsY(A,B),lessOverlapsLess(A,B).
supports(A,B):- object(B),startsYI(B,A),lessOverlapsMost(A,B).
supports(A,B):- mobile(A),overlapsY(A,B),pointContact(A,B).
supports(A,B):- mobile(A),lessFinishesI(A,C),onI(C,B).
supports(A,B):- mobile(A),mostFinishesI(A,C),lessOverlapsLess(C,B).
supports(A,B):- mobile(A),onI(A,B),mostOverlapsLess(B,A).
