supports(A,B):- mobile(A),lessFinishesI(A,B).
supports(A,B):- object(B),rightDuring(B,A).
supports(A,B):- mobile(A),lessOverlapsLess(A,B).
supports(A,B):- object(B),lessOverlapsLessI(B,A).
supports(A,B):- object(B),leftDuringI(B,A).
supports(A,B):- mobile(B),lessStartsI(B,A).
supports(A,B):- mobile(A),mostFinishes(A,B).
supports(A,B):- object(A),overlapsY(A,B),mostOverlapsMostI(B,A).
supports(A,B):- object(A),rightDuringI(A,B),surfaceContact(A,B).
supports(A,B):- fixed(C),mostOverlapsMostI(C,A),onI(A,B).
supports(A,B):- object(A),mostOverlapsLess(A,B),overlapsY(A,B).
supports(A,B):- fixed(C),centerDuringI(C,B),lessOverlapsMost(B,A).
supports(A,B):- object(A),onI(A,B),centerDuring(A,B).
supports(A,B):- fixed(C),below(C,B),lessStarts(B,A).
supports(A,B):- object(A),onI(A,B),pointSurfaceContact(A,B).
supports(A,B):- object(A),onI(A,B),centerDuringI(A,B).
supports(A,B):- object(A),leftDuring(A,B),mobile(B).
supports(A,B):- fixed(C),equalY(C,A),meets(C,B).
supports(A,B):- fixed(C),rightDuringI(C,A),overlapsY(A,B).
supports(A,B):- object(A),mostOverlapsMost(A,B),surfaceContact(A,B).
supports(A,B):- object(A),mostOverlapsMostI(A,B),onI(A,B).
supports(A,B):- object(A),onI(A,B),leftDuringI(A,B).
supports(A,B):- fixed(C),centerDuringI(C,A),mostOverlapsMost(A,B).
supports(A,B):- object(A),mostFinishesI(A,B),overlapsY(A,B).
supports(A,B):- fixed(C),startsY(C,B),on(C,A).
supports(A,B):- object(A),finishesYI(A,B),surfaceContact(A,B).
supports(A,B):- object(A),startsY(A,B),lessOverlapsLessI(A,B).
supports(A,B):- mobile(B),object(A),equal(A,B).
supports(A,B):- object(A),mostOverlapsMost(A,B),overlapsY(A,B).
supports(A,B):- object(A),overlapsY(A,B),centerDuringI(A,B).
supports(A,B):- object(A),onI(A,B),mostFinishesI(A,B).
supports(A,B):- object(A),onI(A,B),horizontalContact(A,B).
supports(A,B):- object(A),overlapsY(A,B),centerDuring(A,B).
supports(A,B):- object(A),startsY(A,B),verticalContact(A,B).
supports(A,B):- object(A),onI(A,B),lessOverlapsMost(A,B).
supports(A,B):- fixed(C),duringY(C,A),startsY(C,B).
supports(A,B):- fixed(C),mostOverlapsLessI(C,A),overlapsY(A,B).
supports(A,B):- fixed(C),lessOverlapsMost(C,B),on(B,A).
supports(A,B):- fixed(C),mostOverlapsLessI(C,A),mostOverlapsMost(A,B).
supports(A,B):- object(A),lessOverlapsMostI(A,B),onI(A,B).
supports(A,B):- fixed(C),onI(C,A),lessOverlapsMost(A,B).
supports(A,B):- fixed(C),lessFinishesI(C,A),meetsI(A,B).
supports(A,B):- fixed(C),before(C,B),mostOverlapsLess(B,A).
supports(A,B):- fixed(C),onI(C,A),lessOverlapsLessI(A,B).
supports(A,B):- object(A),startsY(A,B),mostOverlapsLess(A,B).
supports(A,B):- object(A),overlapsY(A,B),mostOverlapsMost(B,A).
supports(A,B):- object(A),overlapsY(A,B),lessOverlapsMostI(B,A).
