supports(A,B):- mobile(B),startsYI(B,A).
supports(A,B):- mobile(C),after(C,A),rightDuringI(A,B).
supports(A,B):- mobile(C),mostFinishes(C,A),lessOverlapsLess(A,B).
supports(A,B):- mobile(C),on(C,A),lessFinishesI(A,B).
supports(A,B):- mobile(C),lessOverlapsMostI(C,A),mostOverlapsLess(A,B).
supports(A,B):- mobile(C),lessOverlapsLessI(C,A),mostOverlapsLess(A,B).
supports(A,B):- mobile(C),meets(C,A),centerDuringI(A,B).
supports(A,B):- mobile(C),mostOverlapsLessI(C,A),centerDuringI(A,B).
supports(A,B):- mobile(C),mostOverlapsMostI(C,A),lessOverlapsMostI(A,B).
supports(A,B):- mobile(C),mostOverlapsLess(C,A),lessOverlapsLess(A,B).
supports(A,B):- mobile(C),meets(C,A),lessFinishes(A,B).
supports(A,B):- mobile(C),mostOverlapsMost(C,A),lessFinishesI(C,B).
supports(A,B):- mobile(C),centerDuringI(C,A),rightDuringI(A,B).
supports(A,B):- mobile(C),lessStartsI(C,A),meetsI(A,B).
supports(A,B):- mobile(C),centerDuringI(C,A),mostOverlapsLess(A,B).
supports(A,B):- mobile(C),onI(C,A),leftDuringI(A,B).
supports(A,B):- mobile(C),mostFinishesI(C,B),mostOverlapsMost(C,A).
supports(A,B):- mobile(C),mostOverlapsMost(C,A),mostFinishes(A,B).
supports(A,B):- mobile(C),rightDuring(C,A),lessOverlapsMostI(A,B).
supports(A,B):- mobile(C),lessFinishes(C,A),mostFinishesI(A,B).
supports(A,B):- mobile(C),mostOverlapsMost(C,B),centerDuringI(C,A).
supports(A,B):- mobile(C),mostOverlapsLess(C,A),leftDuringI(A,B).
supports(A,B):- mobile(C),mostOverlapsLessI(C,A),lessStartsI(C,B).
supports(A,B):- mobile(C),lessOverlapsMostI(C,A),lessOverlapsMostI(A,B).
supports(A,B):- mobile(C),mostOverlapsMostI(C,A),mostOverlapsLess(A,B).
supports(A,B):- mobile(C),lessOverlapsMostI(C,A),centerDuringI(A,B).
supports(A,B):- mobile(C),mostFinishes(C,A),centerDuringI(A,B).
supports(A,B):- mobile(C),lessOverlapsLess(C,B),rightDuringI(C,A).
supports(A,B):- mobile(C),mostOverlapsMostI(C,A),lessStartsI(A,B).
supports(A,B):- mobile(C),mostFinishes(C,A),mostOverlapsLess(A,B).
supports(A,B):- mobile(C),mostFinishes(C,A),lessStartsI(A,B).
supports(A,B):- mobile(C),meetsI(C,A),mostFinishesI(A,B).
supports(A,B):- mobile(C),lessOverlapsLess(C,A),mostOverlapsMostI(A,B).
supports(A,B):- mobile(C),centerDuring(C,A),lessOverlapsLessI(A,B).
supports(A,B):- mobile(C),rightDuring(C,B),meets(C,A).
supports(A,B):- mobile(C),mostOverlapsMost(C,A),lessOverlapsMostI(A,B).
supports(A,B):- mobile(C),lessOverlapsLessI(C,A),mostOverlapsMost(A,B).
