supports(A,B):- fixed(A),startsY(A,B).
supports(A,B):- object(C),lessOverlapsMost(C,A),meetsI(A,B).
supports(A,B):- object(C),mostOverlapsLess(C,A),leftDuringI(A,B).
supports(A,B):- object(C),duringYI(C,A),centerDuringI(A,B).
supports(A,B):- object(C),overlapsYI(C,A),centerDuringI(C,B).
supports(A,B):- object(C),lessOverlapsMostI(C,A),mostOverlapsLessI(A,B).
supports(A,B):- object(C),mostOverlapsMost(C,A),mostFinishes(A,B).
supports(A,B):- object(C),lessFinishesI(C,B),mostOverlapsLess(B,A).
supports(A,B):- object(C),leftDuringI(C,A),mostOverlapsLess(A,B).
supports(A,B):- object(C),lessOverlapsLessI(C,A),rightDuringI(A,B).
supports(A,B):- object(C),leftDuring(C,B),lessOverlapsMost(B,A).
supports(A,B):- object(C),startsYI(C,A),lessOverlapsLess(A,B).
supports(A,B):- object(C),rightDuringI(C,A),rightDuringI(A,B).
supports(A,B):- object(C),startsYI(C,B),mostOverlapsMostI(B,A).
supports(A,B):- object(C),overlapsYI(C,A),lessOverlapsMostI(A,B).
supports(A,B):- object(C),mostOverlapsLessI(C,B),lessOverlapsMostI(B,A).
supports(A,B):- object(C),centerDuring(C,A),lessOverlapsLessI(A,B).
supports(A,B):- object(C),leftDuring(C,B),mostOverlapsMostI(B,A).
supports(A,B):- object(C),before(C,A),mostFinishesI(A,B).
supports(A,B):- object(C),overlapsYI(C,A),centerDuring(A,B).
supports(A,B):- object(C),lessStarts(C,B),lessStarts(C,A).
supports(A,B):- object(C),lessOverlapsMost(C,A),mostOverlapsLess(A,B).
supports(A,B):- object(C),leftDuringI(C,A),lessStarts(A,B).
supports(A,B):- object(C),startsYI(C,A),lessOverlapsMost(A,B).
supports(A,B):- object(C),centerDuringI(C,B),lessFinishesI(C,A).
supports(A,B):- object(C),lessStartsI(C,A),mostOverlapsLess(A,B).
supports(A,B):- object(C),after(C,A),lessStartsI(A,B).
supports(A,B):- object(C),centerDuringI(C,B),mostOverlapsMost(C,A).
supports(A,B):- object(C),on(C,A),mostFinishesI(A,B).
supports(A,B):- object(C),mostFinishesI(C,A),rightDuringI(A,B).
supports(A,B):- object(C),lessOverlapsMost(C,A),lessStarts(A,B).
supports(A,B):- object(C),mostFinishes(C,A),lessOverlapsLessI(A,B).
supports(A,B):- object(C),before(C,A),mostOverlapsMostI(A,B).
supports(A,B):- object(C),centerDuringI(C,B),lessOverlapsLessI(B,A).
