supports(A,B):- mobile(A),lessOverlapsMostI(A,B).
supports(A,B):- mobile(C),mostOverlapsMost(C,B),on(B,A).
supports(A,B):- object(A),mostOverlapsMostI(A,C),mostFinishesI(C,B).
supports(A,B):- fixed(C),lessFinishes(C,B),on(B,A).
supports(A,B):- mobile(A),onI(A,B),horizontalContact(B,A).
supports(A,B):- object(A),rightDuringI(A,B),surfaceContact(A,B).
supports(A,B):- mobile(A),onI(A,B),mostFinishesI(B,A).
supports(A,B):- mobile(C),centerDuring(C,A),lessFinishesI(C,B).
supports(A,B):- mobile(A),mostOverlapsLess(A,C),lessStartsI(C,B).
supports(A,B):- object(A),lessStartsI(A,B),surfaceContact(A,B).
supports(A,B):- mobile(A),lessOverlapsMost(A,C),meetsI(C,B).
supports(A,B):- mobile(A),rightDuringI(A,C),mostOverlapsMostI(C,B).
supports(A,B):- object(A),lessOverlapsLessI(A,B),surfaceContact(A,B).
supports(A,B):- object(A),centerDuringI(A,B),surfaceContact(A,B).
supports(A,B):- mobile(A),onI(A,B),equal(B,A).
supports(A,B):- fixed(C),lessOverlapsMost(C,A),below(C,B).
supports(A,B):- mobile(A),leftDuringI(A,B),surfaceContact(A,B).
supports(A,B):- mobile(A),mostFinishesI(A,C),lessOverlapsLess(C,B).
supports(A,B):- mobile(A),rightDuringI(A,C),mostOverlapsLessI(C,B).
supports(A,B):- mobile(C),lessFinishes(C,A),lessOverlapsLess(A,B).
supports(A,B):- mobile(C),mostOverlapsMostI(C,A),mostOverlapsLessI(C,B).
supports(A,B):- mobile(A),onI(A,B),lessStartsI(B,A).
supports(A,B):- object(A),mostOverlapsMostI(A,C),lessFinishesI(C,B).
supports(A,B):- object(A),lessFinishesI(A,B),surfaceContact(A,B).
supports(A,B):- object(A),lessFinishes(A,B),surfaceContact(A,B).
supports(A,B):- mobile(B),fixed(A),surfaceContact(A,B).
supports(A,B):- mobile(A),mostOverlapsLess(A,B),onI(A,B).
supports(A,B):- mobile(A),onI(A,B),mostFinishesI(A,B).
supports(A,B):- mobile(C),meets(C,B),mostOverlapsMost(B,A).
