supports(A,B):- mobile(B),leftDuringI(B,A).
supports(A,B):- object(B),lessStarts(B,A).
supports(A,B):- object(B),lessFinishesI(B,A).
supports(A,B):- fixed(C),startsY(C,B),lessOverlapsMost(B,A).
supports(A,B):- fixed(C),centerDuringI(C,A),finishesYI(A,B).
supports(A,B):- fixed(C),centerDuringI(C,A),mostOverlapsLess(A,B).
supports(A,B):- fixed(C),startsY(C,A),lessOverlapsLess(A,B).
supports(A,B):- mobile(C),leftDuring(C,A),leftDuring(C,B).
supports(A,B):- mobile(C),finishesYI(C,A),mostOverlapsLessI(A,B).
supports(A,B):- fixed(C),rightDuringI(C,A),mostFinishes(A,B).
supports(A,B):- fixed(C),leftDuringI(C,B),rightDuringI(B,A).
supports(A,B):- fixed(C),centerDuringI(C,A),overlapsY(A,B).
supports(A,B):- mobile(C),mostOverlapsLessI(C,A),mostOverlapsMostI(A,B).
supports(A,B):- mobile(C),overlapsYI(C,A),centerDuring(A,B).
supports(A,B):- fixed(C),leftDuringI(C,A),lessOverlapsLess(A,B).
supports(A,B):- fixed(C),after(C,A),rightDuringI(A,B).
supports(A,B):- mobile(C),leftDuring(C,B),mostOverlapsMost(B,A).
supports(A,B):- mobile(C),mostOverlapsLessI(C,A),lessStarts(A,B).
supports(A,B):- fixed(C),after(C,A),mostOverlapsMost(A,B).
supports(A,B):- fixed(C),startsY(C,A),centerDuringI(A,B).
supports(A,B):- fixed(C),onI(C,A),lessStarts(A,B).
supports(A,B):- mobile(C),overlapsYI(C,A),rightDuringI(A,B).
supports(A,B):- fixed(C),below(C,B),lessOverlapsMostI(B,A).
supports(A,B):- fixed(C),startsY(C,A),mostOverlapsLessI(A,B).
supports(A,B):- fixed(C),leftDuringI(C,A),lessStarts(A,B).
supports(A,B):- mobile(C),rightDuring(C,A),leftDuring(C,B).
supports(A,B):- fixed(C),rightDuringI(C,A),lessFinishesI(A,B).
supports(A,B):- mobile(C),mostOverlapsLessI(C,A),lessOverlapsLess(A,B).
supports(A,B):- mobile(C),mostOverlapsLessI(C,B),lessOverlapsLessI(B,A).
supports(A,B):- fixed(C),leftDuringI(C,A),mostFinishes(A,B).
supports(A,B):- fixed(C),startsY(C,A),rightDuringI(A,B).
supports(A,B):- mobile(C),startsY(C,A),lessOverlapsMostI(A,B).
supports(A,B):- mobile(C),overlapsYI(C,A),mostOverlapsMostI(A,B).
supports(A,B):- fixed(C),centerDuringI(C,A),centerDuringI(A,B).
supports(A,B):- fixed(C),onI(C,A),lessOverlapsLessI(A,B).
supports(A,B):- mobile(C),mostOverlapsLessI(C,A),centerDuringI(A,B).
supports(A,B):- fixed(C),startsY(C,B),on(C,A).
supports(A,B):- fixed(C),rightDuringI(C,B),lessOverlapsLess(B,A).
supports(A,B):- fixed(C),centerDuringI(C,B),mostOverlapsMostI(B,A).
supports(A,B):- fixed(C),centerDuringI(C,A),mostOverlapsMost(A,B).
supports(A,B):- mobile(C),mostOverlapsLessI(C,A),mostOverlapsLessI(C,B).
supports(A,B):- mobile(C),lessFinishes(C,A),mostOverlapsLessI(C,B).
supports(A,B):- fixed(C),leftDuringI(C,A),lessOverlapsMostI(A,B).
supports(A,B):- fixed(C),centerDuringI(C,B),startsYI(B,A).
supports(A,B):- mobile(C),startsY(C,A),centerDuring(A,B).
supports(A,B):- fixed(C),below(C,B),mostFinishes(B,A).
supports(A,B):- fixed(C),onI(C,A),mostOverlapsLess(A,B).
supports(A,B):- fixed(C),rightDuringI(C,A),mostOverlapsMostI(A,B).
supports(A,B):- mobile(C),lessStarts(C,B),overlapsYI(C,A).
supports(A,B):- fixed(C),onI(C,A),centerDuring(A,B).
supports(A,B):- mobile(C),leftDuringI(C,A),meets(A,B).
supports(A,B):- fixed(C),leftDuringI(C,B),mostOverlapsLessI(B,A).
supports(A,B):- mobile(C),lessStarts(C,A),leftDuringI(A,B).
supports(A,B):- fixed(C),leftDuringI(C,A),lessFinishesI(A,B).
supports(A,B):- mobile(C),lessOverlapsLess(C,A),leftDuringI(A,B).
supports(A,B):- fixed(C),centerDuringI(C,A),mostFinishes(A,B).
supports(A,B):- mobile(C),lessFinishes(C,A),leftDuringI(A,B).
supports(A,B):- mobile(C),finishesYI(C,A),leftDuringI(A,B).
