supports(A,B):- lessFinishes(A,B).
supports(A,B):- leftDuring(A,B).
supports(A,B):- centerDuring(A,B).
supports(A,B):- lessStarts(A,B).
supports(A,B):- mostFinishes(B,A).
supports(A,B):- lessStarts(B,A).
supports(A,B):- lessOverlapsLess(A,C),mostOverlapsMost(C,B).
supports(A,B):- surfaceContact(A,B),finishesY(A,B).
supports(A,B):- overlapsY(B,C),mostOverlapsLess(C,A).
supports(A,B):- on(B,A),mostOverlapsMost(B,A).
supports(A,B):- overlapsY(A,B),surfaceContact(A,B).
supports(A,B):- on(B,A),meets(B,A).
supports(A,B):- mostOverlapsLess(B,A),on(B,A).
supports(A,B):- meets(B,A),startsY(B,A).
supports(A,B):- surfaceContact(A,B),on(B,A).
supports(A,B):- centerDuring(B,A),on(B,A).
supports(A,B):- overlapsY(B,C),meets(A,C).
supports(A,B):- mostOverlapsLess(A,B),startsY(A,B).
supports(A,B):- on(B,A),lessOverlapsLess(A,B).
supports(A,B):- lessOverlapsMost(A,B),on(B,A).
supports(A,B):- on(B,A),startsY(A,B).
supports(A,B):- startsY(A,B),surfaceContact(A,B).
supports(A,B):- equal(B,A),on(B,A).
supports(A,B):- mostOverlapsMost(B,C),mostFinishes(A,C).
supports(A,B):- mostOverlapsLess(B,A),startsY(A,B).
supports(A,B):- lessOverlapsLess(A,B),startsY(A,B).
supports(A,B):- meets(A,C),lessOverlapsLess(B,C).
supports(A,B):- lessOverlapsLess(A,B),finishesY(B,A).
supports(A,B):- mostOverlapsMost(A,C),centerDuring(C,B).
supports(A,B):- on(B,C),finishesY(C,D),horizontalContact(A,D).
supports(A,B):- lessOverlapsMost(B,C),before(A,D),lessOverlapsMost(C,D).
supports(A,B):- on(B,C),verticalContact(C,A),lessOverlapsLess(B,A).