supports(A,B):- mobile(A),lessOverlapsMostI(A,B).
supports(A,B):- mobile(A),mostOverlapsLess(A,C),lessStartsI(C,B).
supports(A,B):- mobile(A),lessOverlapsLessI(A,B),verticalContact(B,A).
supports(A,B):- mobile(B),fixed(A),verticalContact(B,A).
supports(A,B):- fixed(C),mostOverlapsMostI(C,B),on(B,A).
supports(A,B):- object(B),lessStartsI(B,A),onI(A,B).
supports(A,B):- fixed(C),lessOverlapsMost(C,A),onI(A,B).
supports(A,B):- mobile(A),lessStartsI(A,B),verticalContact(B,A).
supports(A,B):- object(A),rightDuringI(A,C),mostOverlapsLessI(C,B).
supports(A,B):- object(A),mostOverlapsMostI(A,C),mostFinishesI(C,B).
supports(A,B):- object(B),on(B,A),equal(A,B).
supports(A,B):- mobile(A),lessFinishes(A,B),verticalContact(B,A).
supports(A,B):- object(B),lessFinishes(B,C),centerDuring(C,A).
supports(A,B):- object(A),mostOverlapsMostI(A,C),lessFinishesI(C,B).
supports(A,B):- mobile(A),rightDuringI(A,B),verticalContact(B,A).
supports(A,B):- mobile(A),lessOverlapsMost(A,C),meetsI(C,B).
supports(A,B):- object(B),mostFinishesI(B,A),onI(A,B).
supports(A,B):- object(B),lessOverlapsLessI(B,C),mostFinishes(C,A).
supports(A,B):- object(B),on(B,A),horizontalContact(A,B).
supports(A,B):- mobile(C),lessStarts(C,A),lessOverlapsLess(A,B).
supports(A,B):- fixed(C),lessFinishes(C,B),on(B,A).
supports(A,B):- mobile(A),centerDuringI(A,B),verticalContact(B,A).
supports(A,B):- object(B),mostFinishes(B,A),onI(A,B).
supports(A,B):- mobile(C),mostOverlapsMost(C,B),on(B,A).
supports(A,B):- mobile(C),meets(C,B),mostOverlapsMost(B,A).
supports(A,B):- mobile(A),mostOverlapsLess(A,B),onI(A,B).
supports(A,B):- mobile(B),lessFinishes(B,A),verticalContact(B,A).
supports(A,B):- mobile(C),mostOverlapsMostI(C,A),mostOverlapsLessI(C,B).
supports(A,B):- mobile(B),on(B,A),leftDuringI(A,B).
