supports(A,B):- mobile(A),lessOverlapsLess(A,B).
supports(A,B):- mobile(B),lessOverlapsLessI(B,A).
supports(A,B):- mobile(B),rightDuring(B,A).
supports(A,B):- fixed(A),meets(A,B).
supports(A,B):- mobile(B),lessStartsI(B,A).
supports(A,B):- mobile(B),lessFinishes(B,A).
supports(A,B):- mobile(B),mostFinishesI(B,A).
supports(A,B):- mobile(B),on(B,A),centerDuring(B,A).
supports(A,B):- mobile(C),below(C,A),leftDuringI(A,B).
supports(A,B):- mobile(B),centerDuringI(B,A),pointSurfaceContact(B,A).
supports(A,B):- mobile(B),lessOverlapsMost(B,C),finishesY(C,A).
supports(A,B):- mobile(B),overlapsYI(B,A),lessOverlapsLess(B,A).
supports(A,B):- mobile(B),on(B,A),pointSurfaceContact(B,A).
supports(A,B):- mobile(C),mostFinishes(C,A),mostOverlapsMost(A,B).
supports(A,B):- mobile(C),mostOverlapsMost(C,A),mostOverlapsLessI(A,B).
supports(A,B):- mobile(C),mostOverlapsMostI(C,A),leftDuring(A,B).
supports(A,B):- mobile(B),startsYI(B,A),verticalContact(B,A).
supports(A,B):- mobile(B),meetsI(B,C),centerDuring(C,A).
supports(A,B):- mobile(B),mostOverlapsMost(B,A),overlapsYI(B,A).
supports(A,B):- mobile(B),finishesY(B,A),surfaceContact(B,A).
supports(A,B):- mobile(B),mostOverlapsLess(B,C),mostOverlapsLessI(C,A).
supports(A,B):- mobile(C),lessStarts(C,A),finishesYI(A,B).
supports(A,B):- mobile(B),mostOverlapsLessI(B,C),centerDuring(C,A).
supports(A,B):- mobile(C),startsYI(C,A),lessOverlapsLessI(A,B).
supports(A,B):- mobile(B),startsYI(B,A),mostOverlapsLessI(B,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,C),finishesY(C,A).
supports(A,B):- mobile(B),meets(B,C),mostOverlapsLessI(C,A).
supports(A,B):- mobile(C),before(C,A),lessStartsI(A,B).
supports(A,B):- mobile(B),mostOverlapsMost(B,A),on(B,A).
supports(A,B):- mobile(C),mostOverlapsMostI(C,A),mostOverlapsLessI(A,B).
supports(A,B):- mobile(C),leftDuring(C,A),mostOverlapsMost(A,B).
supports(A,B):- mobile(C),lessOverlapsLess(C,A),meets(A,B).
supports(A,B):- mobile(C),on(C,A),lessOverlapsMostI(A,B).
supports(A,B):- mobile(C),meetsI(C,A),rightDuringI(A,B).
supports(A,B):- mobile(B),on(B,A),mostFinishes(B,A).
supports(A,B):- mobile(C),below(C,A),lessOverlapsMost(A,B).
supports(A,B):- fixed(A),onI(A,C),startsY(C,B).
supports(A,B):- mobile(C),mostOverlapsLess(C,A),leftDuringI(A,B).
supports(A,B):- mobile(B),centerDuringI(B,A),on(B,A).
supports(A,B):- mobile(B),mostOverlapsMostI(B,A),overlapsYI(B,A).
supports(A,B):- mobile(A),mobile(B),equal(A,B).
supports(A,B):- mobile(C),lessStarts(C,A),mostOverlapsMost(A,B).
supports(A,B):- mobile(C),finishesY(C,A),mostOverlapsMost(A,B).
supports(A,B):- mobile(B),mostFinishes(B,A),overlapsYI(B,A).
supports(A,B):- mobile(B),on(B,A),horizontalContact(A,B).
supports(A,B):- mobile(B),mostOverlapsLess(B,C),centerDuring(C,A).
supports(A,B):- mobile(B),mostOverlapsLessI(B,A),overlapsYI(B,A).
supports(A,B):- fixed(A),meetsI(A,C),mostOverlapsLess(C,B).
supports(A,B):- mobile(C),mostOverlapsMost(C,A),finishesYI(A,B).
supports(A,B):- mobile(B),centerDuring(B,A),overlapsYI(B,A).
