supports(A,B):- fixed(A),mostOverlapsLessI(A,B).
supports(A,B):- mobile(A),lessOverlapsMostI(A,B).
supports(A,B):- fixed(A),overlapsY(A,B).
supports(A,B):- mobile(A),lessFinishes(A,B).
supports(A,B):- object(A),lessStartsI(A,B).
supports(A,B):- mobile(B),rightDuringI(B,A).
supports(A,B):- object(A),meetsI(A,C),lessOverlapsLess(C,B).
supports(A,B):- object(A),onI(A,B),lessOverlapsLess(B,A).
supports(A,B):- object(A),overlapsY(A,B),lessOverlapsLess(B,A).
supports(A,B):- object(A),overlapsY(A,B),pointSurfaceContact(B,A).
supports(A,B):- object(A),startsY(A,B),lessOverlapsLessI(B,A).
supports(A,B):- object(A),finishesYI(A,B),verticalContact(A,B).
supports(A,B):- object(A),overlapsY(A,C),lessStarts(C,B).
supports(A,B):- object(A),onI(A,B),pointContact(B,A).
supports(A,B):- object(A),onI(A,B),surfaceContact(B,A).
supports(A,B):- object(A),startsY(A,B),mostOverlapsLess(A,B).
supports(A,B):- object(A),centerDuringI(A,C),lessFinishesI(C,B).
supports(A,B):- object(A),onI(A,B),equal(A,B).
supports(A,B):- object(A),onI(A,B),centerDuring(B,A).
supports(A,B):- object(A),overlapsY(A,B),lessOverlapsLessI(A,B).
supports(A,B):- object(A),startsY(A,B),lessOverlapsMostI(B,A).
supports(A,B):- object(A),mostOverlapsMostI(A,C),lessOverlapsLess(C,B).
supports(A,B):- object(A),onI(A,B),startsY(A,B).
supports(A,B):- object(A),lessFinishesI(A,C),mostOverlapsLess(C,B).
supports(A,B):- object(A),overlapsY(A,B),lessOverlapsLessI(B,A).
supports(A,B):- object(A),startsY(A,B),lessOverlapsLess(B,A).
supports(A,B):- object(A),startsY(A,B),lessStartsI(B,A).
supports(A,B):- object(A),overlapsY(A,B),mostOverlapsLessI(B,A).
supports(A,B):- object(A),onI(A,B),mostFinishes(B,A).
supports(A,B):- object(A),onI(A,B),mostOverlapsLess(B,A).
supports(A,B):- object(A),onI(A,B),lessStartsI(B,A).
supports(A,B):- object(A),lessStartsI(A,C),centerDuring(C,B).
supports(A,B):- object(A),onI(A,B),mostFinishesI(B,A).
supports(A,B):- object(A),meets(A,C),lessOverlapsLessI(C,B).
supports(A,B):- object(A),lessOverlapsLess(A,B),finishesY(B,A).
supports(A,B):- object(A),lessStarts(A,C),lessOverlapsLessI(C,B).
supports(A,B):- object(A),on(A,C),lessFinishes(C,B).
supports(A,B):- object(A),lessOverlapsLess(A,B),equalY(B,A).
supports(A,B):- object(A),overlapsY(A,B),mostOverlapsMostI(B,A).
supports(A,B):- object(A),meetsI(A,C),lessOverlapsMost(C,B).
supports(A,B):- object(A),mostOverlapsMostI(A,C),finishesYI(C,B).
supports(A,B):- object(A),mostOverlapsMost(A,C),mostOverlapsLess(C,B).
supports(A,B):- object(A),overlapsY(A,B),mostFinishes(B,A).
supports(A,B):- object(A),lessFinishesI(A,C),overlapsYI(C,B).
supports(A,B):- object(A),lessOverlapsMost(A,C),overlapsYI(C,B).
supports(A,B):- object(A),overlapsY(A,B),verticalContact(B,A).
supports(A,B):- object(A),onI(A,B),leftDuringI(A,B).
supports(A,B):- object(A),mostOverlapsMost(A,B),overlapsY(A,B).
supports(A,B):- object(A),onI(A,B),lessFinishes(B,A).
supports(A,B):- object(A),lessOverlapsLess(A,B),onI(A,B).
supports(A,B):- object(A),lessStarts(A,C),centerDuring(C,B).
supports(A,B):- object(A),onI(A,B),rightDuringI(A,B).
supports(A,B):- object(A),finishesYI(A,B),lessOverlapsLess(B,A).
supports(A,B):- object(A),mostOverlapsMostI(A,B),onI(A,B).
supports(A,B):- object(A),startsY(A,B),centerDuringI(B,A).
supports(A,B):- object(A),overlapsY(A,B),equal(A,B).
supports(A,B):- object(A),lessStarts(A,B),duringYI(B,A).
supports(A,B):- object(A),mostOverlapsMost(A,B),onI(A,B).
supports(A,B):- object(A),mostOverlapsMost(A,C),overlapsY(C,B).
supports(A,B):- object(A),onI(A,B),lessOverlapsMostI(B,A).
