supports(A,B):- mobile(B),centerDuringI(B,A).
supports(A,B):- object(A),lessOverlapsLessI(A,B).
supports(A,B):- mobile(A),centerDuringI(A,B).
supports(A,B):- fixed(C),centerDuringI(C,A),mostFinishesI(A,B).
supports(A,B):- mobile(C),mostOverlapsLess(C,B),mostFinishesI(B,A).
supports(A,B):- mobile(C),after(C,A),mostOverlapsMostI(A,B).
supports(A,B):- mobile(B),on(B,A),lessOverlapsLess(A,B).
supports(A,B):- mobile(B),overlapsYI(B,A),lessOverlapsLess(A,B).
supports(A,B):- mobile(B),lessOverlapsMost(B,A),surfaceContact(A,B).
supports(A,B):- mobile(B),startsYI(B,A),lessOverlapsMostI(A,B).
supports(A,B):- fixed(C),mobile(B),lessOverlapsMost(C,A).
supports(A,B):- mobile(C),lessOverlapsLessI(C,A),lessStartsI(A,B).
supports(A,B):- fixed(C),leftDuringI(C,A),mostOverlapsMost(A,B).
supports(A,B):- mobile(B),on(B,A),lessStarts(A,B).
supports(A,B):- mobile(B),on(B,A),rightDuringI(A,B).
supports(A,B):- fixed(C),mobile(B),meets(C,A).
supports(A,B):- fixed(A),mobile(B),on(B,A).
supports(A,B):- mobile(C),startsYI(C,A),lessOverlapsMost(A,B).
supports(A,B):- mobile(C),startsY(C,B),mostOverlapsLessI(B,A).
supports(A,B):- mobile(B),overlapsYI(B,A),mostOverlapsMost(A,B).
supports(A,B):- mobile(B),overlapsYI(B,A),surfaceContact(A,B).
supports(A,B):- mobile(B),on(B,A),lessFinishesI(A,B).
supports(A,B):- mobile(C),mostOverlapsLess(C,A),mostOverlapsMostI(A,B).
supports(A,B):- fixed(C),mostOverlapsLess(C,B),on(B,A).
supports(A,B):- fixed(C),below(C,A),rightDuring(C,B).
supports(A,B):- fixed(C),lessFinishes(C,B),lessFinishes(C,A).
supports(A,B):- mobile(B),on(B,A),mostFinishesI(A,B).
supports(A,B):- mobile(B),on(B,A),leftDuringI(A,B).
supports(A,B):- mobile(B),on(B,A),mostOverlapsLessI(A,B).
supports(A,B):- mobile(C),rightDuring(C,A),meets(A,B).
supports(A,B):- mobile(C),centerDuring(C,A),meetsI(A,B).
supports(A,B):- mobile(C),startsYI(C,A),mostOverlapsMost(A,B).
supports(A,B):- fixed(C),centerDuringI(C,A),startsY(A,B).
supports(A,B):- mobile(B),startsYI(B,A),lessOverlapsLess(A,B).
supports(A,B):- mobile(C),startsYI(C,A),mostFinishes(A,B).
supports(A,B):- mobile(B),on(B,A),lessStartsI(A,B).
