supports(A,B):- fixed(A),onI(A,B).
supports(A,B):- mobile(B),lessOverlapsLessI(B,A),on(B,A).
supports(A,B):- mobile(B),lessOverlapsMost(B,C),mostFinishes(C,A).
supports(A,B):- mobile(B),on(B,A),lessStarts(B,A).
supports(A,B):- mobile(B),overlapsYI(B,A),mostOverlapsMostI(B,A).
supports(A,B):- mobile(B),lessFinishes(B,C),mostOverlapsLess(C,A).
supports(A,B):- mobile(B),on(B,A),lessOverlapsMost(B,A).
supports(A,B):- mobile(B),on(B,A),lessFinishes(B,A).
supports(A,B):- mobile(B),on(B,A),mostOverlapsMost(A,B).
supports(A,B):- mobile(B),on(B,A),lessOverlapsMost(A,B).
supports(A,B):- mobile(B),on(B,A),lessStartsI(B,A).
supports(A,B):- mobile(B),startsYI(B,C),startsYI(C,A).
supports(A,B):- mobile(B),on(B,A),rightDuringI(B,A).
supports(A,B):- mobile(B),lessOverlapsMost(B,C),lessFinishes(C,A).
supports(A,B):- mobile(B),mostFinishes(B,C),mostOverlapsMost(C,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,A),startsYI(B,A).
supports(A,B):- mobile(B),on(B,A),lessOverlapsLessI(A,B).
supports(A,B):- mobile(B),on(B,A),mostOverlapsLess(B,A).
supports(A,B):- mobile(B),lessOverlapsMostI(B,C),mostOverlapsLess(C,A).
supports(A,B):- mobile(B),lessFinishesI(B,A),on(B,A).
supports(A,B):- mobile(B),centerDuring(B,C),overlapsYI(C,A).
supports(A,B):- mobile(B),mostOverlapsMost(B,A),on(B,A).
supports(A,B):- mobile(B),mostFinishesI(B,C),meets(C,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,C),mostOverlapsMost(C,A).
supports(A,B):- mobile(B),rightDuring(B,C),mostFinishesI(C,A).
supports(A,B):- mobile(B),mostOverlapsMostI(B,C),overlapsY(C,A).
supports(A,B):- mobile(B),finishesYI(B,C),on(C,A).
supports(A,B):- mobile(B),mostOverlapsLess(B,C),lessOverlapsLessI(C,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,C),lessOverlapsLess(C,A).
supports(A,B):- mobile(B),lessOverlapsMost(B,C),rightDuringI(C,A).
supports(A,B):- mobile(B),centerDuring(B,A),verticalContact(A,B).
supports(A,B):- mobile(B),on(B,A),rightDuringI(A,B).
supports(A,B):- mobile(B),on(B,A),leftDuringI(A,B).
supports(A,B):- mobile(B),duringY(B,C),meets(C,A).
supports(A,B):- mobile(B),overlapsYI(B,A),pointSurfaceContact(A,B).
supports(A,B):- mobile(B),on(B,A),equal(A,B).
supports(A,B):- mobile(B),mostOverlapsLess(B,C),mostFinishes(C,A).
supports(A,B):- mobile(B),on(B,A),mostOverlapsLess(A,B).
supports(A,B):- mobile(B),on(B,A),mostOverlapsLessI(A,B).
supports(A,B):- mobile(B),on(B,A),lessOverlapsMostI(B,A).
supports(A,B):- mobile(B),finishesY(B,C),overlapsYI(C,A).
