supports(A,B):- mobile(B),rightDuringI(B,A).
supports(A,B):- mobile(A),lessStartsI(A,B).
supports(A,B):- mobile(A),lessFinishes(A,B).
supports(A,B):- mobile(A),lessOverlapsMostI(A,B).
supports(A,B):- mobile(B),on(B,A),mostFinishesI(B,A).
supports(A,B):- mobile(B),overlapsYI(B,C),lessFinishes(C,A).
supports(A,B):- mobile(B),mostOverlapsMostI(B,C),rightDuringI(C,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,C),meets(C,A).
supports(A,B):- mobile(B),mostOverlapsLessI(B,C),mostOverlapsLess(C,A).
supports(A,B):- mobile(B),on(B,A),centerDuring(B,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,A),equalY(B,A).
supports(A,B):- mobile(B),on(B,C),lessFinishes(C,A).
supports(A,B):- mobile(B),lessStartsI(B,A),on(B,A).
supports(A,B):- mobile(B),overlapsYI(B,C),mostOverlapsMostI(C,A).
supports(A,B):- mobile(B),lessOverlapsMostI(B,A),verticalContact(B,A).
supports(A,B):- fixed(C),duringY(C,A),mobile(B).
supports(A,B):- mobile(B),mostOverlapsLessI(B,C),centerDuring(C,A).
supports(A,B):- mobile(B),lessFinishes(B,A),on(B,A).
supports(A,B):- mobile(B),on(B,A),pointContact(B,A).
supports(A,B):- mobile(B),mostFinishes(B,A),on(B,A).
supports(A,B):- mobile(B),on(B,A),mostOverlapsLessI(B,A).
supports(A,B):- mobile(B),lessOverlapsLess(B,C),meetsI(C,A).
supports(A,B):- mobile(B),mostOverlapsMostI(B,C),lessOverlapsLessI(C,A).
supports(A,B):- mobile(B),lessOverlapsLess(B,A),startsYI(B,A).
supports(A,B):- mobile(B),mostFinishes(B,C),finishesYI(C,A).
supports(A,B):- mobile(B),leftDuringI(B,C),meets(C,A).
supports(A,B):- mobile(B),mostOverlapsMostI(B,C),lessOverlapsMost(C,A).
supports(A,B):- mobile(B),mostOverlapsLess(B,C),lessOverlapsLessI(C,A).
supports(A,B):- mobile(B),centerDuringI(B,A),on(B,A).
supports(A,B):- mobile(B),mostOverlapsMost(B,A),on(B,A).
supports(A,B):- fixed(A),mobile(B),on(B,A).
supports(A,B):- mobile(B),overlapsYI(B,A),mostOverlapsMostI(B,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,A),startsYI(B,A).
supports(A,B):- mobile(B),on(B,A),mostOverlapsLess(B,A).
supports(A,B):- mobile(B),mostOverlapsMost(B,C),mostOverlapsLessI(C,A).
supports(A,B):- mobile(B),startsYI(B,A),mostOverlapsLessI(B,A).
supports(A,B):- mobile(B),lessOverlapsMost(B,C),mostOverlapsLess(C,A).
supports(A,B):- mobile(B),rightDuring(B,C),mostOverlapsMost(C,A).
supports(A,B):- mobile(B),mostOverlapsMostI(B,A),on(B,A).
supports(A,B):- mobile(B),overlapsY(B,C),lessOverlapsMostI(C,A).
supports(A,B):- mobile(B),mostOverlapsLessI(B,C),lessFinishes(C,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,C),lessOverlapsMost(C,A).
supports(A,B):- mobile(B),on(B,A),lessOverlapsLess(B,A).
supports(A,B):- mobile(B),leftDuringI(B,C),startsY(C,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,A),finishesY(B,A).
supports(A,B):- mobile(B),overlapsYI(B,A),pointContact(B,A).
supports(A,B):- mobile(B),lessOverlapsMostI(B,C),meets(C,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,C),lessOverlapsLess(C,A).
supports(A,B):- mobile(B),mostFinishes(B,C),lessOverlapsLessI(C,A).
supports(A,B):- mobile(B),on(B,A),lessOverlapsMostI(B,A).
supports(A,B):- mobile(B),meetsI(B,C),lessStarts(C,A).
supports(A,B):- mobile(B),mostOverlapsMostI(B,C),mostOverlapsMost(C,A).
supports(A,B):- mobile(B),lessOverlapsLess(B,C),centerDuringI(C,A).
supports(A,B):- mobile(B),lessOverlapsLess(B,A),finishesY(B,A).
supports(A,B):- mobile(B),lessOverlapsMostI(B,C),startsYI(C,A).
supports(A,B):- mobile(B),lessOverlapsMostI(B,C),mostOverlapsMost(C,A).
supports(A,B):- mobile(B),mostOverlapsLessI(B,C),lessStartsI(C,A).
supports(A,B):- mobile(B),on(B,A),lessOverlapsLessI(B,A).
supports(A,B):- mobile(B),on(B,A),rightDuringI(A,B).
supports(A,B):- mobile(B),centerDuring(B,C),mostFinishesI(C,A).
supports(A,B):- mobile(B),overlapsYI(B,A),verticalContact(B,A).
