supports(A,B):- object(A),lessStarts(A,B).
supports(A,B):- mobile(A),leftDuringI(A,B).
supports(A,B):- mobile(A),centerDuringI(A,B).
supports(A,B):- fixed(A),startsY(A,B).
supports(A,B):- mobile(B),lessStarts(B,A).
supports(A,B):- mobile(A),mostOverlapsMostI(A,C),mostFinishes(C,B).
supports(A,B):- mobile(A),startsY(A,B),verticalContact(A,B).
supports(A,B):- mobile(A),onI(A,B),pointContact(A,B).
supports(A,B):- mobile(A),meetsI(A,C),centerDuring(C,B).
supports(A,B):- mobile(A),onI(A,B),mostOverlapsMostI(B,A).
supports(A,B):- mobile(A),lessOverlapsMostI(A,C),finishesY(C,B).
supports(A,B):- mobile(A),mostOverlapsLessI(A,C),meets(C,B).
supports(A,B):- mobile(A),onI(A,B),mostOverlapsMost(B,A).
supports(A,B):- mobile(A),overlapsY(A,C),mostOverlapsLess(C,B).
supports(A,B):- mobile(A),rightDuringI(A,C),below(C,B).
supports(A,B):- mobile(A),overlapsY(A,C),duringY(C,B).
supports(A,B):- mobile(A),lessFinishes(A,C),rightDuringI(C,B).
supports(A,B):- mobile(A),mostOverlapsLessI(A,B),on(B,A).
supports(A,B):- mobile(A),mostFinishes(A,C),rightDuringI(C,B).
supports(A,B):- mobile(A),meets(A,B),overlapsYI(B,A).
supports(A,B):- mobile(A),duringY(A,B),mostOverlapsLessI(B,A).
supports(A,B):- mobile(A),leftDuringI(A,C),meetsI(C,B).
supports(A,B):- mobile(A),lessStarts(A,C),lessOverlapsMostI(C,B).
supports(A,B):- mobile(A),equalY(A,B),verticalContact(A,B).
supports(A,B):- mobile(A),overlapsY(A,B),verticalContact(A,B).
supports(A,B):- mobile(A),mostOverlapsMost(A,C),mostOverlapsMost(C,B).
supports(A,B):- mobile(A),onI(A,B),mostFinishes(B,A).
supports(A,B):- mobile(A),lessOverlapsMostI(A,B),on(B,A).
supports(A,B):- mobile(A),lessFinishesI(A,C),finishesY(C,B).
supports(A,B):- mobile(A),duringYI(A,B),meets(B,A).
supports(A,B):- mobile(A),mostOverlapsMostI(A,C),startsY(C,B).
supports(A,B):- object(B),mobile(A),equal(A,B).
supports(A,B):- mobile(A),rightDuringI(A,B),pointSurfaceContact(A,B).
supports(A,B):- mobile(A),centerDuring(A,B),on(B,A).
supports(A,B):- mobile(A),onI(A,B),leftDuring(B,A).
supports(A,B):- mobile(A),mostOverlapsMostI(A,C),rightDuringI(C,B).
supports(A,B):- mobile(C),mostFinishes(C,B),on(B,A).
supports(A,B):- mobile(A),meets(A,C),lessOverlapsMostI(C,B).
supports(A,B):- mobile(A),lessOverlapsMost(A,C),duringYI(C,B).
supports(A,B):- mobile(A),mostFinishesI(A,C),duringY(C,B).
supports(A,B):- mobile(A),onI(A,B),meets(B,A).
supports(A,B):- mobile(A),lessFinishesI(A,C),meets(C,B).
supports(A,B):- mobile(A),on(A,C),mostOverlapsMost(C,B).
supports(A,B):- mobile(A),meets(A,C),mostOverlapsLessI(C,B).
supports(A,B):- mobile(A),onI(A,C),lessOverlapsLessI(C,B).
supports(A,B):- mobile(A),rightDuringI(A,C),meets(C,B).
