supports(A,B):- object(B),lessOverlapsLess(B,A).
supports(A,B):- fixed(A),mostOverlapsLess(A,B).
supports(A,B):- fixed(A),lessOverlapsMost(A,B).
supports(A,B):- mobile(A),centerDuringI(A,B).
supports(A,B):- mobile(A),centerDuring(A,B).
supports(A,B):- fixed(A),startsY(A,B).
supports(A,B):- object(A),mostOverlapsMostI(A,C),lessOverlapsMost(C,B).
supports(A,B):- object(A),leftDuringI(A,C),rightDuring(C,B).
supports(A,B):- object(A),rightDuringI(A,C),centerDuring(C,B).
supports(A,B):- object(A),lessFinishesI(A,C),rightDuring(C,B).
supports(A,B):- object(A),lessFinishesI(A,C),overlapsYI(C,B).
supports(A,B):- object(A),lessStartsI(A,C),lessStarts(C,B).
supports(A,B):- object(A),lessOverlapsMost(A,C),mostOverlapsMost(C,B).
supports(A,B):- object(A),mostOverlapsLess(A,C),mostOverlapsLessI(C,B).
supports(A,B):- object(A),mostOverlapsMostI(A,C),mostOverlapsMostI(C,B).
supports(A,B):- object(A),lessStartsI(A,C),duringY(C,B).
supports(A,B):- object(A),lessStartsI(A,C),rightDuring(C,B).
supports(A,B):- object(A),lessOverlapsLess(A,C),lessStartsI(C,B).
supports(A,B):- object(A),mostOverlapsMostI(A,C),mostOverlapsMost(C,B).
supports(A,B):- object(A),overlapsY(A,C),mostOverlapsMostI(C,B).
supports(A,B):- object(A),lessOverlapsMost(A,C),mostFinishes(C,B).
supports(A,B):- object(A),lessFinishesI(A,C),lessStarts(C,B).
supports(A,B):- object(A),rightDuringI(A,C),mostOverlapsMost(C,B).
supports(A,B):- object(A),lessFinishesI(A,C),mostFinishes(C,B).
supports(A,B):- object(A),rightDuringI(A,C),mostFinishesI(C,B).
supports(A,B):- object(A),startsYI(A,C),lessOverlapsMost(C,B).
supports(A,B):- object(A),centerDuringI(A,C),mostOverlapsMost(C,B).
supports(A,B):- object(A),mostOverlapsMost(A,C),lessOverlapsMost(C,B).
supports(A,B):- object(A),duringYI(A,C),startsYI(C,B).
supports(A,B):- object(A),rightDuring(A,C),lessOverlapsMost(C,B).
supports(A,B):- object(A),centerDuring(A,C),mostOverlapsMostI(C,B).
supports(A,B):- object(A),finishesY(A,C),lessOverlapsMost(C,B).
supports(A,B):- object(A),lessOverlapsLessI(A,C),mostOverlapsMost(C,B).
supports(A,B):- object(A),mostOverlapsMostI(A,C),rightDuringI(C,B).
supports(A,B):- object(A),mostOverlapsMost(A,C),mostOverlapsLessI(C,B).
supports(A,B):- object(A),mostFinishesI(A,C),rightDuringI(C,B).
supports(A,B):- object(A),lessOverlapsLessI(A,C),duringY(C,B).
supports(A,B):- object(A),mostOverlapsMostI(A,C),overlapsY(C,B).
supports(A,B):- object(A),lessOverlapsLessI(A,C),meets(C,B).
supports(A,B):- object(A),mostFinishes(A,C),lessFinishesI(C,B).
supports(A,B):- object(A),lessOverlapsLess(A,C),mostOverlapsLessI(C,B).
supports(A,B):- object(A),mostFinishesI(A,C),lessOverlapsMostI(C,B).
supports(A,B):- object(A),lessOverlapsMostI(A,C),lessOverlapsMost(C,B).
supports(A,B):- object(A),centerDuringI(A,C),centerDuring(C,B).
supports(A,B):- object(A),mostOverlapsLessI(A,C),mostOverlapsMostI(C,B).
supports(A,B):- object(A),mostOverlapsLess(A,C),meetsI(C,B).
supports(A,B):- object(A),rightDuringI(A,C),meetsI(C,B).
supports(A,B):- object(A),mostOverlapsMostI(A,C),leftDuringI(C,B).
supports(A,B):- object(A),lessFinishesI(A,C),meetsI(C,B).
supports(A,B):- object(A),centerDuringI(A,C),rightDuringI(C,B).
supports(A,B):- object(A),lessOverlapsMost(A,C),lessOverlapsMostI(C,B).
supports(A,B):- object(A),finishesY(A,C),mostFinishes(C,B).
supports(A,B):- object(A),lessOverlapsLess(A,C),lessOverlapsMostI(C,B).
supports(A,B):- object(A),lessFinishes(A,C),overlapsYI(C,B).
supports(A,B):- object(A),mostFinishes(A,C),mostOverlapsLess(C,B).
supports(A,B):- object(A),lessOverlapsLessI(A,C),lessFinishesI(C,B).
supports(A,B):- object(A),meetsI(A,C),lessOverlapsLess(C,B).
supports(A,B):- object(A),mostOverlapsMostI(A,C),mostFinishesI(C,B).
supports(A,B):- object(A),centerDuringI(A,C),lessOverlapsMost(C,B).
supports(A,B):- object(A),lessStartsI(A,C),mostOverlapsMost(C,B).
supports(A,B):- object(A),mostOverlapsMost(A,C),mostOverlapsMostI(C,B).
supports(A,B):- object(A),mostOverlapsMost(A,C),mostOverlapsLess(C,B).
