supports(A,B):- mobile(B),lessStartsI(B,A).
supports(A,B):- mobile(B),lessFinishes(B,A).
supports(A,B):- mobile(B),mostFinishes(B,A).
supports(A,B):- object(A),rightDuringI(A,B).
supports(A,B):- mobile(B),centerDuring(B,A).
supports(A,B):- fixed(A),startsY(A,B).
supports(A,B):- object(A),leftDuringI(A,B).
supports(A,B):- mobile(B),rightDuringI(B,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,A).
supports(A,B):- mobile(B),lessOverlapsMost(B,A).
supports(A,B):- fixed(C),centerDuringI(C,B),on(B,A).
supports(A,B):- object(B),meets(B,C),rightDuring(C,A).
supports(A,B):- fixed(C),onI(C,A),lessStartsI(A,B).
supports(A,B):- fixed(C),onI(C,A),mostOverlapsMost(A,B).
supports(A,B):- object(B),mostOverlapsLess(B,C),centerDuringI(C,A).
supports(A,B):- fixed(C),lessOverlapsMost(C,A),mostOverlapsLessI(A,B).
supports(A,B):- object(B),mostFinishesI(B,C),lessOverlapsMost(C,A).
supports(A,B):- fixed(C),onI(C,A),lessOverlapsMost(A,B).
supports(A,B):- object(B),lessOverlapsLess(B,C),centerDuring(C,A).
supports(A,B):- object(B),meetsI(B,C),lessOverlapsMost(C,A).
supports(A,B):- object(B),finishesYI(B,C),mostFinishes(C,A).
supports(A,B):- object(B),duringY(B,C),overlapsYI(C,A).
supports(A,B):- fixed(C),centerDuringI(C,A),mostOverlapsMostI(A,B).
supports(A,B):- object(B),rightDuring(B,C),mostOverlapsMost(C,A).
supports(A,B):- object(B),lessStartsI(B,C),finishesY(C,A).
supports(A,B):- fixed(C),below(C,B),lessFinishesI(B,A).
supports(A,B):- object(B),on(B,A),mostOverlapsMostI(B,A).
supports(A,B):- object(B),lessStartsI(B,C),lessStarts(C,A).
supports(A,B):- object(B),mostOverlapsMostI(B,C),mostOverlapsLess(C,A).
supports(A,B):- object(B),overlapsYI(B,C),lessFinishesI(C,A).
supports(A,B):- object(B),duringY(B,C),meets(C,A).
supports(A,B):- object(B),lessStarts(B,C),mostOverlapsMostI(C,A).
supports(A,B):- object(B),on(B,C),duringY(C,A).
supports(A,B):- fixed(C),onI(C,A),lessOverlapsLessI(A,B).
supports(A,B):- fixed(C),rightDuringI(C,A),onI(A,B).
supports(A,B):- fixed(C),leftDuringI(C,B),meetsI(B,A).
supports(A,B):- fixed(C),below(C,B),lessOverlapsLess(B,A).
supports(A,B):- object(B),lessOverlapsLessI(B,C),meets(C,A).
supports(A,B):- object(B),mostFinishesI(B,C),mostOverlapsLessI(C,A).
