supports(A,B):- fixed(A),leftDuring(A,B).
supports(A,B):- object(A),startsY(A,B).
supports(A,B):- fixed(A),mostFinishes(A,B).
supports(A,B):- fixed(A),lessOverlapsMost(A,B).
supports(A,B):- fixed(A),mostOverlapsLess(A,B).
supports(A,B):- fixed(A),lessFinishesI(A,B).
supports(A,B):- mobile(B),on(B,A),equal(B,A).
supports(A,B):- object(B),lessStartsI(B,C),mostFinishesI(C,A).
supports(A,B):- object(B),rightDuring(B,C),mostOverlapsLess(C,A).
supports(A,B):- object(B),lessStarts(B,C),lessOverlapsMostI(C,A).
supports(A,B):- object(B),rightDuring(B,C),mostFinishesI(C,A).
supports(A,B):- object(B),mostOverlapsMost(B,C),lessFinishes(C,A).
supports(A,B):- object(B),mostFinishesI(B,C),rightDuringI(C,A).
supports(A,B):- object(B),lessOverlapsMost(B,C),lessFinishes(C,A).
supports(A,B):- object(B),leftDuringI(B,C),lessOverlapsMostI(C,A).
supports(A,B):- object(B),lessFinishesI(B,C),mostOverlapsMostI(C,A).
supports(A,B):- object(B),lessStarts(B,C),lessStartsI(C,A).
supports(A,B):- object(B),lessStarts(B,C),mostFinishes(C,A).
supports(A,B):- object(B),mostOverlapsLessI(B,C),lessFinishesI(C,A).
supports(A,B):- object(B),lessFinishesI(B,C),mostOverlapsMost(C,A).
supports(A,B):- object(B),mostOverlapsMost(B,C),lessStarts(C,A).
supports(A,B):- object(B),lessOverlapsMost(B,C),lessStartsI(C,A).
supports(A,B):- object(B),mostFinishes(B,C),lessFinishesI(C,A).
supports(A,B):- object(B),lessOverlapsLessI(B,C),mostFinishes(C,A).
supports(A,B):- object(B),lessOverlapsMostI(B,C),mostOverlapsLess(C,A).
supports(A,B):- object(B),mostOverlapsMost(B,C),centerDuringI(C,A).
supports(A,B):- object(B),lessFinishes(B,C),mostOverlapsLess(C,A).
supports(A,B):- object(B),mostOverlapsLess(B,C),lessFinishes(C,A).
supports(A,B):- object(B),lessStartsI(B,C),mostOverlapsLessI(C,A).
supports(A,B):- object(B),mostOverlapsMost(B,C),mostFinishes(C,A).
supports(A,B):- object(B),lessOverlapsMostI(B,C),lessOverlapsLess(C,A).
supports(A,B):- object(B),mostOverlapsLess(B,C),lessOverlapsMostI(C,A).
supports(A,B):- object(B),lessFinishes(B,C),mostFinishesI(C,A).
supports(A,B):- object(B),mostOverlapsMost(B,C),lessOverlapsLessI(C,A).
supports(A,B):- object(B),centerDuringI(B,C),mostOverlapsMost(C,A).
supports(A,B):- object(B),on(B,A),lessStartsI(B,A).
supports(A,B):- object(B),lessOverlapsLess(B,C),mostFinishes(C,A).
supports(A,B):- object(B),lessStarts(B,C),centerDuringI(C,A).
supports(A,B):- object(B),lessOverlapsMost(B,C),meetsI(C,A).
supports(A,B):- object(B),mostOverlapsLessI(B,C),lessOverlapsMost(C,A).
supports(A,B):- object(B),lessOverlapsMostI(B,C),centerDuringI(C,A).
supports(A,B):- object(B),mostFinishesI(B,C),mostOverlapsMostI(C,A).
supports(A,B):- object(B),rightDuring(B,C),lessFinishesI(C,A).
supports(A,B):- object(B),lessOverlapsLessI(B,C),centerDuringI(C,A).
supports(A,B):- object(B),mostFinishesI(B,C),mostOverlapsMost(C,A).
supports(A,B):- object(B),mostOverlapsMostI(B,C),mostFinishesI(C,A).
supports(A,B):- object(B),mostOverlapsMostI(B,C),lessStarts(C,A).
