supports(A,B):- mobile(A),centerDuringI(A,B).
supports(A,B):- fixed(A),startsY(A,B).
supports(A,B):- mobile(B),lessStartsI(B,A).
supports(A,B):- object(A),leftDuringI(A,B).
supports(A,B):- mobile(B),lessOverlapsMostI(B,A).
supports(A,B):- mobile(B),lessStarts(B,A).
supports(A,B):- mobile(B),leftDuringI(B,A).
supports(A,B):- object(A),mostOverlapsMost(A,C),mostFinishes(C,B).
supports(A,B):- mobile(C),overlapsYI(C,B),centerDuringI(B,A).
supports(A,B):- mobile(C),mostOverlapsMost(C,B),finishesY(B,A).
supports(A,B):- mobile(C),overlapsYI(C,B),leftDuring(B,A).
supports(A,B):- mobile(C),onI(C,A),lessOverlapsMost(C,B).
supports(A,B):- mobile(C),before(C,B),mostOverlapsMostI(B,A).
supports(A,B):- mobile(C),meets(C,B),lessOverlapsLess(C,A).
supports(A,B):- object(A),mostOverlapsMost(A,C),centerDuring(C,B).
supports(A,B):- mobile(C),leftDuring(C,B),meets(B,A).
supports(A,B):- object(A),mostOverlapsMost(A,C),rightDuringI(C,B).
supports(A,B):- mobile(C),onI(C,A),mostOverlapsMost(C,B).
supports(A,B):- mobile(C),lessOverlapsLessI(C,B),mostOverlapsLessI(B,A).
supports(A,B):- mobile(C),lessOverlapsMost(C,B),on(B,A).
supports(A,B):- mobile(C),centerDuringI(C,B),lessOverlapsLess(C,A).
supports(A,B):- mobile(C),overlapsYI(C,B),lessOverlapsLess(B,A).
supports(A,B):- mobile(C),meets(C,A),lessOverlapsLess(A,B).
supports(A,B):- mobile(C),meets(C,A),lessOverlapsMost(C,B).
supports(A,B):- mobile(C),lessOverlapsLess(C,A),finishesYI(A,B).
supports(A,B):- mobile(C),mostOverlapsLess(C,B),lessOverlapsMost(B,A).
supports(A,B):- mobile(C),meets(C,B),lessOverlapsLessI(B,A).
supports(A,B):- mobile(C),centerDuring(C,B),lessOverlapsMost(B,A).
supports(A,B):- mobile(C),lessOverlapsMostI(C,A),mostOverlapsLessI(A,B).
supports(A,B):- mobile(C),mostOverlapsLessI(C,A),meetsI(A,B).
supports(A,B):- mobile(C),lessOverlapsMost(C,B),mostOverlapsLess(C,A).
supports(A,B):- mobile(C),rightDuringI(C,B),lessOverlapsLess(C,A).
supports(A,B):- mobile(C),lessFinishes(C,A),meets(A,B).
supports(A,B):- mobile(C),finishesYI(C,A),mostOverlapsMost(C,B).
supports(A,B):- object(A),mostOverlapsMost(A,C),centerDuringI(C,B).
supports(A,B):- mobile(C),before(C,B),lessFinishesI(B,A).
supports(A,B):- mobile(C),lessOverlapsMostI(C,B),mostOverlapsLessI(B,A).
supports(A,B):- mobile(C),mostOverlapsMost(C,B),mostFinishes(B,A).
supports(A,B):- mobile(C),onI(C,B),mostOverlapsMost(B,A).
supports(A,B):- mobile(C),lessOverlapsMost(C,B),finishesY(B,A).
supports(A,B):- mobile(C),mostFinishesI(C,B),mostOverlapsLessI(B,A).
supports(A,B):- mobile(C),lessOverlapsLess(C,A),overlapsY(A,B).
