supports(A,B):- object(A),lessOverlapsLessI(A,B).
supports(A,B):- fixed(A),startsY(A,B).
supports(A,B):- fixed(A),lessFinishes(A,B).
supports(A,B):- object(A),centerDuring(A,B).
supports(A,B):- mobile(A),centerDuringI(A,B).
supports(A,B):- fixed(A),mostOverlapsLess(A,B).
supports(A,B):- object(B),mostOverlapsLess(B,A),on(B,A).
supports(A,B):- object(B),lessOverlapsMostI(B,A),on(B,A).
supports(A,B):- mobile(A),overlapsY(A,B),surfaceContact(A,B).
supports(A,B):- object(B),on(B,A),lessStarts(B,A).
supports(A,B):- object(A),lessOverlapsMostI(A,B),surfaceContact(A,B).
supports(A,B):- object(B),on(B,A),lessStartsI(B,A).
supports(A,B):- object(B),on(B,A),lessFinishes(B,A).
supports(A,B):- object(A),duringYI(A,B),surfaceContact(A,B).
supports(A,B):- object(B),lessOverlapsLessI(B,A),on(B,A).
supports(A,B):- object(B),on(B,A),rightDuring(B,A).
supports(A,B):- object(B),on(B,A),leftDuring(B,A).
supports(A,B):- object(B),on(B,A),equal(B,A).
supports(A,B):- object(B),on(B,A),mostFinishes(B,A).
supports(A,B):- object(A),finishesYI(A,B),surfaceContact(A,B).
