supports(A,B):- mobile(A),lessOverlapsLess(A,B).
supports(A,B):- mobile(A),mostFinishes(A,B).
supports(A,B):- object(B),lessFinishes(B,A).
supports(A,B):- fixed(A),mostOverlapsLess(A,B).
supports(A,B):- object(B),lessOverlapsLessI(B,A).
supports(A,B):- mobile(B),lessStartsI(B,A).
supports(A,B):- object(B),rightDuring(B,A).
supports(A,B):- mobile(B),lessStarts(B,A),surfaceContact(A,B).
supports(A,B):- mobile(B),on(B,A),centerDuring(A,B).
supports(A,B):- mobile(B),object(A),equal(A,B).
supports(A,B):- mobile(B),on(B,A),lessOverlapsLessI(A,B).
supports(A,B):- mobile(B),mostOverlapsLessI(B,C),centerDuring(C,A).
supports(A,B):- mobile(B),fixed(A),startsY(A,B).
supports(A,B):- mobile(B),lessOverlapsMost(B,C),mostFinishes(C,A).
supports(A,B):- mobile(B),on(B,A),leftDuringI(A,B).
supports(A,B):- mobile(B),mostOverlapsMostI(B,A),surfaceContact(A,B).
supports(A,B):- mobile(B),mostOverlapsMost(B,A),overlapsY(A,B).
supports(A,B):- mobile(B),rightDuringI(B,C),finishesYI(C,A).
supports(A,B):- mobile(B),lessOverlapsMostI(B,C),lessFinishesI(C,A).
supports(A,B):- mobile(B),startsYI(B,A),verticalContact(A,B).
supports(A,B):- mobile(B),lessFinishes(B,C),mostOverlapsMost(C,A).
supports(A,B):- mobile(B),on(B,A),lessStartsI(A,B).
supports(A,B):- mobile(B),on(B,A),pointSurfaceContact(A,B).
supports(A,B):- mobile(B),startsYI(B,A),mostOverlapsLess(A,B).
supports(A,B):- mobile(B),lessOverlapsLess(B,A),finishesYI(A,B).
supports(A,B):- mobile(B),startsYI(B,C),lessStarts(C,A).
supports(A,B):- mobile(B),centerDuringI(B,C),mostOverlapsLessI(C,A).
supports(A,B):- mobile(B),lessOverlapsLess(B,C),lessOverlapsLessI(C,A).
supports(A,B):- mobile(B),mostOverlapsLess(B,C),mostOverlapsLessI(C,A).
supports(A,B):- mobile(B),mostOverlapsLess(B,C),lessOverlapsMostI(C,A).
supports(A,B):- mobile(B),finishesY(B,A),pointSurfaceContact(A,B).
supports(A,B):- mobile(B),mostOverlapsLess(B,C),centerDuring(C,A).
supports(A,B):- mobile(B),duringYI(B,C),mostFinishes(C,A).
supports(A,B):- mobile(B),lessOverlapsMost(B,A),overlapsY(A,B).
supports(A,B):- mobile(B),lessOverlapsMost(B,A),onI(A,B).
supports(A,B):- mobile(B),lessOverlapsMostI(B,A),surfaceContact(A,B).
supports(A,B):- mobile(B),centerDuring(B,C),mostOverlapsMost(C,A).
supports(A,B):- mobile(B),on(B,A),mostOverlapsMostI(A,B).
supports(A,B):- mobile(B),overlapsYI(B,A),mostOverlapsMost(A,B).
supports(A,B):- mobile(B),lessOverlapsLessI(B,C),lessOverlapsLess(C,A).
supports(A,B):- mobile(B),lessOverlapsLess(B,A),overlapsY(A,B).
supports(A,B):- mobile(B),on(B,A),mostFinishesI(A,B).
supports(A,B):- mobile(B),on(B,A),horizontalContact(A,B).
supports(A,B):- mobile(B),lessOverlapsMostI(B,A),meets(A,B).
supports(A,B):- mobile(B),leftDuringI(B,C),leftDuring(C,A).
supports(A,B):- mobile(B),lessOverlapsMost(B,C),mostOverlapsLess(C,A).
supports(A,B):- mobile(B),leftDuringI(B,C),meets(C,A).
supports(A,B):- mobile(B),mostOverlapsMostI(B,C),mostOverlapsMost(C,A).
supports(A,B):- mobile(B),startsYI(B,A),lessOverlapsLessI(A,B).
supports(A,B):- mobile(B),on(B,A),rightDuringI(A,B).
supports(A,B):- mobile(B),mostOverlapsLessI(B,A),overlapsY(A,B).
supports(A,B):- mobile(B),mostFinishes(B,C),centerDuringI(C,A).
supports(A,B):- mobile(B),overlapsYI(B,A),mostFinishesI(A,B).
supports(A,B):- mobile(B),on(B,A),centerDuringI(A,B).
supports(A,B):- mobile(B),meetsI(B,C),centerDuring(C,A).
supports(A,B):- mobile(B),mostFinishes(B,C),mostOverlapsMost(C,A).
