supports(A,B):- mobile(B),leftDuringI(B,A).
supports(A,B):- fixed(C),startsY(C,B),lessOverlapsLess(B,A).
supports(A,B):- fixed(C),on(C,A),startsY(C,B).
supports(A,B):- object(A),finishesYI(A,C),overlapsY(C,B).
supports(A,B):- mobile(B),fixed(A),pointContact(A,B).
supports(A,B):- object(A),onI(A,B),lessOverlapsLessI(B,A).
supports(A,B):- object(A),onI(A,B),centerDuring(A,B).
supports(A,B):- object(A),centerDuringI(A,B),onI(A,B).
supports(A,B):- object(A),finishesY(A,C),overlapsY(C,B).
supports(A,B):- object(A),startsYI(A,C),lessOverlapsLessI(C,B).
supports(A,B):- object(A),mostFinishesI(A,C),mostOverlapsMostI(C,B).
supports(A,B):- object(A),lessOverlapsLess(A,B),surfaceContact(A,B).
supports(A,B):- object(A),leftDuringI(A,C),meets(C,B).
supports(A,B):- object(A),onI(A,B),lessFinishes(A,B).
supports(A,B):- object(A),duringY(A,C),meetsI(C,B).
supports(A,B):- fixed(C),lessOverlapsMost(C,B),on(B,A).
supports(A,B):- object(A),rightDuringI(A,C),mostOverlapsLessI(C,B).
supports(A,B):- object(A),lessOverlapsLessI(A,B),onI(A,B).
supports(A,B):- object(A),onI(A,B),mostOverlapsLess(A,B).
supports(A,B):- object(A),rightDuringI(A,C),startsY(C,B).
supports(A,B):- object(A),startsY(A,B),meets(A,B).
supports(A,B):- fixed(C),centerDuringI(C,B),mostFinishesI(B,A).
supports(A,B):- object(A),mostFinishes(A,C),mostOverlapsMost(C,B).
supports(A,B):- fixed(C),mostFinishesI(C,B),on(B,A).
supports(A,B):- fixed(C),onI(C,A),lessOverlapsMost(A,B).
supports(A,B):- fixed(C),leftDuringI(C,A),onI(A,B).
supports(A,B):- object(A),mostFinishesI(A,B),onI(A,B).
supports(A,B):- object(A),startsY(A,C),startsY(C,B).
supports(A,B):- object(A),meets(A,C),mostFinishes(C,B).
supports(A,B):- fixed(C),meetsI(C,B),mostFinishesI(B,A).
supports(A,B):- mobile(B),fixed(A),equal(A,B).
supports(A,B):- object(A),onI(A,B),rightDuringI(B,A).
supports(A,B):- object(A),overlapsYI(A,C),lessStarts(C,B).
supports(A,B):- object(A),lessOverlapsMostI(A,B),onI(A,B).
supports(A,B):- object(A),mostOverlapsLess(A,C),mostOverlapsMostI(C,B).
supports(A,B):- object(A),mostOverlapsMost(A,B),surfaceContact(B,A).
supports(A,B):- object(A),lessStartsI(A,C),mostOverlapsLess(C,B).
supports(A,B):- object(A),centerDuringI(A,C),mostFinishesI(C,B).
supports(A,B):- object(A),mostFinishesI(A,B),overlapsY(A,B).
supports(A,B):- object(C),finishesYI(C,B),mostOverlapsMost(B,A).
supports(A,B):- fixed(C),mostOverlapsLessI(C,A),onI(A,B).
supports(A,B):- object(A),onI(A,B),rightDuringI(A,B).
supports(A,B):- object(A),onI(A,B),leftDuringI(A,B).
supports(A,B):- object(A),startsY(A,B),surfaceContact(B,A).
supports(A,B):- fixed(C),rightDuringI(C,A),overlapsY(A,B).
supports(A,B):- object(A),mostOverlapsMostI(A,B),surfaceContact(A,B).
supports(A,B):- object(A),lessStartsI(A,B),onI(A,B).
supports(A,B):- object(A),onI(A,B),lessStarts(A,B).
supports(A,B):- fixed(C),lessStartsI(C,A),onI(A,B).
supports(A,B):- fixed(C),below(C,A),finishesYI(A,B).
supports(A,B):- object(A),onI(A,B),horizontalContact(A,B).
supports(A,B):- object(A),mostOverlapsLessI(A,C),lessOverlapsMost(C,B).
supports(A,B):- object(A),lessFinishesI(A,B),onI(A,B).
