supports(A,B):- fixed(A),startsY(A,B).
supports(A,B):- object(A),mostOverlapsMostI(A,B).
supports(A,B):- mobile(C),meetsI(C,B),lessOverlapsMostI(B,A).
supports(A,B):- mobile(C),lessStarts(C,B),on(B,A).
supports(A,B):- mobile(C),leftDuringI(C,A),onI(A,B).
supports(A,B):- mobile(C),mostOverlapsLessI(C,B),on(B,A).
supports(A,B):- mobile(C),lessFinishes(C,A),onI(A,B).
supports(A,B):- mobile(C),mostOverlapsLess(C,A),mostFinishes(A,B).
supports(A,B):- mobile(C),mostFinishes(C,A),mostOverlapsMostI(C,B).
supports(A,B):- mobile(C),finishesYI(C,A),onI(C,B).
supports(A,B):- mobile(C),after(C,A),mostOverlapsMost(A,B).
supports(A,B):- mobile(C),lessFinishesI(C,A),lessOverlapsMost(C,B).
supports(A,B):- mobile(C),rightDuringI(C,A),onI(A,B).
supports(A,B):- mobile(A),lessStarts(A,C),lessStartsI(C,B).
supports(A,B):- mobile(C),centerDuring(C,A),onI(A,B).
supports(A,B):- mobile(C),lessStarts(C,B),startsYI(B,A).
supports(A,B):- mobile(C),mostOverlapsMostI(C,A),onI(A,B).
supports(A,B):- mobile(C),overlapsYI(C,B),lessOverlapsLess(B,A).
supports(A,B):- mobile(C),lessOverlapsMostI(C,A),onI(A,B).
supports(A,B):- mobile(C),below(C,A),mostFinishes(A,B).
supports(A,B):- mobile(C),mostOverlapsMost(C,A),onI(A,B).
supports(A,B):- mobile(C),duringY(C,A),onI(A,B).
supports(A,B):- mobile(C),lessOverlapsMost(C,A),mostFinishesI(A,B).
supports(A,B):- mobile(C),lessFinishesI(C,B),lessOverlapsMost(C,A).
supports(A,B):- mobile(C),finishesYI(C,B),on(B,A).
supports(A,B):- mobile(C),mostOverlapsLess(C,B),on(B,A).
