supports(A,B):- mobile(B),startsYI(B,A).
supports(A,B):- object(C),meets(C,A),centerDuringI(A,B).
supports(A,B):- fixed(C),centerDuringI(C,B),lessOverlapsLess(B,A).
supports(A,B):- fixed(C),centerDuringI(C,B),meetsI(B,A).
supports(A,B):- object(C),mostFinishes(C,A),lessOverlapsLess(A,B).
supports(A,B):- fixed(C),lessStarts(C,A),onI(A,B).
supports(A,B):- fixed(C),centerDuringI(C,B),mostOverlapsLessI(B,A).
supports(A,B):- object(C),lessOverlapsMostI(C,A),mostOverlapsLess(A,B).
supports(A,B):- object(C),mostOverlapsMostI(C,A),lessStartsI(A,B).
supports(A,B):- object(C),on(C,A),lessFinishesI(A,B).
supports(A,B):- object(C),lessStartsI(C,A),lessFinishes(A,B).
supports(A,B):- object(C),leftDuringI(C,A),meetsI(A,B).
supports(A,B):- fixed(C),rightDuringI(C,A),centerDuringI(A,B).
supports(A,B):- fixed(C),centerDuringI(C,A),rightDuringI(A,B).
supports(A,B):- fixed(C),startsY(C,A),mostFinishesI(A,B).
supports(A,B):- object(C),mostOverlapsLess(C,A),lessOverlapsLess(A,B).
supports(A,B):- object(C),after(C,A),mostFinishesI(A,B).
supports(A,B):- object(C),lessOverlapsLessI(C,A),mostFinishes(A,B).
supports(A,B):- object(C),mostFinishes(C,A),centerDuringI(A,B).
supports(A,B):- fixed(C),after(C,B),centerDuring(B,A).
supports(A,B):- fixed(C),meets(C,B),meets(C,A).
supports(A,B):- object(C),lessFinishes(C,A),mostFinishesI(A,B).
supports(A,B):- fixed(C),lessStartsI(C,B),on(B,A).
supports(A,B):- object(C),mostOverlapsLess(C,A),centerDuringI(A,B).
supports(A,B):- object(C),mostOverlapsMostI(C,A),lessOverlapsMostI(A,B).
supports(A,B):- fixed(C),mostOverlapsMostI(C,B),on(B,A).
supports(A,B):- fixed(C),lessOverlapsLess(C,B),on(B,A).
supports(A,B):- object(C),lessOverlapsLess(C,A),mostOverlapsMostI(A,B).
supports(A,B):- fixed(C),rightDuringI(C,B),lessFinishesI(B,A).
supports(A,B):- fixed(C),leftDuringI(C,B),lessStartsI(B,A).
supports(A,B):- object(C),rightDuring(C,A),lessOverlapsMostI(A,B).
supports(A,B):- object(C),mostFinishes(C,A),lessStartsI(A,B).
supports(A,B):- object(C),mostFinishes(C,A),mostOverlapsLess(A,B).
supports(A,B):- fixed(C),centerDuringI(C,A),lessOverlapsLessI(A,B).
supports(A,B):- object(C),after(C,A),rightDuringI(A,B).
supports(A,B):- fixed(C),below(C,A),leftDuringI(A,B).
supports(A,B):- object(C),lessOverlapsMostI(C,A),lessOverlapsMostI(A,B).
supports(A,B):- fixed(C),after(C,A),lessOverlapsMostI(C,B).
supports(A,B):- object(C),lessOverlapsLessI(C,A),mostOverlapsMost(A,B).
