supports(A,B):- fixed(A),startsY(A,B).
supports(A,B):- mobile(B),mostOverlapsMost(B,A).
supports(A,B):- mobile(B),duringY(B,A).
supports(A,B):- mobile(B),leftDuringI(B,A).
supports(A,B):- mobile(B),centerDuringI(B,A).
supports(A,B):- mobile(B),rightDuring(B,A).
supports(A,B):- fixed(C),onI(C,B),lessStartsI(B,A).
supports(A,B):- fixed(C),onI(C,B),duringYI(B,A).
supports(A,B):- fixed(C),onI(C,A),lessOverlapsMost(A,B).
supports(A,B):- mobile(B),mostFinishesI(B,C),centerDuring(C,A).
supports(A,B):- mobile(B),lessStarts(B,C),lessStartsI(C,A).
supports(A,B):- fixed(C),leftDuringI(C,A),mostFinishes(A,B).
supports(A,B):- mobile(B),centerDuringI(B,C),centerDuring(C,A).
supports(A,B):- mobile(B),lessFinishes(B,C),mostOverlapsLess(C,A).
supports(A,B):- fixed(C),leftDuringI(C,A),mostOverlapsLessI(A,B).
supports(A,B):- fixed(C),onI(C,A),mostOverlapsMost(A,B).
supports(A,B):- fixed(C),lessStartsI(C,A),onI(A,B).
supports(A,B):- mobile(B),lessOverlapsMostI(B,C),mostOverlapsLess(C,A).
supports(A,B):- fixed(C),onI(C,A),mostFinishesI(A,B).
supports(A,B):- fixed(C),below(C,B),lessOverlapsMost(B,A).
supports(A,B):- fixed(C),below(C,B),centerDuring(B,A).
supports(A,B):- mobile(B),leftDuringI(B,C),onI(C,A).
supports(A,B):- fixed(C),centerDuringI(C,B),mostOverlapsLessI(B,A).
supports(A,B):- fixed(C),startsY(C,A),mostOverlapsLess(A,B).
supports(A,B):- fixed(C),below(C,A),lessStarts(A,B).
supports(A,B):- mobile(B),meetsI(B,C),lessOverlapsMost(C,A).
supports(A,B):- fixed(C),leftDuringI(C,A),mostOverlapsMost(A,B).
supports(A,B):- fixed(C),centerDuringI(C,B),mostFinishesI(B,A).
supports(A,B):- mobile(B),mostOverlapsMostI(B,C),leftDuring(C,A).
supports(A,B):- fixed(C),centerDuringI(C,B),lessFinishesI(B,A).
