supports(A,B):- fixed(A),mostFinishes(A,B).
supports(A,B):- fixed(A),lessStarts(A,B).
supports(A,B):- object(B),startsYI(B,A).
supports(A,B):- fixed(A),mostOverlapsLess(A,B).
supports(A,B):- object(C),mostOverlapsMost(C,A),lessStarts(A,B).
supports(A,B):- object(C),lessOverlapsLessI(C,A),lessOverlapsMost(A,B).
supports(A,B):- object(C),mostOverlapsMost(C,A),mostFinishes(A,B).
supports(A,B):- object(C),mostOverlapsMostI(C,A),leftDuring(A,B).
supports(A,B):- object(C),startsY(C,A),lessFinishes(A,B).
supports(A,B):- object(C),mostFinishes(C,A),lessOverlapsLess(A,B).
supports(A,B):- object(C),startsY(C,A),mostFinishesI(A,B).
supports(A,B):- object(C),rightDuringI(C,A),centerDuringI(A,B).
supports(A,B):- object(C),mostOverlapsMost(C,A),lessOverlapsMostI(A,B).
supports(A,B):- object(C),mostOverlapsMost(C,A),mostOverlapsLess(A,B).
supports(A,B):- object(C),lessStartsI(C,A),mostOverlapsMost(A,B).
supports(A,B):- object(C),mostOverlapsMostI(C,A),rightDuringI(A,B).
supports(A,B):- object(C),mostOverlapsMostI(C,A),lessOverlapsMostI(A,B).
supports(A,B):- object(C),lessOverlapsLessI(C,A),mostOverlapsMost(A,B).
supports(A,B):- object(C),leftDuringI(C,A),leftDuringI(A,B).
supports(A,B):- object(C),mostOverlapsMostI(C,A),mostOverlapsLessI(A,B).
supports(A,B):- object(C),mostOverlapsLess(C,A),lessStarts(A,B).
supports(A,B):- object(C),mostOverlapsMost(C,A),mostOverlapsLessI(A,B).
supports(A,B):- object(C),startsY(C,A),lessOverlapsMostI(A,B).
supports(A,B):- object(C),startsY(C,A),centerDuringI(A,B).
supports(A,B):- object(C),startsY(C,A),mostOverlapsMost(A,B).
supports(A,B):- object(C),centerDuring(C,A),lessOverlapsLessI(A,B).
supports(A,B):- object(C),startsY(C,A),mostFinishes(A,B).
supports(A,B):- object(C),mostFinishes(C,A),centerDuringI(A,B).
supports(A,B):- object(C),lessFinishesI(C,A),mostOverlapsLessI(A,B).
supports(A,B):- object(C),lessOverlapsMostI(C,A),mostFinishes(A,B).
supports(A,B):- object(C),rightDuringI(C,A),leftDuringI(A,B).
supports(A,B):- object(C),mostOverlapsMost(C,A),lessFinishesI(A,B).
supports(A,B):- object(C),lessFinishesI(C,A),leftDuring(A,B).
supports(A,B):- object(C),meetsI(C,A),lessStartsI(A,B).
supports(A,B):- object(C),leftDuringI(C,A),centerDuringI(A,B).
supports(A,B):- object(C),startsY(C,A),mostOverlapsMostI(A,B).
supports(A,B):- object(C),lessOverlapsMostI(C,A),mostFinishesI(A,B).
supports(A,B):- object(C),mostOverlapsMostI(C,A),lessFinishes(A,B).
supports(A,B):- object(C),lessOverlapsLessI(C,A),mostFinishesI(A,B).
