supports(A,B):- mobile(B),startsYI(B,A).
supports(A,B):- mobile(A),centerDuringI(A,C),lessFinishesI(C,B).
supports(A,B):- mobile(A),lessFinishes(A,B),pointSurfaceContact(B,A).
supports(A,B):- object(C),mostOverlapsMost(C,B),on(B,A).
supports(A,B):- mobile(A),meetsI(A,C),lessOverlapsLess(C,B).
supports(A,B):- mobile(A),mostOverlapsLess(A,B),on(B,A).
supports(A,B):- mobile(A),rightDuringI(A,C),mostOverlapsMostI(C,B).
supports(A,B):- object(B),on(B,A),lessOverlapsMostI(A,B).
supports(A,B):- object(C),mostOverlapsMostI(C,A),mostOverlapsLessI(C,B).
supports(A,B):- fixed(A),onI(A,B),pointContact(B,A).
supports(A,B):- object(C),lessStarts(C,A),lessOverlapsLess(A,B).
supports(A,B):- mobile(A),mostFinishesI(A,B),on(B,A).
supports(A,B):- mobile(A),onI(A,B),equal(A,B).
supports(A,B):- mobile(A),mostOverlapsLess(A,C),lessStartsI(C,B).
supports(A,B):- mobile(A),mostOverlapsMostI(A,C),mostFinishesI(C,B).
supports(A,B):- mobile(A),mostFinishesI(A,C),lessOverlapsLess(C,B).
supports(A,B):- mobile(A),lessOverlapsLessI(A,B),pointSurfaceContact(B,A).
supports(A,B):- object(B),on(B,A),lessFinishesI(A,B).
supports(A,B):- mobile(B),on(B,A),leftDuringI(A,B).
supports(A,B):- mobile(A),lessStartsI(A,B),pointSurfaceContact(B,A).
supports(A,B):- mobile(A),lessOverlapsMost(A,C),meetsI(C,B).
supports(A,B):- mobile(A),lessStarts(A,B),on(B,A).
supports(A,B):- fixed(C),lessOverlapsMost(C,A),onI(A,B).
supports(A,B):- mobile(A),rightDuringI(A,C),mostOverlapsLessI(C,B).
supports(A,B):- mobile(A),mostFinishes(A,B),on(B,A).
supports(A,B):- mobile(A),mostOverlapsMostI(A,C),lessFinishesI(C,B).
supports(A,B):- fixed(C),mostOverlapsLess(C,A),onI(A,B).
supports(A,B):- fixed(C),below(C,A),lessFinishes(C,B).
supports(A,B):- object(B),on(B,A),centerDuringI(A,B).
supports(A,B):- mobile(A),rightDuringI(A,B),pointSurfaceContact(B,A).
supports(A,B):- mobile(A),onI(A,B),horizontalContact(A,B).
