supports(A,B):- fixed(A),mostOverlapsLessI(A,B).
supports(A,B):- mobile(B),leftDuringI(B,A).
supports(A,B):- mobile(B),lessStartsI(B,A).
supports(A,B):- object(A),mostFinishes(A,B).
supports(A,B):- fixed(A),mostOverlapsLess(A,B).
supports(A,B):- fixed(A),lessOverlapsMostI(A,B).
supports(A,B):- object(A),lessFinishesI(A,B).
supports(A,B):- object(A),lessOverlapsLess(A,B).
supports(A,B):- fixed(A),lessStartsI(A,B).
supports(A,B):- mobile(B),mostFinishes(B,C),centerDuring(C,A).
supports(A,B):- mobile(B),centerDuringI(B,C),lessOverlapsMost(C,A).
supports(A,B):- mobile(B),lessOverlapsMostI(B,C),leftDuring(C,A).
supports(A,B):- mobile(B),lessStarts(B,C),meetsI(C,A).
supports(A,B):- object(B),lessOverlapsMostI(B,A),surfaceContact(A,B).
supports(A,B):- mobile(B),lessOverlapsLess(B,C),rightDuring(C,A).
supports(A,B):- mobile(B),lessOverlapsMost(B,C),leftDuring(C,A).
supports(A,B):- mobile(B),leftDuringI(B,C),leftDuring(C,A).
supports(A,B):- mobile(B),lessOverlapsMost(B,C),mostFinishes(C,A).
supports(A,B):- mobile(B),fixed(C),leftDuring(C,A).
supports(A,B):- object(B),leftDuring(B,A),surfaceContact(A,B).
supports(A,B):- object(B),rightDuring(B,A),surfaceContact(A,B).
supports(A,B):- mobile(B),centerDuring(B,C),mostOverlapsMost(C,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,C),leftDuring(C,A).
supports(A,B):- object(B),lessFinishesI(B,A),surfaceContact(A,B).
supports(A,B):- object(B),fixed(A),surfaceContact(A,B).
supports(A,B):- mobile(B),rightDuringI(B,C),leftDuring(C,A).
supports(A,B):- mobile(B),mostOverlapsLess(B,C),centerDuring(C,A).
supports(A,B):- mobile(B),lessOverlapsMostI(B,C),lessFinishesI(C,A).
supports(A,B):- mobile(B),lessOverlapsLess(B,C),mostFinishes(C,A).
supports(A,B):- mobile(B),lessFinishesI(B,C),leftDuring(C,A).
supports(A,B):- object(B),lessOverlapsMost(B,A),surfaceContact(A,B).
supports(A,B):- mobile(B),lessOverlapsLess(B,C),lessStartsI(C,A).
supports(A,B):- object(B),finishesY(B,A),surfaceContact(A,B).
supports(A,B):- object(B),lessStarts(B,A),surfaceContact(A,B).
supports(A,B):- mobile(B),lessOverlapsLessI(B,C),overlapsY(C,A).
supports(A,B):- mobile(B),lessOverlapsMost(B,C),lessFinishes(C,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,C),lessOverlapsMost(C,A).
supports(A,B):- mobile(B),finishesYI(B,C),leftDuring(C,A).
supports(A,B):- mobile(B),leftDuringI(B,C),mostOverlapsLess(C,A).
supports(A,B):- mobile(B),rightDuring(B,C),equalY(C,A).
supports(A,B):- mobile(B),object(A),equal(A,B).
supports(A,B):- mobile(B),lessFinishes(B,C),mostFinishesI(C,A).
supports(A,B):- mobile(B),lessStartsI(B,C),meets(C,A).
supports(A,B):- mobile(B),mostFinishesI(B,C),lessOverlapsLess(C,A).
supports(A,B):- mobile(B),mostOverlapsMost(B,C),lessOverlapsLess(C,A).
supports(A,B):- mobile(B),mostOverlapsMost(B,C),lessStartsI(C,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,C),lessOverlapsLess(C,A).
supports(A,B):- mobile(B),centerDuringI(B,C),mostOverlapsMost(C,A).
supports(A,B):- mobile(B),lessFinishes(B,C),meets(C,A).
supports(A,B):- mobile(B),lessOverlapsMost(B,C),meetsI(C,A).
supports(A,B):- mobile(B),mostOverlapsMost(B,C),meetsI(C,A).
supports(A,B):- mobile(B),centerDuring(B,C),mostOverlapsMostI(C,A).
supports(A,B):- mobile(B),mostFinishesI(B,C),rightDuring(C,A).
supports(A,B):- mobile(B),lessFinishes(B,C),mostOverlapsMost(C,A).
supports(A,B):- mobile(B),mostOverlapsLess(B,C),meetsI(C,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,C),equalY(C,A).
supports(A,B):- mobile(B),mostOverlapsLess(B,C),lessOverlapsMostI(C,A).
supports(A,B):- mobile(B),mostOverlapsMost(B,C),lessOverlapsMost(C,A).
supports(A,B):- mobile(B),lessOverlapsLess(B,C),mostOverlapsLessI(C,A).
supports(A,B):- mobile(B),mostOverlapsLess(B,C),rightDuring(C,A).
supports(A,B):- mobile(B),mostFinishesI(B,C),mostOverlapsMostI(C,A).
supports(A,B):- mobile(B),meets(B,C),lessStarts(C,A).
supports(A,B):- mobile(B),lessFinishes(B,C),lessFinishesI(C,A).
supports(A,B):- mobile(B),lessOverlapsMost(B,C),lessOverlapsLessI(C,A).
supports(A,B):- mobile(B),mostOverlapsMost(B,C),lessOverlapsMostI(C,A).
supports(A,B):- mobile(B),lessOverlapsMostI(B,C),mostOverlapsMost(C,A).
supports(A,B):- mobile(B),mostOverlapsLess(B,C),mostOverlapsLessI(C,A).
supports(A,B):- mobile(B),mostOverlapsLessI(B,C),mostOverlapsMost(C,A).
supports(A,B):- mobile(B),mostOverlapsMostI(B,C),finishesYI(C,A).
supports(A,B):- mobile(B),centerDuringI(B,C),lessOverlapsLessI(C,A).
supports(A,B):- mobile(B),lessOverlapsLessI(B,C),finishesY(C,A).
supports(A,B):- mobile(B),mostFinishes(B,C),mostOverlapsMost(C,A).
supports(A,B):- mobile(B),mostOverlapsLess(B,C),mostOverlapsMostI(C,A).
supports(A,B):- mobile(B),duringYI(B,C),mostFinishes(C,A).
supports(A,B):- object(B),mostOverlapsMostI(B,A),surfaceContact(A,B).
