supports(A,B):- mostFinishes(A,B).
supports(A,B):- mostOverlapsLess(B,A).
supports(A,B):- lessOverlapsMost(B,A).
supports(A,B):- meets(B,C),horizontalContact(C,A).
supports(A,B):- mostFinishes(B,C),overlapsY(A,C).
supports(A,B):- centerDuring(A,C),mostOverlapsMost(C,B).
supports(A,B):- meets(B,C),mostOverlapsMost(A,C).
supports(A,B):- mostFinishes(B,C),mostOverlapsMost(A,C).
supports(A,B):- equalY(A,C),rightDuring(C,B).
supports(A,B):- startsY(A,B),meets(A,B).
supports(A,B):- startsY(A,B),mostOverlapsMost(A,B).
supports(A,B):- meets(B,A),startsY(A,B).
supports(A,B):- meets(A,B),on(B,A).
supports(A,B):- meets(B,C),lessOverlapsMost(A,C).
supports(A,B):- on(B,A),centerDuring(A,B).
supports(A,B):- overlapsY(B,C),mostFinishes(A,C).
supports(A,B):- mostOverlapsLess(A,C),below(C,B).
supports(A,B):- overlapsY(B,C),leftDuring(A,C).
supports(A,B):- on(B,A),verticalContact(A,B).
supports(A,B):- verticalContact(A,B),equalY(A,B).
supports(A,B):- meets(B,C),duringY(C,A).
supports(A,B):- on(B,C),overlapsY(C,A).
supports(A,B):- lessOverlapsLess(A,B),duringY(A,B).
supports(A,B):- centerDuring(B,A),on(B,A).
supports(A,B):- overlapsY(A,B),verticalContact(A,B).
supports(A,B):- surfaceContact(B,A),startsY(A,B).
supports(A,B):- mostOverlapsMost(A,B),on(B,A).
supports(A,B):- on(B,A),lessStarts(B,A).
supports(A,B):- on(B,A),equal(A,B).
supports(A,B):- startsY(A,B),on(B,A).
supports(A,B):- on(B,A),mostOverlapsMost(B,A).
supports(A,B):- startsY(B,C),duringY(C,A).
supports(A,B):- lessOverlapsMost(A,C),mostFinishes(C,B).
supports(A,B):- duringY(A,C),lessOverlapsMost(C,B).
supports(A,B):- pointSurfaceContact(B,A),overlapsY(A,B).
supports(A,B):- lessOverlapsMost(A,C),mostOverlapsLess(B,C).
supports(A,B):- meets(B,C),mostFinishes(C,A).
supports(A,B):- lessOverlapsLess(A,B),startsY(A,B).
supports(A,B):- leftDuring(A,D),startsY(D,C),mostOverlapsLess(C,B).
supports(A,B):- finishesY(B,C),startsY(A,C),meets(C,B).