supports(A,B):- mobile(B),startsYI(B,A).
supports(A,B):- mobile(A),lessOverlapsMostI(A,B).
supports(A,B):- mobile(C),before(C,B),lessFinishesI(B,A).
supports(A,B):- mobile(C),mostOverlapsLessI(C,B),mostOverlapsMostI(C,A).
supports(A,B):- mobile(C),on(C,A),lessFinishesI(A,B).
supports(A,B):- mobile(C),below(C,B),mostFinishes(B,A).
supports(A,B):- mobile(C),mostFinishesI(C,B),mostOverlapsMost(C,A).
supports(A,B):- fixed(C),mostOverlapsMostI(C,B),on(B,A).
supports(A,B):- fixed(C),lessOverlapsMostI(C,B),on(B,A).
supports(A,B):- mobile(C),mostFinishes(C,A),lessOverlapsLess(A,B).
supports(A,B):- mobile(C),centerDuring(C,B),mostOverlapsLessI(B,A).
supports(A,B):- object(A),rightDuringI(A,B),onI(A,B).
supports(A,B):- mobile(C),mostOverlapsMostI(C,A),mostOverlapsLess(A,B).
supports(A,B):- fixed(C),mostOverlapsLess(C,A),onI(A,B).
supports(A,B):- fixed(C),below(C,A),leftDuringI(A,B).
supports(A,B):- mobile(C),lessOverlapsMostI(C,B),lessStartsI(B,A).
supports(A,B):- fixed(C),lessFinishes(C,B),on(B,A).
supports(A,B):- object(A),onI(A,B),lessStartsI(A,B).
supports(A,B):- fixed(C),meets(C,B),meets(C,A).
supports(A,B):- fixed(C),onI(C,A),mostFinishesI(A,B).
supports(A,B):- mobile(C),meetsI(C,B),lessOverlapsMostI(C,A).
supports(A,B):- object(A),onI(A,B),equal(A,B).
supports(A,B):- fixed(C),lessOverlapsMost(C,A),onI(A,B).
supports(A,B):- mobile(C),mostFinishes(C,A),mostOverlapsLess(A,B).
supports(A,B):- mobile(C),centerDuring(C,B),mostFinishesI(B,A).
supports(A,B):- object(A),onI(A,B),meetsI(B,A).
supports(A,B):- object(A),onI(A,B),centerDuringI(A,B).
supports(A,B):- mobile(C),below(C,A),lessOverlapsLessI(A,B).
supports(A,B):- mobile(C),centerDuringI(C,A),mostOverlapsLess(A,B).
supports(A,B):- mobile(C),mostOverlapsMost(C,B),on(B,A).
supports(A,B):- mobile(C),lessStarts(C,A),lessOverlapsLess(A,B).
supports(A,B):- mobile(C),centerDuring(C,A),lessFinishesI(C,B).
supports(A,B):- mobile(C),lessFinishesI(C,B),mostOverlapsMost(C,A).
supports(A,B):- mobile(C),meets(C,B),mostOverlapsMost(B,A).
supports(A,B):- object(A),onI(A,B),meetsI(A,B).
