supports(A,B):- object(A),centerDuring(A,B).
supports(A,B):- object(B),duringY(B,A).
supports(A,B):- object(A),rightDuringI(A,B).
supports(A,B):- fixed(A),startsY(A,B).
supports(A,B):- object(B),on(B,A),equal(B,A).
supports(A,B):- object(B),on(B,A),mostOverlapsLess(A,B).
supports(A,B):- object(B),startsYI(B,A),verticalContact(B,A).
supports(A,B):- object(B),on(B,A),lessOverlapsMost(B,A).
supports(A,B):- object(B),lessOverlapsMostI(B,A),finishesY(B,A).
supports(A,B):- object(B),mostFinishes(B,A),on(B,A).
supports(A,B):- object(B),duringYI(B,A),lessOverlapsLess(B,A).
supports(A,B):- object(B),overlapsYI(B,A),mostOverlapsLess(B,A).
supports(A,B):- object(B),on(B,A),verticalContact(B,A).
