supports(A,B):- mobile(A),lessOverlapsLess(A,B).
supports(A,B):- mobile(A),mostFinishes(A,B).
supports(A,B):- mobile(B),leftDuringI(B,A).
supports(A,B):- mobile(A),lessFinishesI(A,B).
supports(A,B):- fixed(A),meets(A,B).
supports(A,B):- mobile(B),lessStartsI(B,A).
supports(A,B):- fixed(C),centerDuringI(C,A),lessOverlapsMostI(A,B).
supports(A,B):- fixed(C),rightDuringI(C,B),centerDuring(B,A).
supports(A,B):- fixed(C),centerDuringI(C,B),mostOverlapsMostI(B,A).
supports(A,B):- fixed(C),mostOverlapsMostI(C,B),mobile(A).
supports(A,B):- fixed(C),centerDuringI(C,A),leftDuringI(A,B).
supports(A,B):- fixed(C),mostOverlapsLessI(C,B),mostOverlapsLess(B,A).
supports(A,B):- fixed(C),before(C,A),mostFinishesI(A,B).
supports(A,B):- fixed(C),below(C,B),rightDuring(B,A).
supports(A,B):- fixed(C),duringY(C,B),on(B,A).
supports(A,B):- fixed(C),rightDuringI(C,A),finishesYI(A,B).
supports(A,B):- fixed(C),mostOverlapsLess(C,A),lessOverlapsLessI(A,B).
supports(A,B):- fixed(C),lessOverlapsMost(C,B),on(B,A).
supports(A,B):- fixed(C),mostOverlapsLessI(C,A),mostOverlapsMost(A,B).
supports(A,B):- fixed(C),on(C,A),mostOverlapsMostI(A,B).
supports(A,B):- fixed(C),on(C,A),onI(C,B).
supports(A,B):- fixed(C),rightDuringI(C,A),lessOverlapsMost(A,B).
supports(A,B):- fixed(C),centerDuringI(C,A),mostFinishesI(A,B).
supports(A,B):- fixed(C),lessOverlapsLess(C,A),meets(C,B).
supports(A,B):- fixed(C),startsY(C,A),centerDuringI(A,B).
supports(A,B):- fixed(C),below(C,B),lessStarts(B,A).
supports(A,B):- fixed(C),rightDuringI(C,A),centerDuring(A,B).
supports(A,B):- fixed(C),mostOverlapsMost(C,A),startsY(A,B).
supports(A,B):- fixed(C),centerDuringI(C,A),mostOverlapsMost(A,B).
supports(A,B):- fixed(C),centerDuringI(C,A),meetsI(A,B).
supports(A,B):- fixed(C),lessFinishesI(C,A),meetsI(A,B).
supports(A,B):- fixed(C),centerDuringI(C,B),centerDuringI(B,A).
supports(A,B):- fixed(C),mostOverlapsLessI(C,A),mostOverlapsMostI(A,B).
supports(A,B):- fixed(C),overlapsYI(C,A),startsY(A,B).
supports(A,B):- fixed(C),meets(C,A),onI(A,B).
supports(A,B):- fixed(C),leftDuringI(C,B),lessOverlapsMost(B,A).
supports(A,B):- fixed(C),onI(C,A),mostOverlapsLess(A,B).
supports(A,B):- fixed(C),centerDuringI(C,A),lessOverlapsLessI(A,B).
supports(A,B):- fixed(C),rightDuringI(C,A),lessFinishes(A,B).
supports(A,B):- fixed(C),mostOverlapsMost(C,B),on(B,A).
supports(A,B):- fixed(C),mostOverlapsMostI(C,A),meetsI(C,B).
supports(A,B):- fixed(C),lessFinishesI(C,B),lessFinishesI(C,A).
supports(A,B):- fixed(C),onI(C,A),lessOverlapsMost(A,B).
supports(A,B):- fixed(C),centerDuringI(C,A),centerDuringI(A,B).
