supports(A,B):- mobile(B),overlapsY(B,A),lessOverlapsLessI(A,B).
supports(A,B):- mobile(B),overlapsYI(B,C),finishesYI(C,A).
supports(A,B):- fixed(C),on(C,A),startsY(C,B).
supports(A,B):- mobile(B),overlapsY(B,C),mostOverlapsLess(C,A).
supports(A,B):- mobile(B),lessOverlapsMost(B,C),overlapsY(C,A).
supports(A,B):- mobile(B),finishesY(B,A),surfaceContact(A,B).
supports(A,B):- mobile(B),on(B,A),surfaceContact(A,B).
supports(A,B):- mobile(B),overlapsYI(B,A),surfaceContact(A,B).
supports(A,B):- mobile(B),overlapsY(B,C),mostOverlapsMostI(C,A).
supports(A,B):- mobile(B),fixed(C),overlapsY(C,A).
supports(A,B):- mobile(B),finishesY(B,A),lessOverlapsLessI(A,B).
supports(A,B):- fixed(C),leftDuringI(C,A),onI(A,B).
supports(A,B):- mobile(B),duringYI(B,C),mostOverlapsMost(C,A).
supports(A,B):- mobile(B),startsYI(B,A),surfaceContact(B,A).
supports(A,B):- mobile(B),overlapsYI(B,A),centerDuring(A,B).
supports(A,B):- mobile(B),on(B,A),lessOverlapsMost(B,A).
supports(A,B):- fixed(C),startsY(C,A),mostOverlapsMostI(A,B).
supports(A,B):- mobile(B),overlapsYI(B,C),finishesY(C,A).
supports(A,B):- mobile(B),startsYI(B,C),startsYI(C,A).
supports(A,B):- mobile(B),finishesY(B,A),lessStartsI(A,B).
supports(A,B):- mobile(B),on(B,A),leftDuringI(A,B).
supports(A,B):- mobile(B),on(B,C),finishesYI(C,A).
supports(A,B):- mobile(B),startsY(B,C),mostOverlapsLess(C,A).
supports(A,B):- mobile(B),on(B,A),pointContact(A,B).
supports(A,B):- mobile(B),on(B,A),equal(A,B).
supports(A,B):- mobile(B),on(B,A),mostOverlapsMost(A,B).
