supports(A,B):- object(B),startsYI(B,A).
supports(A,B):- mobile(B),leftDuringI(B,A).
supports(A,B):- mobile(A),leftDuringI(A,B).
supports(A,B):- object(C),lessStartsI(C,A),lessOverlapsMostI(A,B).
supports(A,B):- object(C),mostOverlapsLessI(C,A),mostFinishes(A,B).
supports(A,B):- fixed(C),lessOverlapsLess(C,A),below(C,B).
supports(A,B):- fixed(C),on(C,A),mostOverlapsMostI(A,B).
supports(A,B):- object(C),leftDuringI(C,A),lessFinishes(A,B).
supports(A,B):- object(C),centerDuringI(C,B),mostFinishesI(B,A).
supports(A,B):- object(C),lessOverlapsLessI(C,A),mostOverlapsLessI(C,B).
supports(A,B):- object(C),meetsI(C,B),lessOverlapsLessI(B,A).
supports(A,B):- object(C),mostOverlapsLessI(C,A),lessFinishes(A,B).
supports(A,B):- fixed(C),centerDuring(C,B),on(B,A).
supports(A,B):- fixed(C),onI(C,A),mostFinishesI(A,B).
supports(A,B):- object(C),lessOverlapsMostI(C,B),rightDuringI(B,A).
supports(A,B):- fixed(C),centerDuringI(C,A),mostOverlapsLess(A,B).
supports(A,B):- fixed(C),startsY(C,A),mostOverlapsMost(A,B).
supports(A,B):- object(C),lessOverlapsLess(C,A),lessOverlapsMost(C,B).
supports(A,B):- object(C),rightDuringI(C,B),centerDuring(C,A).
supports(A,B):- fixed(C),lessFinishesI(C,B),mostOverlapsLess(C,A).
supports(A,B):- object(C),centerDuringI(C,B),lessOverlapsLessI(C,A).
supports(A,B):- object(C),lessStartsI(C,A),lessStartsI(C,B).
supports(A,B):- fixed(C),mostOverlapsMostI(C,B),meetsI(B,A).
supports(A,B):- object(C),mostOverlapsMostI(C,A),lessOverlapsMostI(A,B).
supports(A,B):- object(C),mostFinishesI(C,A),lessStarts(C,B).
supports(A,B):- fixed(C),onI(C,A),mostFinishes(A,B).
supports(A,B):- fixed(C),mostOverlapsLess(C,A),meets(C,B).
supports(A,B):- fixed(C),startsY(C,A),lessOverlapsMostI(A,B).
supports(A,B):- object(C),lessOverlapsMost(C,B),centerDuringI(C,A).
supports(A,B):- object(C),lessOverlapsLessI(C,A),centerDuring(C,B).
supports(A,B):- object(C),mostOverlapsMostI(C,B),lessOverlapsLessI(B,A).
supports(A,B):- fixed(C),lessFinishes(C,A),onI(A,B).
supports(A,B):- object(C),mostFinishesI(C,B),lessOverlapsMost(B,A).
supports(A,B):- object(C),lessOverlapsMost(C,B),lessFinishesI(C,A).
supports(A,B):- object(C),leftDuring(C,B),lessFinishesI(B,A).
supports(A,B):- object(C),lessFinishesI(C,B),lessOverlapsMost(C,A).
supports(A,B):- object(C),lessOverlapsMostI(C,A),mostFinishesI(A,B).
supports(A,B):- object(C),lessStarts(C,B),rightDuring(C,A).
supports(A,B):- object(C),lessOverlapsMost(C,B),meets(B,A).
supports(A,B):- mobile(C),centerDuringI(C,A),centerDuringI(A,B).
supports(A,B):- fixed(C),lessFinishes(C,B),on(B,A).
supports(A,B):- object(C),mostOverlapsMost(C,B),mostFinishesI(C,A).
supports(A,B):- fixed(C),centerDuringI(C,A),lessOverlapsMost(A,B).
supports(A,B):- object(C),lessStartsI(C,A),mostOverlapsLess(A,B).
supports(A,B):- fixed(C),leftDuringI(C,A),mostOverlapsLess(A,B).
supports(A,B):- object(C),lessOverlapsMostI(C,B),mostOverlapsLess(C,A).
supports(A,B):- fixed(C),mostFinishes(C,A),onI(A,B).
supports(A,B):- object(C),lessOverlapsMostI(C,B),lessStartsI(B,A).
supports(A,B):- object(C),rightDuringI(C,B),mostFinishesI(C,A).
supports(A,B):- fixed(C),mostOverlapsLessI(C,A),onI(A,B).
supports(A,B):- object(C),mostFinishesI(C,B),lessStartsI(B,A).
supports(A,B):- object(C),mostOverlapsMost(C,B),lessFinishesI(B,A).
supports(A,B):- object(C),mostOverlapsMost(C,A),lessFinishesI(A,B).
supports(A,B):- fixed(C),startsY(C,A),centerDuringI(A,B).
supports(A,B):- mobile(C),mostFinishes(C,A),mostOverlapsLess(A,B).
supports(A,B):- fixed(C),onI(C,A),lessOverlapsMost(A,B).
supports(A,B):- fixed(C),mostOverlapsMost(C,A),meets(C,B).
supports(A,B):- object(C),mostOverlapsMostI(C,A),mostOverlapsLessI(C,B).
supports(A,B):- object(C),before(C,A),rightDuringI(A,B).
supports(A,B):- object(C),meets(C,A),lessOverlapsMost(C,B).
supports(A,B):- object(C),mostOverlapsMostI(C,B),mostFinishes(C,A).
supports(A,B):- object(C),mostFinishesI(C,A),lessFinishesI(C,B).
supports(A,B):- object(C),mostOverlapsLess(C,B),mostFinishesI(B,A).
supports(A,B):- object(C),mostFinishes(C,A),lessOverlapsLess(C,B).
supports(A,B):- fixed(C),mostFinishesI(C,B),rightDuringI(C,A).
supports(A,B):- object(C),centerDuring(C,A),lessOverlapsLessI(A,B).
supports(A,B):- object(C),lessOverlapsMostI(C,B),meetsI(B,A).
supports(A,B):- object(C),mostFinishes(C,A),centerDuringI(A,B).
supports(A,B):- fixed(C),mostOverlapsLessI(C,B),on(B,A).
supports(A,B):- object(C),rightDuringI(C,B),mostFinishes(B,A).
supports(A,B):- object(C),leftDuring(C,B),meetsI(B,A).
supports(A,B):- fixed(C),startsY(C,A),mostOverlapsMostI(A,B).
supports(A,B):- object(C),lessFinishesI(C,A),mostFinishesI(C,B).
supports(A,B):- object(C),rightDuring(C,B),meets(B,A).
supports(A,B):- object(C),lessOverlapsMostI(C,A),rightDuringI(A,B).
supports(A,B):- object(C),mostOverlapsLessI(C,A),mostFinishesI(A,B).
