stable(A):-lessStarts(A,B),lessOverlapsMost(B,C).
stable(D):-lessFinishes(D,E),supports(E,F).
stable(G):-mostOverlapsLess(G,H),mostOverlapsLess(H,I).
stable(J):-mostFinishes(J,K),centerDuring(K,L).
stable(bg_18_29).
stable(bg_17_3).
stable(bg_15_6).
stable(M):-leftDuring(M,N),supports(N,M).
stable(O):-mostOverlapsMost(O,P),lessOverlapsLess(P,Q).
stable(R):-meets(R,S),centerDuring(S,T).
stable(bg_11_4).
stable(bg_10_30).
stable(bg_10_29).
stable(bg_10_28).
stable(bg_10_21).
stable(bg_10_18).
stable(U):-rightDuring(U,V),supports(V,U).
stable(W):-leftDuring(W,X),above(X,Y).
stable(Z):-centerDuring(Z,A1).
stable(B1):-fixed(B1).