stable(A):-object(B),lessOverlapsMost(B,A).
stable(bg_13_39).
stable(C):-mostFinishes(C,D),supports(D,C).
stable(bg_13_30).
stable(bg_13_14).
stable(E):-rightDuring(E,F),supports(F,E).
stable(G):-mostOverlapsLess(G,H),supports(H,G).
stable(I):-mostOverlapsMost(I,J),mostOverlapsMost(J,K).
stable(bg_12_12).
stable(L):-centerDuring(L,M),supports(M,L).
stable(N):-leftDuring(N,O),supports(O,N).
stable(P):-lessStarts(P,Q).
stable(bg_10_31).
stable(R):-meets(R,S),lessOverlapsMost(R,T).
stable(bg_10_3).
stable(U):-supports(U,V),rightDuring(U,W).
stable(X):-lessFinishes(X,Y).
stable(bg_10_27).
stable(bg_10_24).
stable(bg_10_22).
stable(bg_10_2).
stable(bg_10_15).
stable(bg_10_14).
stable(bg_10_13).
stable(bg_10_12).
stable(bg_10_11).
stable(bg_10_10).
stable(bg_10_1).
stable(bg_0_6).
stable(bg_0_2).
stable(bg_0_10).
stable(Z):-fixed(Z).
