stable(A):- fixed(A).
stable(A):- fixed(B),lessStartsI(B,A).
stable(A):- mobile(A),startsYI(A,B),supports(A,B).
stable(A):- fixed(B),startsY(B,A),mostOverlapsLessI(B,A).
stable(A):- mobile(A),meets(A,B),supports(B,A).
stable(A):- fixed(B),lessOverlapsLessI(B,C),onI(C,A).
stable(A):- mobile(A),onI(A,B),rightDuring(A,B).
stable(A):- fixed(B),lessStartsI(B,C),duringYI(C,A).
stable(A):- fixed(B),lessOverlapsMost(B,C),rightDuringI(C,A).
stable(A):- fixed(B),startsYI(B,C),meetsI(C,A).
stable(A):- mobile(A),overlapsY(A,B),rightDuringI(B,A).
stable(A):- mobile(A),startsYI(A,B),mostOverlapsMostI(B,A).
stable(A):- mobile(A),startsYI(A,B),lessStarts(B,A).
stable(A):- mobile(A),lessOverlapsLessI(A,B),startsYI(B,A).
stable(A):- fixed(B),leftDuringI(B,C),centerDuring(C,A).
stable(A):- mobile(B),lessOverlapsMostI(B,C),lessOverlapsMostI(C,A).
stable(A):- mobile(A),duringY(A,B),rightDuringI(B,A).
stable(A):- mobile(A),lessFinishesI(A,B),below(B,A).
stable(A):- fixed(B),lessStartsI(B,C),overlapsY(C,A).
stable(A):- mobile(A),duringYI(A,B),mostOverlapsLess(B,A).
stable(A):- fixed(B),mostOverlapsMostI(B,C),finishesY(C,A).
stable(A):- fixed(B),lessStartsI(B,C),startsY(C,A).
stable(A):- fixed(B),rightDuringI(B,C),lessOverlapsMost(C,A).
stable(A):- fixed(B),lessOverlapsMost(B,A),pointSurfaceContact(A,B).
stable(A):- mobile(A),lessOverlapsLessI(A,B),overlapsYI(B,A).
stable(A):- fixed(B),rightDuringI(B,C),lessOverlapsLessI(C,A).
stable(A):- fixed(B),startsY(B,A),mostOverlapsLess(B,A).
stable(A):- mobile(A),rightDuringI(A,B),pointContact(B,A).
stable(A):- mobile(A),onI(A,B),leftDuringI(B,A).
stable(A):- fixed(B),lessFinishesI(B,C),duringYI(C,A).
stable(A):- fixed(B),lessOverlapsLess(B,C),mostOverlapsMostI(C,A).
stable(A):- mobile(A),startsY(A,B),supports(B,A).
stable(A):- mobile(A),mostOverlapsLess(A,B),duringYI(B,A).
stable(A):- fixed(B),lessStartsI(B,C),finishesYI(C,A).
stable(A):- fixed(B),lessStartsI(B,C),startsYI(C,A).
stable(A):- fixed(B),lessOverlapsLessI(B,C),duringYI(C,A).
stable(A):- mobile(A),leftDuringI(A,B),pointSurfaceContact(B,A).
stable(A):- object(B),lessOverlapsMostI(B,A),finishesY(A,B).
stable(A):- mobile(A),meetsI(A,B),supports(A,B).
stable(A):- fixed(B),lessOverlapsLessI(B,C),finishesYI(C,A).
stable(A):- mobile(A),leftDuringI(A,B),onI(B,A).
stable(A):- fixed(B),lessFinishesI(B,C),mostOverlapsLessI(C,A).
stable(A):- mobile(A),lessFinishes(A,B),above(B,A).
stable(A):- mobile(A),mostFinishes(A,B),onI(B,A).
stable(A):- mobile(A),mostOverlapsMostI(A,B),startsYI(B,A).
stable(A):- mobile(A),lessStarts(A,B),supports(A,B).
stable(A):- fixed(B),meets(B,C),onI(C,A).
stable(A):- mobile(A),lessOverlapsLess(A,B),pointContact(B,A).
stable(A):- mobile(B),on(B,A),lessFinishesI(A,B).
stable(A):- fixed(B),rightDuring(B,C),equalY(C,A).
