stable(A):- fixed(A).
stable(A):- fixed(B),lessOverlapsMost(B,A).
stable(A):- fixed(B),mostOverlapsLessI(B,A).
stable(A):- object(B),lessStartsI(B,A).
stable(A):- fixed(B),meets(B,A).
stable(A):- object(B),lessStarts(B,A).
stable(A):- mobile(B),leftDuringI(B,A).
stable(A):- object(B),lessFinishesI(B,A).
stable(A):- object(B),leftDuring(B,A).
stable(A):- object(B),mostFinishesI(B,A).
stable(A):- object(B),lessOverlapsLessI(B,A).
stable(A):- object(B),mostFinishes(B,A).
stable(A):- fixed(B),startsYI(B,A).
stable(A):- mobile(B),overlapsYI(B,A),mostOverlapsMost(A,B).
stable(A):- object(B),overlapsY(B,A),lessOverlapsLessI(A,B).
stable(A):- object(B),below(B,A),lessOverlapsLessI(A,B).
stable(A):- mobile(B),equalY(B,A),mostOverlapsMost(A,B).
stable(A):- mobile(B),startsYI(B,A),mostOverlapsMost(A,B).
stable(A):- object(B),on(B,A),lessOverlapsLessI(A,B).
stable(A):- object(B),overlapsYI(B,A),lessOverlapsLessI(A,B).
stable(A):- mobile(A),mostOverlapsMost(A,B),supports(B,A).
stable(A):- object(B),startsYI(B,A),lessOverlapsLessI(A,B).
