stable(A):- fixed(A).
stable(A):- object(B),lessFinishesI(B,A).
stable(A):- fixed(B),meets(B,A).
stable(A):- object(B),mostFinishes(B,A).
stable(A):- fixed(B),lessOverlapsMost(B,A).
stable(A):- fixed(B),startsYI(B,A).
stable(A):- fixed(B),mostOverlapsLessI(B,A).
stable(A):- object(B),mostFinishesI(B,A).
stable(A):- object(B),lessStartsI(B,A).
stable(A):- object(B),lessOverlapsLessI(B,A).
stable(A):- mobile(B),leftDuringI(B,A).
stable(A):- object(B),meets(B,A),equalY(A,B).
stable(A):- object(B),meets(B,A),on(A,B).
stable(A):- mobile(C),finishesY(C,B),meets(B,A).
stable(A):- object(C),leftDuringI(C,B),meets(B,A).
stable(A):- mobile(C),mostOverlapsLess(C,B),meets(B,A).
stable(A):- object(C),meetsI(C,B),mostOverlapsMostI(B,A).
stable(A):- mobile(C),meets(C,B),meets(B,A).
stable(A):- object(B),mostOverlapsMostI(B,A),supports(B,A).
stable(A):- object(C),centerDuringI(C,B),meets(B,A).
