stable(A):- object(B),lessStarts(B,A),pointSurfaceContact(A,B).
stable(A):- object(B),rightDuring(B,A),verticalContact(B,A).
stable(A):- object(B),finishesY(B,A),horizontalContact(B,A).
stable(A):- object(B),mostOverlapsMost(B,C),mostOverlapsLess(C,A).
stable(A):- startsYI(A,B),object(B),mostOverlapsMost(B,A).
stable(A):- mostOverlapsMostI(A,B),object(B),meets(B,A).
stable(A):- object(B),on(B,A),leftDuringI(B,A).
stable(A):- object(B),duringY(B,A),surfaceContact(A,B).
stable(A):- object(B),lessOverlapsMost(B,A),pointContact(B,A).
stable(A):- object(A),mostOverlapsMost(A,B),meetsI(B,A).
stable(A):- object(B),lessStartsI(B,A),below(B,A).
stable(A):- object(B),lessOverlapsMost(B,A),supports(B,A).
stable(A):- meetsI(B,A),object(A),overlapsY(A,B).
stable(A):- object(B),rightDuring(B,C),overlapsY(C,A).
stable(A):- object(A),mostOverlapsMost(A,B),pointContact(B,A).
stable(A):- object(B),finishesY(B,A),meetsI(A,B).
stable(A):- object(B),equalY(B,A),mostOverlapsMostI(B,A).
stable(A):- overlapsYI(B,A),object(A),mostFinishes(A,B).
stable(A):- object(A),overlapsY(A,B),lessOverlapsLessI(A,B).
stable(A):- object(B),mostOverlapsLess(B,A),startsY(A,B).
stable(A):- lessStartsI(B,A),object(B),on(B,A).
stable(A):- object(B),lessStarts(B,A),above(B,A).
stable(A):- object(B),mostOverlapsMost(B,C),mostFinishes(C,A).
stable(A):- duringYI(B,A),object(B),meets(B,A).
stable(A):- object(A),startsY(A,B),supports(A,B).
stable(A):- duringYI(A,B),object(B),lessStarts(B,A).
stable(A):- object(A),lessStarts(A,B),supports(B,A).
stable(A):- object(A),meets(A,B),supports(A,B).
stable(A):- object(A),duringY(A,B),meetsI(B,A).
stable(A):- object(A),finishesY(A,B),pointSurfaceContact(A,B).
stable(A):- object(B),overlapsY(B,A),pointContact(A,B).
stable(A):- object(B),leftDuring(B,C),meets(C,A).
stable(A):- duringYI(B,A),object(A),lessFinishes(A,B).
stable(A):- object(B),rightDuringI(B,A),on(B,A).
stable(A):- object(B),meets(B,C),lessFinishes(C,A).
stable(A):- object(B),mostFinishes(B,A),above(B,A).
stable(A):- object(B),mostOverlapsLess(B,C),mostOverlapsLess(C,A).
stable(A):- object(A),lessFinishes(A,B),pointSurfaceContact(A,B).
stable(A):- mostFinishesI(A,B),object(B),overlapsY(B,A).
stable(A):- object(B),duringY(B,C),below(C,A).