stable(A):- fixed(A).
stable(A):- fixed(B),centerDuring(B,A).
stable(A):- fixed(B),mostOverlapsMost(B,A).
stable(A):- mobile(B),lessStarts(B,A).
stable(A):- mobile(A),meetsI(A,B),overlapsYI(B,A).
stable(A):- mobile(A),meetsI(A,B),duringY(B,A).
stable(A):- mobile(B),startsY(B,A),meetsI(A,B).
stable(A):- mobile(A),meetsI(A,B),supports(B,A).
stable(A):- mobile(A),meetsI(A,B),finishesYI(B,A).
