stable(A):- fixed(A).
stable(A):- mobile(A),finishesY(A,B),lessOverlapsMost(A,B).
stable(A):- object(C),mostOverlapsMost(C,B),lessStarts(B,A).
stable(A):- fixed(C),lessStartsI(C,B),startsY(B,A).
stable(A):- mobile(A),mostOverlapsMost(A,B),startsYI(A,B).
stable(A):- fixed(C),lessStartsI(C,B),overlapsY(B,A).
stable(A):- mobile(A),startsY(A,B),mostOverlapsMost(B,A).
stable(A):- object(C),lessOverlapsMostI(C,B),lessOverlapsMostI(B,A).
stable(A):- fixed(C),lessOverlapsLessI(C,B),overlapsY(B,A).
stable(A):- object(C),rightDuring(C,B),overlapsYI(B,A).
stable(A):- fixed(B),lessOverlapsMost(B,A),pointSurfaceContact(A,B).
stable(A):- mobile(A),startsYI(A,B),supports(A,B).
stable(A):- mobile(A),overlapsY(A,B),mostOverlapsLessI(A,B).
stable(A):- object(C),leftDuring(C,B),lessStartsI(B,A).
stable(A):- fixed(C),lessOverlapsLessI(C,B),below(B,A).
stable(A):- fixed(C),leftDuringI(C,B),centerDuring(B,A).
stable(A):- object(C),lessOverlapsLess(C,B),lessStartsI(B,A).
stable(A):- object(C),lessStartsI(C,B),mostOverlapsMostI(B,A).
stable(A):- fixed(C),rightDuringI(C,B),lessOverlapsLessI(B,A).
stable(A):- object(C),lessOverlapsMost(C,B),rightDuringI(B,A).
stable(A):- object(C),lessOverlapsMostI(C,B),mostOverlapsLess(B,A).
stable(A):- mobile(A),onI(A,B),rightDuring(A,B).
stable(A):- mobile(A),lessFinishesI(A,B),below(B,A).
stable(A):- object(C),rightDuring(C,B),lessStartsI(B,A).
stable(A):- mobile(B),lessFinishesI(B,A),below(A,B).
stable(A):- mobile(A),overlapsY(A,B),lessOverlapsLessI(A,B).
stable(A):- fixed(C),leftDuring(C,B),rightDuringI(B,A).
stable(A):- object(C),lessFinishesI(C,B),lessOverlapsMost(B,A).
stable(A):- fixed(C),lessStartsI(C,B),finishesYI(B,A).
stable(A):- fixed(C),startsYI(C,B),meetsI(B,A).
stable(A):- object(C),duringYI(C,B),leftDuringI(B,A).
stable(A):- object(C),rightDuringI(C,B),centerDuringI(B,A).
stable(A):- fixed(C),startsY(C,B),on(B,A).
stable(A):- fixed(C),lessStartsI(C,B),duringYI(B,A).
stable(A):- fixed(B),startsY(B,A),mostOverlapsLess(A,B).
stable(A):- mobile(B),onI(B,A),lessFinishesI(B,A).
stable(A):- fixed(C),lessFinishesI(C,B),startsYI(B,A).
stable(A):- object(C),lessStartsI(C,B),mostFinishes(B,A).
stable(A):- object(C),leftDuring(C,B),meets(B,A).
stable(A):- fixed(C),lessStartsI(C,B),startsYI(B,A).
stable(A):- mobile(A),mostFinishes(A,B),onI(B,A).
stable(A):- fixed(C),lessOverlapsLessI(C,B),duringYI(B,A).
stable(A):- mobile(A),startsYI(A,B),lessOverlapsLess(A,B).
stable(A):- mobile(A),lessFinishesI(A,B),onI(A,B).
stable(A):- fixed(C),overlapsY(C,B),meets(B,A).
stable(A):- fixed(C),lessOverlapsLessI(C,B),finishesYI(B,A).
stable(A):- fixed(C),lessOverlapsLess(C,B),mostOverlapsMostI(B,A).
stable(A):- object(C),mostOverlapsLessI(C,B),mostOverlapsLessI(B,A).
