stable(A):- fixed(A).
stable(A):- mobile(B),leftDuring(B,A).
stable(A):- fixed(B),lessFinishesI(B,A).
stable(A):- fixed(B),startsYI(B,A).
stable(A):- fixed(B),on(B,A).
stable(A):- object(B),lessOverlapsMost(B,A),verticalContact(B,A).
stable(A):- object(B),mostOverlapsLess(B,C),startsYI(C,A).
stable(A):- object(B),mostOverlapsMost(B,C),finishesYI(C,A).
stable(A):- object(B),leftDuringI(B,A),supports(B,A).
stable(A):- object(B),meetsI(B,C),mostOverlapsLessI(C,A).
stable(A):- object(B),lessFinishesI(B,C),lessOverlapsMostI(C,A).
stable(A):- object(B),mostFinishes(B,C),startsY(C,A).
stable(A):- object(B),leftDuringI(B,A),surfaceContact(B,A).
stable(A):- object(B),mostFinishesI(B,C),duringYI(C,A).
stable(A):- object(B),mostOverlapsMost(B,C),mostFinishesI(C,A).
stable(A):- object(B),mostOverlapsMost(B,C),startsYI(C,A).
stable(A):- object(B),startsY(B,C),mostOverlapsMost(C,A).
stable(A):- object(B),mostFinishesI(B,C),finishesY(C,A).
stable(A):- object(B),mostOverlapsMostI(B,C),startsYI(C,A).
stable(A):- object(B),lessStartsI(B,A),verticalContact(B,A).
stable(A):- object(B),lessOverlapsLessI(B,C),startsYI(C,A).
stable(A):- object(B),mostOverlapsLess(B,A),verticalContact(B,A).
stable(A):- object(B),duringYI(B,C),mostFinishes(C,A).
stable(A):- object(B),duringYI(B,C),overlapsYI(C,A).
stable(A):- object(B),startsY(B,C),mostFinishesI(C,A).
stable(A):- object(B),mostOverlapsMostI(B,A),verticalContact(B,A).
stable(A):- object(B),startsY(B,A),verticalContact(B,A).
stable(A):- object(B),mostOverlapsMost(B,C),duringYI(C,A).
stable(A):- object(B),startsY(B,C),lessFinishesI(C,A).
stable(A):- object(B),lessFinishesI(B,C),overlapsYI(C,A).
stable(A):- object(B),overlapsY(B,C),mostOverlapsLess(C,A).
stable(A):- object(B),mostOverlapsMost(B,C),centerDuring(C,A).
