stable(A):- fixed(A).
stable(A):- object(B),meets(B,C),mostFinishesI(C,A).
stable(A):- object(B),rightDuringI(B,C),centerDuringI(C,A).
stable(A):- fixed(B),meetsI(B,C),on(C,A).
stable(A):- object(A),rightDuringI(A,B),surfaceContact(A,B).
stable(A):- object(B),below(B,A),equal(B,A).
stable(A):- object(B),lessOverlapsMostI(B,C),after(C,A).
stable(A):- object(A),on(A,B),rightDuringI(B,A).
stable(A):- object(B),lessStartsI(B,C),meets(C,A).
stable(A):- above(B,A),mobile(B),lessOverlapsLessI(B,A).
stable(A):- fixed(B),onI(B,A),pointContact(A,B).
stable(A):- object(B),mostOverlapsLess(B,A),verticalContact(B,A).
stable(A):- object(A),lessOverlapsMostI(A,B),verticalContact(B,A).
stable(A):- object(B),lessOverlapsLess(B,A),verticalContact(B,A).
stable(A):- object(A),mostOverlapsLess(A,B),onI(B,A).
stable(A):- object(A),leftDuring(A,B),surfaceContact(A,B).
stable(A):- object(B),lessOverlapsMost(B,C),mostOverlapsMostI(C,A).
stable(A):- mobile(B),mostOverlapsLess(B,C),meets(C,A).
stable(A):- object(C),startsY(C,A),meets(A,B),surfaceContact(B,C).
stable(A):- object(C),leftDuringI(C,B),mostOverlapsMost(B,A),surfaceContact(B,C).
stable(A):- object(C),rightDuringI(C,B),mostOverlapsLessI(B,A),surfaceContact(B,C).
stable(A):- object(C),lessOverlapsMostI(C,B),centerDuringI(B,A),surfaceContact(B,C).
stable(A):- object(C),lessOverlapsLessI(C,B),surfaceContact(B,C),centerDuringI(B,A).
