stable(A):- fixed(A).
stable(A):- mobile(B),lessStarts(B,A).
stable(A):- object(C),lessStartsI(C,B),startsY(B,A).
stable(A):- object(C),meets(C,B),rightDuringI(B,A).
stable(A):- object(C),startsYI(C,B),mostOverlapsLessI(B,A).
stable(A):- object(C),overlapsYI(C,B),on(B,A).
stable(A):- object(C),lessFinishes(C,B),leftDuringI(B,A).
stable(A):- object(C),lessStarts(C,B),overlapsYI(B,A).
stable(A):- object(C),lessFinishes(C,B),meets(B,A).
stable(A):- object(C),lessStarts(C,B),meetsI(B,A).
stable(A):- object(C),mostOverlapsLessI(C,B),mostOverlapsMostI(B,A).
stable(A):- object(C),lessStarts(C,B),centerDuringI(B,A).
stable(A):- object(C),mostOverlapsLess(C,B),lessOverlapsLessI(B,A).
stable(A):- object(B),meets(B,C),lessFinishesI(C,A).
stable(A):- object(C),mostOverlapsLess(C,B),lessStartsI(B,A).
stable(A):- object(C),lessStarts(C,B),on(B,A).
stable(A):- object(C),overlapsYI(C,B),mostFinishesI(B,A).
stable(A):- object(C),rightDuringI(C,B),mostOverlapsLess(B,A).
stable(A):- object(C),rightDuringI(C,B),lessOverlapsMostI(B,A).
stable(A):- object(C),mostFinishes(C,B),startsY(B,A).
stable(A):- object(C),after(C,B),mostFinishes(B,A).
stable(A):- object(C),leftDuringI(C,B),finishesY(B,A).
