stable(A):- fixed(A).
stable(A):- fixed(B),mostOverlapsMostI(B,A).
stable(A):- object(B),lessOverlapsLessI(B,A).
stable(A):- fixed(B),mostFinishes(B,A).
stable(A):- object(C),lessOverlapsMost(C,B),meetsI(B,A).
stable(A):- object(C),mostOverlapsMost(C,B),centerDuring(B,A).
stable(A):- object(C),mostOverlapsLessI(C,B),meetsI(B,A).
stable(A):- object(C),lessFinishes(C,B),leftDuringI(B,A).
stable(A):- object(C),lessStarts(C,B),meetsI(B,A).
stable(A):- object(C),mostFinishes(C,B),meets(B,A).
stable(A):- object(C),lessOverlapsLess(C,B),onI(B,A).
stable(A):- object(C),meets(C,B),mostOverlapsLess(B,A).
stable(A):- object(C),mostOverlapsLessI(C,B),lessOverlapsMost(B,A).
stable(A):- object(C),lessOverlapsLessI(C,B),mostOverlapsMostI(B,A).
stable(A):- object(C),meets(C,B),mostOverlapsMost(B,A).
stable(A):- object(C),lessStarts(C,B),meets(B,A).
stable(A):- object(C),meets(C,B),lessStarts(B,A).
stable(A):- object(C),lessStarts(C,B),mostOverlapsLessI(B,A).
stable(A):- object(C),lessOverlapsMostI(C,B),lessStartsI(B,A).
