stable(A):- fixed(A).
stable(A):- fixed(B),lessOverlapsMost(B,A).
stable(A):- fixed(B),startsYI(B,A).
stable(A):- fixed(B),lessFinishesI(B,A).
stable(A):- fixed(B),meetsI(B,A).
stable(A):- object(B),leftDuring(B,A).
stable(A):- object(C),startsY(C,B),leftDuringI(B,A).
stable(A):- object(C),finishesYI(C,B),mostFinishes(B,A).
stable(A):- object(C),mostFinishesI(C,B),finishesY(B,A).
stable(A):- object(C),mostOverlapsMostI(C,B),finishesYI(B,A).
stable(A):- object(C),overlapsY(C,B),mostOverlapsLess(B,A).
stable(A):- object(C),overlapsY(C,B),lessStartsI(B,A).
stable(A):- object(C),lessOverlapsMost(C,B),overlapsYI(B,A).
stable(A):- object(C),meetsI(C,B),mostOverlapsLessI(B,A).
stable(A):- object(C),mostFinishesI(C,B),duringYI(B,A).
stable(A):- object(C),finishesYI(C,B),overlapsYI(B,A).
stable(A):- object(C),mostOverlapsLess(C,B),startsYI(B,A).
stable(A):- object(C),lessOverlapsMost(C,B),startsYI(B,A).
stable(A):- object(C),mostOverlapsMostI(C,B),overlapsY(B,A).
stable(A):- object(C),startsY(C,B),mostOverlapsMost(B,A).
stable(A):- object(C),duringY(C,B),lessOverlapsMost(B,A).
stable(A):- object(C),lessFinishesI(C,B),lessOverlapsMostI(B,A).
stable(A):- object(C),lessOverlapsMost(C,B),finishesYI(B,A).
stable(A):- object(C),duringYI(C,B),overlapsYI(B,A).
stable(A):- object(C),lessFinishes(C,B),startsYI(B,A).
stable(A):- object(C),lessOverlapsMost(C,B),duringYI(B,A).
stable(A):- object(C),lessFinishes(C,B),finishesYI(B,A).
stable(A):- object(C),lessOverlapsMost(C,B),centerDuring(B,A).
stable(A):- object(C),lessOverlapsLessI(C,B),startsYI(B,A).
