stable(A):- fixed(A).
stable(A):- mobile(B),onI(B,A),lessFinishesI(B,A).
stable(A):- object(B),rightDuringI(B,C),centerDuringI(C,A).
stable(A):- object(B),lessOverlapsLess(B,A),startsYI(B,A).
stable(A):- object(B),mostOverlapsLessI(B,C),mostOverlapsLessI(C,A).
stable(A):- object(B),overlapsYI(B,A),lessOverlapsLessI(A,B).
stable(A):- object(B),lessFinishes(B,A),below(B,A).
stable(A):- object(B),lessStartsI(B,A),supports(A,B).
stable(A):- fixed(B),startsYI(B,C),meetsI(C,A).
stable(A):- object(B),leftDuring(B,C),lessStartsI(C,A).
stable(A):- fixed(B),lessOverlapsLessI(B,C),below(C,A).
stable(A):- fixed(B),lessStartsI(B,C),finishesYI(C,A).
stable(A):- fixed(B),lessOverlapsLessI(B,C),overlapsY(C,A).
stable(A):- fixed(B),lessFinishesI(B,C),startsYI(C,A).
stable(A):- fixed(B),lessStartsI(B,C),startsYI(C,A).
stable(A):- object(B),lessOverlapsLessI(B,A),pointContact(A,B).
stable(A):- fixed(B),lessStartsI(B,C),duringYI(C,A).
stable(A):- object(B),lessFinishesI(B,A),below(A,B).
stable(A):- mobile(C),lessFinishesI(C,B),mostOverlapsMostI(B,A).
stable(A):- object(B),lessFinishes(B,A),on(B,A).
stable(A):- object(B),rightDuring(B,C),overlapsYI(C,A).
stable(A):- object(B),duringYI(B,A),mostOverlapsLess(A,B).
stable(A):- object(B),duringY(B,A),rightDuringI(A,B).
stable(A):- object(B),mostOverlapsLess(B,C),lessStarts(C,A).
stable(A):- fixed(B),lessOverlapsLessI(B,C),finishesYI(C,A).
stable(A):- object(B),lessOverlapsMostI(B,C),lessOverlapsMostI(C,A).
stable(A):- fixed(B),startsYI(B,C),rightDuringI(C,A).
stable(A):- object(B),meetsI(B,A),supports(B,A).
stable(A):- object(B),lessFinishesI(B,C),lessOverlapsMost(C,A).
stable(A):- fixed(B),overlapsY(B,C),meets(C,A).
stable(A):- object(B),startsY(B,A),mostOverlapsMost(A,B).
stable(A):- fixed(B),lessOverlapsLessI(B,C),duringYI(C,A).
stable(A):- object(B),lessOverlapsMost(B,C),rightDuringI(C,A).
stable(A):- object(B),on(B,A),rightDuring(A,B).
stable(A):- object(B),meets(B,A),supports(A,B).
stable(A):- object(B),lessStartsI(B,C),mostFinishes(C,A).
stable(A):- fixed(B),finishesY(B,C),startsY(C,A).
stable(A):- object(B),rightDuringI(B,C),lessOverlapsLessI(C,A).
stable(A):- object(A),rightDuringI(A,B),pointContact(A,B).
stable(A):- object(B),onI(B,A),mostFinishesI(B,A).
stable(A):- object(B),mostOverlapsMost(B,A),startsYI(B,A).
stable(A):- fixed(C),lessOverlapsLess(C,B),mostOverlapsMostI(B,A).
stable(A):- object(B),rightDuringI(B,A),pointContact(A,B).
stable(A):- mobile(B),on(B,A),mostFinishes(B,A).
stable(A):- fixed(B),lessStartsI(B,C),overlapsY(C,A).
stable(A):- object(B),duringYI(B,C),leftDuringI(C,A).
stable(A):- object(B),rightDuringI(B,A),duringYI(B,A).
stable(A):- object(B),mostOverlapsMost(B,C),lessStarts(C,A).
stable(A):- fixed(B),lessStartsI(B,C),startsY(C,A).
stable(A):- fixed(B),lessOverlapsMost(B,A),surfaceContact(A,B).
stable(A):- object(B),mostOverlapsLessI(B,A),startsY(B,A).
stable(A):- object(B),startsYI(B,A),supports(B,A).
stable(A):- object(C),mostOverlapsLessI(C,A),object(B),lessOverlapsMostI(B,A).
stable(A):- object(B),object(C),lessStarts(C,A),lessOverlapsMostI(B,A).
