stable(A):- fixed(A).
stable(A):- mobile(B),leftDuringI(B,A).
stable(A):- mobile(B),rightDuring(B,A).
stable(A):- fixed(B),mostOverlapsLessI(B,A).
stable(A):- mobile(A),after(A,B),surfaceContact(B,A).
stable(A):- mobile(A),lessOverlapsMost(A,B),supports(A,B).
stable(A):- mobile(A),mostOverlapsMostI(A,B),verticalContact(B,A).
stable(A):- mobile(A),centerDuring(A,B),supports(A,B).
stable(A):- object(A),below(A,B),rightDuringI(B,A).
stable(A):- mobile(A),startsY(A,B),supports(B,A).
stable(A):- object(A),overlapsYI(A,B),lessOverlapsLessI(A,B).
stable(A):- object(A),leftDuringI(A,B),supports(A,B).
stable(A):- object(A),startsYI(A,B),rightDuringI(B,A).
stable(A):- object(A),mostOverlapsMost(A,B),verticalContact(A,B).
stable(A):- object(A),lessOverlapsLessI(A,B),supports(A,B).
stable(A):- above(B,A),object(A),lessOverlapsLess(A,B).
stable(A):- object(A),overlapsY(A,B),rightDuringI(B,A).
stable(A):- object(A),duringY(A,B),after(A,B).
stable(A):- object(A),startsYI(A,B),mostOverlapsLessI(A,B).
stable(A):- object(A),lessFinishes(A,B),on(A,B).
stable(A):- object(A),lessOverlapsLess(A,B),equalY(A,B).
stable(A):- object(A),meets(A,B),duringYI(A,B).
stable(A):- object(A),lessFinishesI(A,B),on(A,B).
stable(A):- object(A),overlapsYI(A,B),mostOverlapsLess(A,B).
stable(A):- mobile(A),centerDuringI(A,B),pointSurfaceContact(A,B).
stable(A):- object(A),lessStarts(A,B),noContact(B,A).
stable(A):- object(A),startsY(A,B),lessOverlapsMostI(A,B).
stable(A):- object(A),onI(A,B),lessFinishes(A,B).
stable(A):- object(A),finishesY(A,B),meetsI(A,B).
stable(A):- object(A),lessFinishesI(A,B),supports(A,B).
stable(A):- object(A),onI(A,B),rightDuringI(B,A).
stable(A):- mobile(A),on(A,B),mostFinishes(A,B).
stable(A):- above(B,A),object(A),mostOverlapsMost(A,B).
stable(A):- object(A),above(B,A),lessFinishes(A,B).
stable(A):- object(A),mostOverlapsLess(A,B),pointContact(B,A).
stable(A):- mobile(A),meetsI(A,B),mostOverlapsMostI(A,B).
stable(A):- mobile(A),startsY(A,B),mostOverlapsLess(A,B).
