stable(A):- object(B),rightDuring(B,A).
stable(A):- object(C),leftDuring(C,B),on(B,A).
stable(A):- object(C),leftDuring(C,B),equalY(B,A).
stable(A):- object(C),rightDuring(C,B),mostOverlapsMost(B,A).
stable(A):- object(A),below(A,B),equal(B,A).
stable(A):- object(B),below(B,A),equal(B,A).
stable(A):- finishesYI(B,A),object(A),centerDuring(A,B).
stable(A):- object(C),leftDuring(C,B),finishesY(B,A).
stable(A):- object(C),leftDuring(C,B),lessOverlapsMost(B,A).
stable(A):- object(C),duringY(C,B),mostOverlapsLess(B,A).
stable(A):- lessStartsI(B,A),object(A),startsY(A,B).
stable(A):- object(A),duringY(A,B),horizontalContact(B,A).
stable(A):- object(B),finishesY(B,A),pointContact(B,A).
stable(A):- object(C),leftDuring(C,B),mostOverlapsMost(B,A).
stable(A):- object(B),rightDuringI(A,B),startsY(B,A).
stable(A):- object(C),leftDuring(C,B),meets(B,A).
stable(A):- object(A),lessFinishesI(B,A),on(A,B).
stable(A):- object(A),lessFinishes(A,B),supports(A,B).
stable(A):- object(A),lessStarts(A,B),fixed(B).
stable(A):- object(C),rightDuring(C,B),on(B,A).
stable(A):- onI(A,B),object(A),mostFinishes(A,B).
stable(A):- object(C),lessOverlapsMost(C,B),lessFinishes(B,A).
stable(A):- object(C),mostOverlapsMost(C,B),lessStarts(B,A).
stable(A):- lessOverlapsMostI(A,B),object(A),overlapsY(A,B).
stable(A):- object(A),overlapsY(A,B),leftDuringI(B,A).
stable(A):- object(C),centerDuring(C,B),centerDuring(B,A).
stable(A):- object(B),duringY(B,A),horizontalContact(B,A).
stable(A):- object(A),meetsI(B,A),mostOverlapsMost(A,B).
stable(A):- object(B),centerDuringI(A,B),finishesY(B,A).