stable(A):- fixed(A).
stable(A):- mobile(B),lessStarts(B,A).
stable(A):- fixed(B),mostOverlapsLessI(B,A).
stable(A):- fixed(B),lessOverlapsLess(B,A).
stable(A):- fixed(B),startsYI(B,A).
stable(A):- object(B),lessFinishesI(B,A).
stable(A):- object(B),lessStartsI(B,A).
stable(A):- fixed(B),lessOverlapsMost(B,A).
stable(A):- object(B),mostFinishesI(B,A).
stable(A):- object(B),mostFinishes(B,A).
stable(A):- mobile(B),lessOverlapsLessI(B,A).
stable(A):- mobile(B),rightDuring(B,A).
stable(A):- fixed(B),duringY(B,A).
stable(A):- mobile(B),leftDuringI(B,A).
stable(A):- mobile(B),rightDuringI(B,A),verticalContact(B,A).
stable(A):- mobile(B),startsYI(B,A),mostOverlapsMostI(A,B).
stable(A):- mobile(B),centerDuringI(B,A),verticalContact(B,A).
stable(A):- mobile(B),meetsI(B,A),startsYI(A,B).
stable(A):- mobile(B),lessOverlapsMost(B,A),on(B,A).
stable(A):- mobile(B),meets(B,A),onI(A,B).
stable(A):- mobile(B),rightDuringI(B,A),noContact(B,A).
stable(A):- mobile(B),mostOverlapsMostI(B,A),overlapsY(B,A).
stable(A):- mobile(B),startsYI(B,A),lessOverlapsLessI(A,B).
stable(A):- mobile(B),finishesYI(B,A),meets(B,A).
stable(A):- mobile(B),duringY(B,A),horizontalContact(B,A).
stable(A):- mobile(B),meetsI(B,A),lessOverlapsMostI(B,A).
stable(A):- mobile(B),duringY(B,A),meetsI(B,A).
stable(A):- mobile(B),on(B,A),lessOverlapsLessI(A,B).
stable(A):- mobile(B),centerDuringI(B,A),on(B,A).
stable(A):- mobile(B),centerDuringI(B,A),pointSurfaceContact(B,A).
stable(A):- mobile(B),mostOverlapsMostI(B,A),overlapsYI(B,A).
stable(A):- mobile(B),startsYI(B,A),mostOverlapsMostI(B,A).
stable(A):- mobile(B),lessOverlapsMostI(B,A),on(B,A).
stable(A):- mobile(B),lessOverlapsMost(B,A),startsYI(A,B).
stable(A):- mobile(A),lessOverlapsMostI(A,B),noContact(B,A).
stable(A):- mobile(B),meets(B,A),startsYI(B,A).
stable(A):- mobile(B),finishesY(B,A),meetsI(B,A).
stable(A):- mobile(B),mostOverlapsLess(B,A),pointSurfaceContact(B,A).
stable(A):- mobile(B),overlapsYI(B,A),lessOverlapsLessI(A,B).
stable(A):- mobile(B),on(B,A),rightDuringI(A,B).
stable(A):- mobile(B),duringYI(B,A),meets(B,A).
