stable(A):- fixed(A).
stable(A):- mobile(A),leftDuringI(A,B),on(B,A).
stable(A):- fixed(C),before(C,B),duringY(B,A).
stable(A):- mobile(A),overlapsYI(A,B),horizontalContact(A,B).
stable(A):- object(B),lessOverlapsLess(B,A),pointContact(A,B).
stable(A):- mobile(A),lessOverlapsLess(A,B),overlapsYI(B,A).
stable(A):- mobile(A),startsYI(A,B),lessOverlapsMostI(B,A).
stable(A):- object(B),mostFinishes(B,A),pointContact(A,B).
stable(A):- mobile(A),below(A,B),lessFinishesI(B,A).
stable(A):- fixed(B),lessOverlapsLessI(B,A),startsY(A,B).
stable(A):- fixed(B),before(B,A),equalY(B,A).
stable(A):- mobile(A),lessOverlapsMostI(A,B),horizontalContact(A,B).
stable(A):- fixed(C),before(C,B),lessStarts(B,A).
stable(A):- mobile(A),mostOverlapsLessI(A,B),finishesY(B,A).
stable(A):- mobile(A),lessOverlapsMostI(A,B),startsYI(B,A).
stable(A):- mobile(A),mostFinishes(A,B),onI(B,A).
stable(A):- mobile(A),mostFinishes(A,B),pointContact(A,B).
stable(A):- fixed(B),before(B,A),startsY(A,B).
stable(A):- mobile(A),leftDuringI(A,B),above(B,A).
stable(A):- mobile(A),overlapsY(A,B),mostOverlapsMost(B,A).
stable(A):- mobile(A),duringY(A,B),lessOverlapsLess(B,A).
stable(A):- mobile(A),startsY(A,B),mostOverlapsLess(B,A).
stable(A):- above(A,B),mobile(B),leftDuringI(B,A).
stable(A):- above(A,B),mobile(A),lessFinishesI(A,B).
stable(A):- mobile(A),below(A,B),lessStarts(B,A).
stable(A):- object(B),rightDuring(B,A),supports(A,B).
stable(A):- mobile(A),mostFinishes(A,B),startsYI(B,A).
stable(A):- object(B),overlapsY(B,A),mostOverlapsMost(A,B).
stable(A):- mobile(A),overlapsYI(A,B),rightDuringI(B,A).
stable(A):- fixed(B),meets(B,A),startsY(A,B).
stable(A):- fixed(B),meets(B,A),on(A,B).
stable(A):- object(B),lessStartsI(B,A),supports(A,B).
stable(A):- mobile(B),leftDuringI(B,A),on(A,B).
stable(A):- mobile(A),onI(A,B),mostFinishes(B,A).
stable(A):- fixed(B),lessOverlapsMost(B,A),supports(B,A).
stable(A):- fixed(B),after(B,A),onI(A,B).
