stable(A):- fixed(A).
stable(A):- object(B),lessOverlapsLess(B,A).
stable(A):- mobile(B),leftDuringI(B,A).
stable(A):- object(B),leftDuring(B,A).
stable(A):- fixed(C),rightDuring(C,B),onI(B,A).
stable(A):- fixed(C),meets(C,B),mostFinishesI(B,A).
stable(A):- fixed(C),rightDuringI(C,B),meets(B,A).
stable(A):- fixed(C),onI(C,B),lessOverlapsMostI(B,A).
stable(A):- fixed(C),mostOverlapsLess(C,B),on(B,A).
stable(A):- fixed(C),centerDuringI(C,B),rightDuringI(B,A).
stable(A):- fixed(B),onI(B,A),equal(B,A).
stable(A):- fixed(C),startsY(C,B),mostOverlapsLess(B,A).
stable(A):- fixed(C),onI(C,B),mostOverlapsMost(B,A).
stable(A):- object(C),mostFinishesI(C,B),centerDuringI(B,A).
stable(A):- fixed(C),rightDuringI(C,B),rightDuringI(B,A).
stable(A):- fixed(B),leftDuringI(B,A),startsYI(A,B).
stable(A):- fixed(C),rightDuringI(C,B),centerDuringI(B,A).
stable(A):- fixed(B),startsY(B,A),centerDuring(A,B).
stable(A):- fixed(C),onI(C,B),lessStartsI(B,A).
stable(A):- fixed(C),onI(C,B),mostOverlapsLessI(B,A).
stable(A):- fixed(C),onI(C,B),mostOverlapsMostI(B,A).
stable(A):- fixed(C),leftDuringI(C,B),lessOverlapsMost(B,A).
stable(A):- fixed(C),startsY(C,B),rightDuring(B,A).
stable(A):- mobile(C),mostFinishesI(C,B),lessOverlapsMost(B,A).
stable(A):- fixed(C),leftDuringI(C,B),centerDuringI(B,A).
