stable(A):- fixed(A).
stable(A):- mobile(B),leftDuringI(B,A).
stable(A):- fixed(B),mostOverlapsLessI(B,A).
stable(A):- object(B),rightDuring(B,A).
stable(A):- object(A),meets(A,B),duringY(B,A).
stable(A):- object(A),mostOverlapsMost(A,B),meets(A,B).
stable(A):- object(A),meetsI(A,B),mostOverlapsMost(B,A).
stable(A):- object(A),lessOverlapsLessI(A,B),supports(A,B).
stable(A):- object(A),lessFinishes(A,B),onI(B,A).
stable(A):- object(A),after(A,B),duringYI(B,A).
stable(A):- object(A),after(A,B),surfaceContact(A,B).
stable(A):- object(C),mostOverlapsMost(C,B),lessOverlapsMostI(B,A).
stable(A):- object(A),mostOverlapsMostI(A,B),on(B,A).
stable(A):- object(A),on(A,B),mostFinishes(A,B).
stable(A):- object(C),mostOverlapsMostI(C,B),lessOverlapsMostI(B,A).
stable(A):- object(A),lessStartsI(A,B),supports(A,B).
stable(A):- object(A),lessOverlapsLessI(A,B),on(A,B).
stable(A):- object(A),lessStarts(A,B),noContact(A,B).
stable(A):- object(A),centerDuringI(A,B),on(A,B).
stable(A):- object(A),startsY(A,B),supports(B,A).
stable(A):- object(A),mostOverlapsLessI(A,B),startsY(B,A).
stable(A):- object(A),lessOverlapsLessI(A,B),startsY(B,A).
stable(A):- object(A),lessOverlapsMostI(A,B),startsY(A,B).
stable(A):- object(A),meetsI(A,B),finishesY(A,B).
stable(A):- object(A),centerDuring(A,B),supports(A,B).
stable(A):- object(A),startsY(A,B),mostOverlapsLessI(B,A).
stable(A):- object(A),lessFinishes(A,B),above(B,A).
stable(A):- object(C),finishesYI(C,B),lessOverlapsMostI(B,A).
stable(A):- object(C),leftDuringI(C,B),lessOverlapsMostI(B,A).
stable(A):- object(A),on(A,B),lessFinishesI(A,B).
stable(A):- object(A),lessOverlapsLess(A,B),on(A,B).
stable(A):- object(A),mostOverlapsLess(A,B),duringYI(B,A).
stable(A):- object(A),lessFinishes(A,B),on(B,A).
stable(A):- object(A),lessFinishesI(A,B),supports(A,B).
stable(A):- object(A),rightDuring(A,B),on(B,A).
