stable(A):- fixed(A).
stable(A):- mobile(B),lessOverlapsLessI(B,A).
stable(A):- fixed(B),mostFinishes(B,A).
stable(A):- mobile(B),below(B,C),lessFinishes(C,A).
stable(A):- fixed(B),rightDuring(B,C),onI(C,A).
stable(A):- mobile(B),meets(B,C),mostOverlapsMost(C,A).
stable(A):- object(B),rightDuring(B,C),lessFinishesI(C,A).
stable(A):- mobile(B),mostOverlapsMost(B,C),mostFinishes(C,A).
stable(A):- fixed(B),lessOverlapsLess(B,C),onI(C,A).
stable(A):- mobile(B),below(B,C),leftDuringI(C,A).
stable(A):- mobile(B),centerDuringI(B,A),below(A,B).
stable(A):- mobile(B),centerDuringI(B,C),meets(C,A).
stable(A):- mobile(B),meets(B,A),below(A,B).
stable(A):- fixed(B),rightDuring(B,C),rightDuringI(C,A).
stable(A):- mobile(B),equalY(B,A),horizontalContact(B,A).
stable(A):- mobile(B),lessOverlapsLessI(B,C),on(C,A).
stable(A):- mobile(B),lessFinishes(B,C),meetsI(C,A).
