stable(A):- fixed(A).
stable(A):- object(B),duringY(B,A).
stable(A):- fixed(B),startsYI(B,A).
stable(A):- mobile(B),startsYI(B,A),meets(A,B).
stable(A):- mobile(B),startsYI(B,C),mostOverlapsMost(C,A).
stable(A):- mobile(B),startsYI(B,C),overlapsY(C,A).
stable(A):- mobile(B),startsYI(B,C),rightDuring(C,A).
stable(A):- mobile(B),startsYI(B,C),lessOverlapsMost(C,A).
stable(A):- mobile(B),startsYI(B,C),mostOverlapsLessI(C,A).
stable(A):- mobile(B),lessFinishesI(B,C),duringYI(C,A).
stable(A):- mobile(B),startsYI(B,C),lessStarts(C,A).
stable(A):- mobile(B),startsYI(B,C),lessFinishesI(C,A).
stable(A):- mobile(B),startsYI(B,C),duringYI(C,A).
stable(A):- mobile(B),duringYI(B,A),meets(A,B).
stable(A):- mobile(B),lessFinishesI(B,C),overlapsYI(C,A).
stable(A):- mobile(B),lessFinishesI(B,C),centerDuring(C,A).
stable(A):- mobile(B),finishesY(B,A),meets(A,B).
stable(A):- mobile(B),startsYI(B,C),mostFinishesI(C,A).
stable(A):- mobile(B),startsYI(B,C),lessFinishes(C,A).
