stable(A):- fixed(A).
stable(A):- object(B),duringY(B,A).
stable(A):- fixed(B),lessOverlapsMost(B,A).
stable(A):- mobile(C),mostFinishes(C,B),leftDuringI(B,A).
stable(A):- mobile(C),duringYI(C,B),lessFinishes(B,A).
stable(A):- fixed(B),centerDuringI(B,A),surfaceContact(B,A).
stable(A):- mobile(C),startsY(C,B),mostFinishesI(B,A).
stable(A):- mobile(C),duringYI(C,B),mostOverlapsLessI(B,A).
stable(A):- fixed(B),centerDuringI(B,C),duringYI(C,A).
stable(A):- fixed(B),rightDuringI(B,A),on(A,B).
stable(A):- fixed(B),leftDuringI(B,C),lessOverlapsLessI(C,A).
stable(A):- mobile(C),startsY(C,B),centerDuringI(B,A).
stable(A):- fixed(B),mostOverlapsLessI(B,C),on(C,A).
stable(A):- mobile(C),duringYI(C,B),onI(B,A).
stable(A):- mobile(C),duringYI(C,B),mostOverlapsMost(B,A).
stable(A):- mobile(C),duringYI(C,B),startsY(B,A).
stable(A):- mobile(C),startsY(C,B),mostOverlapsLess(B,A).
stable(A):- mobile(C),startsY(C,B),mostOverlapsMostI(B,A).
stable(A):- fixed(B),lessOverlapsMost(B,C),onI(C,A).
stable(A):- mobile(C),duringYI(C,B),lessStarts(B,A).
stable(A):- mobile(C),duringYI(C,B),mostFinishesI(B,A).
stable(A):- mobile(C),duringYI(C,B),meets(B,A).
stable(A):- fixed(B),leftDuringI(B,C),startsYI(C,A).
stable(A):- fixed(B),leftDuringI(B,C),rightDuringI(C,A).
stable(A):- fixed(B),onI(B,A),equal(A,B).
stable(A):- fixed(B),leftDuringI(B,C),duringYI(C,A).
stable(A):- fixed(B),startsY(B,C),centerDuringI(C,A).
stable(A):- mobile(C),startsY(C,B),below(B,A).
stable(A):- fixed(B),lessStartsI(B,C),startsYI(C,A).
stable(A):- mobile(C),mostOverlapsMostI(C,B),finishesY(B,A).
