stable(A):- fixed(A).
stable(A):- fixed(B),mostOverlapsMost(B,A).
stable(A):- object(B),lessStarts(B,A).
stable(A):- mobile(C),lessOverlapsLess(C,B),startsY(B,A).
stable(A):- mobile(C),onI(C,B),lessFinishesI(B,A).
stable(A):- mobile(C),centerDuring(C,B),leftDuringI(B,A).
stable(A):- mobile(C),meets(C,B),mostFinishesI(B,A).
stable(A):- mobile(C),leftDuring(C,B),duringYI(B,A).
stable(A):- mobile(C),lessFinishesI(C,B),meets(B,A).
stable(A):- mobile(C),lessFinishes(C,B),leftDuringI(B,A).
stable(A):- mobile(C),mostOverlapsLess(C,B),duringY(B,A).
stable(A):- mobile(C),centerDuring(C,B),mostOverlapsMost(B,A).
stable(A):- mobile(C),lessFinishes(C,B),lessStartsI(B,A).
stable(A):- mobile(C),overlapsY(C,B),lessStartsI(B,A).
stable(A):- mobile(C),rightDuring(C,B),meetsI(B,A).
stable(A):- mobile(C),lessFinishes(C,B),finishesY(B,A).
stable(A):- mobile(C),finishesYI(C,B),meets(B,A).
stable(A):- mobile(C),finishesYI(C,B),mostFinishes(B,A).
stable(A):- mobile(C),overlapsYI(C,B),on(B,A).
stable(A):- mobile(C),startsYI(C,B),mostOverlapsLessI(B,A).
stable(A):- mobile(C),lessFinishes(C,B),mostOverlapsLessI(B,A).
stable(A):- mobile(C),centerDuringI(C,B),mostOverlapsMostI(B,A).
stable(A):- mobile(C),on(C,B),mostFinishes(B,A).
