stable(A):- fixed(A).
stable(A):- object(B),mostOverlapsLess(B,A),verticalContact(B,A).
stable(A):- above(B,A),mobile(B),lessOverlapsLessI(B,A).
stable(A):- object(B),onI(B,A),leftDuring(A,B).
stable(A):- object(B),lessStartsI(B,C),meets(C,A).
stable(A):- object(B),on(B,A),rightDuringI(A,B).
stable(A):- object(A),lessOverlapsMostI(A,B),verticalContact(B,A).
stable(A):- mobile(B),mostOverlapsLess(B,C),meets(C,A).
stable(A):- object(B),leftDuringI(B,C),after(C,A).
stable(A):- mobile(B),lessFinishes(B,C),meetsI(C,A).
stable(A):- object(B),below(B,A),equal(B,A).
stable(A):- object(B),rightDuringI(B,A),on(A,B).
stable(A):- object(A),lessOverlapsLess(A,B),surfaceContact(A,B).
stable(A):- object(A),mostOverlapsLess(A,B),verticalContact(B,A).
stable(A):- fixed(B),startsY(B,C),centerDuringI(C,A),onI(C,A).
stable(A):- fixed(B),startsY(B,C),onI(C,A),pointContact(A,C).
stable(A):- object(A),mostOverlapsMost(A,C),fixed(B),startsY(B,C).
stable(A):- fixed(B),startsY(B,C),rightDuring(C,B),startsY(B,A).
