stable(A):- fixed(A).
stable(A):- mobile(B),lessOverlapsLessI(B,A).
stable(A):- object(B),mostOverlapsLessI(B,C),meetsI(C,A).
stable(A):- object(B),lessOverlapsMost(B,C),meetsI(C,A).
stable(A):- object(B),meetsI(B,A),pointContact(A,B).
stable(A):- fixed(C),centerDuringI(C,B),lessFinishesI(B,A).
stable(A):- object(B),lessFinishes(B,C),meets(C,A).
stable(A):- object(B),lessOverlapsLess(B,C),mostOverlapsMost(C,A).
stable(A):- fixed(C),on(C,B),on(B,A).
stable(A):- object(B),lessOverlapsLess(B,C),below(C,A).
stable(A):- object(B),lessStarts(B,C),meets(C,A).
stable(A):- object(B),mostOverlapsLess(B,A),below(A,B).
stable(A):- object(B),mostOverlapsLessI(B,C),lessOverlapsMost(C,A).
stable(A):- object(B),lessFinishes(B,C),mostOverlapsLessI(C,A).
stable(A):- object(B),lessStarts(B,C),mostOverlapsLessI(C,A).
stable(A):- fixed(C),onI(C,B),mostFinishes(B,A).
stable(A):- fixed(C),centerDuring(C,B),onI(B,A).
stable(A):- object(B),lessOverlapsLess(B,C),onI(C,A).
stable(A):- object(B),lessFinishes(B,C),mostOverlapsMostI(C,A).
stable(A):- object(B),mostOverlapsMostI(B,C),centerDuring(C,A).
