stable(A):- fixed(A).
stable(A):- fixed(B),overlapsYI(B,A).
stable(A):- fixed(B),mostOverlapsMost(B,A).
stable(A):- fixed(B),duringY(B,A).
stable(A):- fixed(B),mostFinishes(B,A).
stable(A):- fixed(B),mostFinishesI(B,A).
stable(A):- object(A),mostFinishesI(A,B),startsY(B,A).
stable(A):- object(A),mostFinishesI(A,B),pointContact(B,A).
stable(A):- object(A),mostFinishesI(A,B),on(B,A).
