stable(A):- fixed(A).
stable(A):- object(C),lessStartsI(C,B),mostFinishes(B,A).
stable(A):- above(A,B),object(A),lessFinishesI(A,B).
stable(A):- object(A),meets(A,B),supports(B,A).
stable(A):- fixed(C),lessStartsI(C,B),startsYI(B,A).
stable(A):- fixed(C),lessFinishesI(C,B),startsYI(B,A).
stable(A):- object(A),startsY(A,B),supports(B,A).
stable(A):- fixed(C),lessOverlapsLessI(C,B),finishesYI(B,A).
stable(A):- object(A),meetsI(A,B),supports(A,B).
stable(A):- object(B),lessOverlapsMostI(B,C),lessOverlapsMostI(C,A).
stable(A):- fixed(C),overlapsYI(C,B),startsY(B,A).
stable(A):- fixed(C),rightDuring(C,B),equalY(B,A).
stable(A):- fixed(C),lessOverlapsLessI(C,B),duringYI(B,A).
stable(A):- object(A),lessOverlapsLessI(A,B),overlapsYI(B,A).
stable(A):- object(B),lessOverlapsMost(B,C),rightDuringI(C,A).
stable(A):- fixed(C),lessStartsI(C,B),startsY(B,A).
stable(A):- fixed(C),startsYI(C,B),meetsI(B,A).
stable(A):- fixed(C),lessStartsI(C,B),duringYI(B,A).
stable(A):- object(A),startsY(A,B),lessOverlapsLess(B,A).
stable(A):- mobile(C),lessFinishesI(C,B),mostOverlapsMostI(B,A).
stable(A):- fixed(C),mostOverlapsMostI(C,B),finishesY(B,A).
stable(A):- object(B),mostOverlapsLessI(B,C),mostOverlapsLessI(C,A).
stable(A):- fixed(C),lessOverlapsLessI(C,B),below(B,A).
stable(A):- object(A),rightDuringI(A,B),duringY(B,A).
stable(A):- object(A),duringY(A,B),rightDuringI(B,A).
stable(A):- object(B),duringYI(B,C),leftDuringI(C,A).
stable(A):- object(B),lessFinishesI(B,C),lessOverlapsMost(C,A).
stable(A):- mobile(B),lessFinishesI(B,A),onI(B,A).
stable(A):- fixed(C),lessOverlapsLessI(C,B),overlapsY(B,A).
stable(A):- fixed(C),rightDuringI(C,B),lessOverlapsLessI(B,A).
stable(A):- object(A),lessOverlapsLess(A,B),pointContact(B,A).
stable(A):- object(B),leftDuring(B,C),meets(C,A).
stable(A):- object(B),rightDuring(B,C),lessStartsI(C,A).
stable(A):- fixed(B),lessOverlapsMost(B,A),pointSurfaceContact(B,A).
stable(A):- mobile(B),on(B,A),mostFinishes(B,A).
stable(A):- fixed(C),lessStartsI(C,B),finishesYI(B,A).
stable(A):- object(B),rightDuring(B,C),overlapsYI(C,A).
stable(A):- object(A),onI(A,B),lessFinishes(B,A).
stable(A):- object(B),mostOverlapsLess(B,A),duringYI(A,B).
stable(A):- fixed(C),lessStartsI(C,B),overlapsY(B,A).
stable(A):- fixed(C),lessOverlapsLess(C,B),mostOverlapsMostI(B,A).
stable(A):- fixed(B),mostOverlapsLessI(B,A),startsYI(A,B).
stable(A):- object(A),on(A,B),mostFinishesI(B,A).
stable(A):- object(A),mostOverlapsLess(A,B),duringYI(B,A).
stable(A):- above(B,A),object(A),lessFinishes(A,B).
stable(A):- mobile(A),after(A,B),duringYI(B,C),rightDuringI(B,C).
stable(A):- mobile(A),after(A,B),centerDuring(A,C),supports(B,C).
stable(A):- mobile(A),after(A,B),leftDuring(A,C),duringY(C,B).
stable(A):- mobile(A),rightDuring(A,C),after(A,B),overlapsYI(C,B).
stable(A):- mobile(A),after(A,B),startsY(A,C),leftDuring(C,B).
