stable(A):- fixed(A).
stable(A):- fixed(B),centerDuring(B,A).
stable(A):- fixed(B),mostOverlapsMost(B,A).
stable(A):- mobile(B),lessStarts(B,A).
stable(A):- mobile(C),mostOverlapsMostI(C,B),meetsI(B,A).
stable(A):- fixed(C),rightDuringI(C,B),startsY(B,A).
stable(A):- mobile(B),meetsI(B,A),overlapsYI(A,B).
stable(A):- fixed(C),mostOverlapsLess(C,B),lessOverlapsLess(B,A).
stable(A):- fixed(C),rightDuringI(C,B),meets(B,A).
stable(A):- object(A),startsY(A,B),meetsI(B,A).
stable(A):- fixed(C),startsYI(C,B),mostOverlapsLessI(B,A).
stable(A):- fixed(C),startsYI(C,B),lessOverlapsMost(B,A).
stable(A):- fixed(C),finishesY(C,B),meetsI(B,A).
stable(A):- mobile(C),lessStarts(C,B),meetsI(B,A).
stable(A):- object(A),finishesY(A,B),meetsI(B,A).
stable(A):- fixed(C),rightDuringI(C,B),mostOverlapsMost(B,A).
stable(A):- fixed(C),mostOverlapsMostI(C,B),overlapsY(B,A).
stable(A):- fixed(C),rightDuringI(C,B),leftDuringI(B,A).
stable(A):- mobile(A),duringYI(A,B),meetsI(B,A).
stable(A):- mobile(C),rightDuring(C,B),meetsI(B,A).
stable(A):- fixed(C),rightDuringI(C,B),mostOverlapsLessI(B,A).
