stable(A):- fixed(A).
stable(A):- object(B),lessStarts(B,A).
stable(A):- fixed(B),rightDuringI(B,C),meets(C,A).
stable(A):- fixed(B),startsY(B,C),mostFinishesI(C,A).
stable(A):- fixed(B),leftDuring(B,C),startsY(C,A).
stable(A):- fixed(B),below(B,C),lessFinishesI(C,A).
stable(A):- fixed(B),lessFinishesI(B,C),below(C,A).
stable(A):- object(B),lessFinishes(B,C),meets(C,A).
stable(A):- fixed(B),rightDuringI(B,C),centerDuring(C,A).
stable(A):- fixed(B),centerDuringI(B,C),meets(C,A).
stable(A):- fixed(B),on(B,A),mostOverlapsMostI(B,A).
stable(A):- fixed(B),startsY(B,C),mostFinishes(C,A).
stable(A):- fixed(B),lessStartsI(B,C),centerDuring(C,A).
stable(A):- fixed(B),before(B,C),lessOverlapsLess(C,A).
stable(A):- fixed(B),lessFinishesI(B,C),onI(C,A).
stable(A):- fixed(C),overlapsY(C,B),lessOverlapsMost(B,A).
stable(A):- object(B),lessFinishes(B,C),finishesY(C,A).
stable(A):- fixed(B),below(B,C),rightDuringI(C,A).
stable(A):- fixed(B),leftDuringI(B,A),onI(B,A).
stable(A):- mobile(A),leftDuring(A,B),surfaceContact(A,B).
stable(A):- mobile(C),overlapsY(C,B),mostOverlapsLess(B,A).
stable(A):- fixed(B),lessFinishesI(B,C),startsY(C,A).
stable(A):- fixed(B),onI(B,A),rightDuringI(A,B).
stable(A):- fixed(B),startsY(B,A),pointContact(B,A).
stable(A):- fixed(B),centerDuringI(B,A),onI(B,A).
stable(A):- object(B),lessFinishes(B,C),lessStartsI(C,A).
stable(A):- fixed(B),before(B,C),lessOverlapsMost(C,A).
