stable(A):- object(B),duringY(B,C),lessOverlapsLess(C,A).
stable(A):- object(B),meets(B,C),lessFinishes(C,A).
stable(A):- object(A),rightDuring(A,B),recursive_supports(A,B).
stable(A):- object(B),mostOverlapsLess(B,A),startsY(A,B).
stable(A):- object(A),lessOverlapsMost(A,B),recursive_supports(A,B).
stable(A):- object(A),mostOverlapsMost(A,B),pointContact(B,A).
stable(A):- object(A),meets(A,B),overlapsYI(B,A).
stable(A):- object(B),duringY(B,C),below(C,A).
stable(A):- object(A),meets(A,B),supports(A,B).
stable(A):- object(B),leftDuring(B,C),meets(C,A).
stable(A):- object(B),startsY(B,C),rightDuring(C,A).
stable(A):- object(A),finishesY(A,B),horizontalContact(B,A).
stable(A):- object(B),lessFinishes(B,C),mostOverlapsMost(C,A).
stable(A):- object(B),duringY(B,A),horizontalContact(B,A).
stable(A):- object(B),startsY(B,A),mostOverlapsLessI(A,B).
stable(A):- object(B),on(B,A),lessStarts(A,B).
stable(A):- object(A),lessFinishes(A,B),recursive_supports(B,A).
stable(A):- above(B,A),object(B),mostFinishes(B,A).
stable(A):- object(B),finishesY(B,C),lessOverlapsMost(C,A).
stable(A):- object(A),startsY(A,B),supports(A,B).
stable(A):- object(A),lessStarts(A,B),recursive_supports(B,A).
stable(A):- object(B),lessStarts(B,A),pointSurfaceContact(B,A).
stable(A):- object(A),duringY(A,B),horizontalContact(A,B).
stable(A):- object(A),mostFinishesI(B,A),overlapsY(A,B).
stable(A):- object(B),mostOverlapsMost(B,A),startsY(B,A).
stable(A):- object(A),lessFinishes(A,B),duringY(A,B).
stable(A):- object(B),lessOverlapsMost(B,C),lessStarts(C,A).
stable(A):- mostOverlapsMostI(B,A),object(A),meets(A,B).
stable(A):- object(B),overlapsY(B,C),finishesY(C,A).
stable(A):- object(B),mostOverlapsLess(B,A),recursive_supports(A,B).
stable(A):- object(B),leftDuringI(B,A),on(B,A).
stable(A):- object(B),rightDuring(B,C),overlapsY(C,A).
stable(A):- object(B),lessOverlapsMost(B,A),recursive_supports(B,A).
stable(A):- object(B),meets(B,A),mostOverlapsMostI(A,B).
stable(A):- object(B),finishesY(B,A),surfaceContact(B,A).
stable(A):- rightDuringI(B,A),object(B),on(B,A).
stable(A):- above(B,A),object(B),lessStarts(B,A).
stable(A):- object(A),lessFinishes(A,B),pointSurfaceContact(B,A).