stable(A):- fixed(A).
stable(A):- fixed(B),mostOverlapsMost(B,A).
stable(A):- object(B),lessStarts(B,A).
stable(A):- mobile(C),lessFinishes(C,B),leftDuringI(B,A).
stable(A):- mobile(C),mostFinishes(C,B),meets(B,A).
stable(A):- mobile(C),lessFinishes(C,B),lessStartsI(B,A).
stable(A):- mobile(C),mostFinishes(C,B),startsYI(B,A).
stable(A):- mobile(C),mostOverlapsLessI(C,B),overlapsYI(B,A).
stable(A):- fixed(C),overlapsY(C,B),lessOverlapsLess(B,A).
stable(A):- mobile(C),meets(C,B),lessFinishesI(B,A).
stable(A):- mobile(C),lessFinishes(C,B),lessOverlapsMost(B,A).
stable(A):- mobile(C),mostFinishes(C,B),overlapsY(B,A).
stable(A):- mobile(C),mostOverlapsLessI(C,B),mostOverlapsMostI(B,A).
stable(A):- mobile(C),rightDuringI(C,B),lessOverlapsMostI(B,A).
stable(A):- object(C),overlapsY(C,B),centerDuringI(B,A).
stable(A):- mobile(C),after(C,B),mostFinishes(B,A).
stable(A):- mobile(C),mostFinishes(C,B),overlapsYI(B,A).
stable(A):- mobile(C),meets(C,B),rightDuringI(B,A).
stable(A):- mobile(C),startsY(C,B),mostFinishesI(B,A).
stable(A):- mobile(C),lessFinishesI(C,B),meets(B,A).
stable(A):- mobile(C),startsYI(C,B),mostOverlapsLessI(B,A).
stable(A):- mobile(C),lessStarts(C,B),mostOverlapsLessI(B,A).
stable(A):- mobile(C),mostFinishesI(C,B),startsYI(B,A).
stable(A):- mobile(C),startsY(C,B),finishesY(B,A).
stable(A):- mobile(C),mostFinishes(C,B),lessOverlapsLessI(B,A).
stable(A):- mobile(C),startsYI(C,B),lessOverlapsMost(B,A).
